### ISSUE TITLE
abort if dest device is mounted

### ISSUE THREAD

**Issue by curu** [axboe/fio#1007]
some user may copy fio test command from the internet and set -filename=/dev/vdb, which  contains valuable data, and would be  destroied after running fio.

we should abort if -filename is set to a device file and the device or partition is already mounted, prevent possible data loss.

**Comment by sitsofe** [comment]
Before we go further I can't stress the following enough: I recommend people should not access raw disks/block devices unless they KNOW they can afford to irrecoverably lose the data on it.

@curu I'm afraid this (people destroying their data by accident) can happen and there's only so much that can be done. I would think it would be better for all those giving the example on the internet to update their text to include a warning that says: "don't run this command on disks device that has data you can't afford to irrecoverably lose".

However back to your original point: notice what you used as your example - `/dev/vdb`. It's very unlikely people mount a filesystem over the whole "disk" block device. Usually you partition it the disk and then mount the filesystem atop that partition (e.g. the filesystem would be on `/dev/vdb1`). If you look in https://github.com/axboe/fio/blob/9caaf02b06deecf0b0a13c16b6d59dddc64b8c35/lib/mountcheck.c#L11 you'll see code that actually checks for this later (you're accessing the direct device (e.g. partition) the filesystem is on) BUT it can't handle the former (accessing the **device the partition is on** where the partition has a mounted filesystem) because the filesystem is at least once removed from it! Further the OS itself has made a design decision - OSes like FreeBSD and Windows don't let you write to raw disk if you have ANY partitions on it (and this is enforced by the kernel) whereas Linux will so it's the case that on Linux you can do something dangerous and nothing will stop you. Note this doesn't apply just to fio, even tools like `dd` can destroy your data and that doesn't even attempt to warn in any situation.

I'm going to close this because I don't think it's easy to do better than what we currently have without a huge amount of work (what happens when it's a filesystem on top a device mapper device on top of a partition on top of a block device?). However, if someone submits a patch that makes the checks even more robust we'll definitely review it (maybe https://github.com/karelzak/util-linux/blob/master/misc-utils/lsblk.c will give some ideas?).
