### ISSUE TITLE
fio: setsockopt: Protocol not available

### ISSUE THREAD

**Issue by KayGuoWhu** [axboe/fio#101]
I executed the command "fio --server" in the shell, but it occurred the error "fio: setsockopt: Protocol not available".
I failed to find a similar problem or solution in Google.:-(

**Comment by axboe** [comment]
Can you retry with the current tree? There are two setsockopt calls in the server code, and unfortunately I can't tell which one it is from message above.

**Comment by guenthert** [comment]
Well, the issue seems to be still present in the current code ('master.zip' retrieved 2016-02-09), compiled and executed on Debian Wheezy (yeah, it's old, can't do anything about it):
--8<--
17092 open("/proc/meminfo", O_RDONLY|O_CLOEXEC) = 4
17092 fstat(4, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
17092 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0868aae000
17092 read(4, "MemTotal:       33006416 kB\nMemF"..., 1024) = 1024
17092 close(4)                          = 0
17092 munmap(0x7f0868aae000, 4096)      = 0
17092 open("/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 4
17092 read(4, "0-5\n", 8192)            = 4
17092 close(4)                          = 0
17092 sched_getaffinity(17092, 128, {3f, 0, 0, 0, 0, 0, 0, 0}) = 64
17092 socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 4
17092 setsockopt(4, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
17092 setsockopt(4, SOL_SOCKET, SO_REUSEPORT, [1], 4) = -1 ENOPROTOOPT (Protocol not available)
17092 write(2, "fio: setsockopt(REUSEPORT): Prot"..., 51) = 51
17092 close(4)                          = 0
-->8--

**Comment by axboe** [comment]
http://git.kernel.dk/cgit/fio/commit/?id=8a768c2e725d6a527b904570949f6099c3f1434a

This should fix it for you. We don't need to make the SO_REUSEPORT error fatal.

**Comment by guenthert** [comment]
Yes, that fixes (or bypasses rather) the setsocket() issue, thanks!
