### ISSUE TITLE
Feature request: percentiles for submission/total latency

### ISSUE THREAD

**Issue by alexander-f** [axboe/fio#102]
Is there any technical reason or problem with the definition of the value why latency percentiles are only printed for the completion latencies (clat percentiles (usec)), but not for submit latency and/or total latency, which look more relevant for an application depending on low IO latencies?

From the HOWTO: "For sync io, the slat is really the completion latency, since queue/complete is one operation there" and "For sync io, clat will usually be equal (or very close) to 0" (which seems like it makes clat percentiles actually useless).

For the total latency, I get the distribution
     lat (msec): 2=1.6%, 4=0.0%, 10=3.2%, 20=12.8%, 50=38.4%, 100=24.8%,
     lat (msec): 250=15.2%, 500=0.0%, 750=0.0%, 1000=0.0%, >=2048=0.0%
but this is not 100% equivalent to the percentiles.

**Comment by alexander-f** [comment]
P.S.: And the lat (msec) distribution does not differentiate between read and write.

**Comment by sitsofe** [comment]
It's not exactly what's been asked for but it's possible to select that the latency percentiles shown should be for either completion latencies (http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-clat-percentiles ) or total latencies (http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-lat-percentiles ) instead of the default submission latencies. It's also worth noting the json+ format (http://fio.readthedocs.io/en/latest/fio_doc.html#id1 ) shows multiple latency percentiles types.

**Comment by vincentkfu** [comment]
I didn't realize there was actually an issue open for this feature, but this should be resolved with https://github.com/axboe/fio/pull/920

**Comment by sitsofe** [comment]
I'm closing this request as it's been done - good spot Vincent!
