### ISSUE TITLE
fio iops constantly dropped to zero during the test

### ISSUE THREAD

**Issue by rainning** [axboe/fio#1076]
I ran 4k randwrite test in my VM (KVM + QEMU) against a ceph rbd device, and found that iops fluctuated dramatically and even dropped to zero constantly. Meahwhile, I also ran iostat, and found that the corresponding ops also dropped to zero while fio showed zero iops. It seems to me that fio stopped generating io requests during the period for some reasons. Is my guess true? If so, what underlying factors will affect fio generating io requests? The queue is full?

**Comment by sitsofe** [comment]
>  It seems to me that fio stopped generating io requests during the period for some reasons. Is my guess true? If so, what underlying factors will affect fio generating io requests? The queue is full?

@rainning Unfortunately there is not enough information here to begin to answer this question. At a bare minimum we need the information asked for in https://github.com/axboe/fio/blob/master/REPORTING-BUGS . Could you follow up with that information?

The overall question is still a vague though. How can we know that your Ceph backend isn't suspect? How can we know that KVM/QEMU isn't at issue? What does fio say the latency of your I/Os is (is it taking a long time for an I/O to come back)? How many I/Os is fio allowed to keep in flight simultaneously? Would it be wiser to test more discrete parts of your infrastructure so there are less places to look for problems? We can only be go so far due to time but let's see where we get to after you post more information.

**Comment by rainning** [comment]
@sitsofe First of all, thanks for your reply.

Actually, I am not reporting bugs of fio, but just try to get a quick answer about how fio generates io requests and keeps the configured load. Maybe here is not the right place to ask this kind questions. I am sorry for that. We are investigating KVM/QEMU, network, and Ceph. I just have some tentative thoughts that some underlying factors that cause fio to temporarily stop generating io requests. I am new to the fio source code, and just started reading it. I noticed that there is some implementation (https://github.com/axboe/fio/blob/84106576cefbbd9f5dfa5ee33b245f77938d0269/backend.c#L1071), not sure if it is the underlying factor I mentioned.

**Comment by sitsofe** [comment]
@rainning We would need to see the job file to know if you are likely hitting that. For example, if you allow only one I/O outstanding then fio can't send any more until that I/O is serviced (thus you hit queue_full). Could you post the job file please?

**Comment by rainning** [comment]
@sitsofe there is no job file, we just use command line like:
`fio --filename=/dev/rbd5 --ioengine=libaio --rw=randwrite --bs=4k --size=100G --iodepth=32 --numjobs=16 --direct=1 --runtime=480 --name=randwrite --group_reporting`
then we observed that iops constantly dropped to zero during the test.

**Comment by rainning** [comment]
@sitsofe is there any configuration for the number of outstanding I/O allowed?

**Comment by rainning** [comment]
Closed and going to move to the mailing list.

**Comment by sitsofe** [comment]
(There will be some maximum number of I/Os that can be kept in flight by your system. If that number is exceeded (plus some kernel queue length) then calls to libaio submissions will start blocking. See https://github.com/axboe/fio/issues/1046#issuecomment-662284037 for some discussion about because you are likely well over the default for Ceph's queue default which is apparently 128.  Do you see the same problem if the *total* number of I/Os is less than 128? But you're likely better off asking the Ceph folks for their advice on this)

**Comment by rainning** [comment]
@sitsofe Thanks for your reply. Yes, I did observe the rbd device's queue size reaching the maximum value (`/sys/block/<rbd device>/queue/nr_requests`) from `iostat`. As far as if the phenomenon is still observable when the queue size is less than the maximum number, I don't recall. Let me double check.
