### ISSUE TITLE
libumem.so. will support Solaris 11.4.23.69.3

### ISSUE THREAD

**Issue by Vikram0511** [axboe/fio#1091]
We are using libumem.so in Solaris 11.4 (11.4.16.4.0) which is working fine. But in Solaris 11.4 (11.4.23.69.3) is not working. Can any one help on this issue.

**Comment by sitsofe** [comment]
@Vikram0511 it's going to be tricky because we're not Solaris users (and I don't have access to Solaris) but if you tell us more who knows? :-)

For starters, can you include the information requested in https://github.com/axboe/fio/blob/master/REPORTING-BUGS ? Thanks!

(mentioning @szaydel who has helped out on other Solaris issues)

**Comment by sitsofe** [comment]
@Vikram0511 ping?

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen and post the requested information. Thanks!
