### ISSUE TITLE
how can i print the address requested by the ram from the hard drive 

### ISSUE THREAD

**Issue by HrithikSampson** [axboe/fio#1106]

**Comment by HrithikSampson** [comment]
Where can i find the adress accessed to the hard disk

**Comment by sitsofe** [comment]
@HrithikSampson I'm sorry I'm struggling to understand your question and you haven't provided any context (is this even a question about fio? If so are you running it on Linux? What version of fio? Do you mean LBA or do you mean offset in the file? etc.)

> how can i print the address requested by the ram from the hard drive

Because your question is ambiguous I will give a vague answer to how I interpreted it:

> If fio requests a particular offset in a file on Linux how can I know which real LBA of the disk was requested?

Fio doesn't know because there could be any sort of indirection/abstraction between fio and the disk such a filesystem, on Linux device mapper (which can rearrange block offsets), software RAID. From a userspace perspective these layers are opaque.

@HrithikSampson if this doesn't answer your question can you clarify at least all of the above questions? Thanks!

**Comment by HrithikSampson** [comment]
i want to print the disk addresses can you recommend me some benchmark which will print me the disk addresses

**Comment by HrithikSampson** [comment]
thank you for replying

**Comment by sitsofe** [comment]
> i want to print the disk addresses can you recommend me some benchmark which will print me the disk addresses

I'm afraid you restated your question without answering any of my questions :-). Just to be clear, can you answer **ALL** of the following:

> @HrithikSampson I'm sorry I'm struggling to understand your question and you haven't provided any context (is this even a question about fio? If so are you running it on Linux? What version of fio? Do you mean LBA or do you mean offset in the file? etc.)

**Comment by HrithikSampson** [comment]
I am running it on linux. probably 3.17. I mean LBA+offset

**Comment by HrithikSampson** [comment]
i'm sorry i need only offset

**Comment by axboe** [comment]
For file offset, just see ```write_iolog```

**Comment by axboe** [comment]
And if you need to figure out what LBAs are accessed, then you can look at something like blktrace.

Closing this one up, you should have the info you need.

**Comment by HrithikSampson** [comment]
thank you
