### ISSUE TITLE
Difference between lat, slat and clat ? 

### ISSUE THREAD

**Issue by vschiavoni** [axboe/fio#1110]
Hi,
in the FIO documentation, the 3 latency values reported are documented separately, as follows:
([https://fio.readthedocs.io/en/latest/fio_doc.html#interpreting-the-output](https://fio.readthedocs.io/en/latest/fio_doc.html#interpreting-the-output))
**slat**
_Submission latency (min being the minimum, max being the maximum, avg being the average, stdev being the standard deviation). This is the time it took to submit the I/O. For sync I/O this row is not displayed as the slat is really the completion latency (since queue/complete is one operation there). This value can be in nanoseconds, microseconds or milliseconds — fio will choose the most appropriate base and print that (in the example above nanoseconds was the best scale). 
Note: in --minimal mode latencies are always expressed in microseconds._
**clat**
_Completion latency. Same names as slat, this denotes the time from submission to completion of the I/O pieces. For sync I/O, clat will usually be equal (or very close) to 0, as the time from submit to complete is basically just CPU time (I/O has already been done, see slat explanation)._
**lat**
_Total latency. Same names as slat and clat, this denotes the time from when fio created the I/O unit to completion of the I/O operation._

Now, from these descriptions, I do not understand what is the relation (if there is one) between lat, clat and slat. 
While websites ([https://tobert.github.io/post/2014-04-17-fio-output-explained.html](https://tobert.github.io/post/2014-04-17-fio-output-explained.html)) suggest that **lat !=clat+slat**, I would still like to have this somehow clarified. 
This can be either by improving the documentation, or at least by explaining better how those are computed so that one can make his understanding. 

Thanks !

**Comment by sitsofe** [comment]
(We're definitely open to patches that provide a clearer explanation! Would you like to submit one?)

So first up it depends on whether you have a synchronous or an asynchronous I/O engine. "Clearly" when I/O is being submitted synchronously you can't separate submission latency from completion latency right? (First question: why?)

(We're definitely open to patches that provide a clearer explanation! Would you like to submit one?)

As I'm short on time I'm just going to leave links for now:
- https://github.com/axboe/fio/blob/fio-3.23/io_u.c#L1799
- https://github.com/axboe/fio/blob/fio-3.23/engines/io_uring.c#L426 (example async)
- https://github.com/axboe/fio/blob/fio-3.23/io_u.c#L2053
- https://github.com/axboe/fio/blob/fio-3.23/io_u.c#L1874
- https://github.com/axboe/fio/blob/fio-3.23/io_u.c#L1879
- https://github.com/axboe/fio/blob/fio-3.23/io_u.c#L1899

From what I can see on a per I/O basis for an async ioengine `slat + clat = lat` ?

**Comment by sitsofe** [comment]
(Waiting on a reply from @vschiavoni for the above)

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Comment by arthurshau** [comment]
Hi @sitsofe ,

Not the reporter, but I've been thinking about this issue for the last couple of days, mostly pertaining to sync I/O, as that is my use case. For me, the confusion comes from two places.

1. These two lines in the documentation together:

slat:
`For sync I/O this row is not displayed as the slat is really the completion latency (since queue/complete is one operation there).`

clat:
`For sync I/O, clat will usually be equal (or very close) to 0, as the time from submit to complete is basically just CPU time (I/O has already been done, see slat explanation).`

The first line says that for sync I/O, slat is not displayed, because it's really clat. This implies that slat is not a thing for sync I/O, only clat is. Fair enough. But the second line says that clat will be equal or close to 0. Which doesn't make sense to me, because then where is the actual latency being calculated and outputted? When I run a sync I/O job with O_DIRECT, I'm seeing non-zero latency numbers for clat. Where are these numbers coming from/what is actually being measured?

2. Thinking about your question:

`"Clearly" when I/O is being submitted synchronously you can't separate submission latency from completion latency right? (First question: why?)`

I though this was obvious, but thinking about it more, I'm now having doubts about my answer. To understand why submission latency is inseparable form completion latency for sync I/O, I asked myself "when exactly does fio need to call gettimeofday() in order to calculate the latency values?"

For async I/O, it would need to be 1. when the I/O request is created, 2. when the I/O request is submitted to the kernel, and 3. when the I/O request completes. slat is calculated as the difference between 1 and 2, and clat is the difference between 2 and 3.

But for sync I/O, shouldn't it still be the same thing? All that's different is that, after submitting, the application needs to wait for the I/O request to complete. But slat and clat can still be calculated separately here. What am I getting wrong?

**Comment by sitsofe** [comment]
@arthurshau Hi,

Just for clarity when I say "sync I/O" above I mean "I/O done by a synchronous I/O engine".

The timing for asynchronous I/O ioengine has the following points:
A) When fio has finished prepping the I/O
B) When the I/O has **finished** being submitted
C) When fio finds out the I/O completed

The timing for synchronous I/O ioengine has the following points:
A) When fio has finished prepping the I/O
B) Before the I/O has **queued**
C) When fio finds out the I/O completed

So while they are similar, the measurements of A-B aren't _quite_ same thing (and there's an argument that A-B in the synchronous I/O ioengine case is only measuring time spent in fio) whereas B-C is comparable (because B-C does not include prep time). I think the documentation explanation mixes a few things together but it's right that you can't really separate out submission time when the ioengine is synchronous.

Is that a bit clearer?

**Comment by arthurshau** [comment]
@sitsofe Yes, I think I got it now. Thanks!

**Comment by JigaoLuo** [comment]
> a per I/O basis for an async ioengines `slat + clat = lat` ?

Hi,

I'm sorry for reopening this issue, but I believe the latency question is fundamental. For asynchronous IO engines, can we confirm if `slat + clat = lat` on a per-I/O basis?

Thank you.

**Comment by vincentkfu** [comment]
> > a per I/O basis for an async ioengines `slat + clat = lat` ?
> 
> Hi,
> 
> I'm sorry for reopening this issue, but I believe the latency question is fundamental. For asynchronous IO engines, can we confirm if `slat + clat = lat` on a per-I/O basis?
> 
> Thank you.

See Observation 1 at the very bottom of https://github.com/vincentkfu/fio-blog/wiki/How-does-fio-measure-latency.

Also we have tests confirming that mean(slat) + mean(clat) = mean(lat)

https://github.com/axboe/fio/blob/master/t/jobs/t0015-4e7e7898.fio
https://github.com/axboe/fio/blob/master/t/jobs/t0016-d54ae22.fio
https://github.com/axboe/fio/blob/c948ee34afde7eda14adf82512772b03f6fb1d69/t/run-fio-tests.py#L256

**Comment by Amd0905** [comment]
Is clat a feature of the hard disk itself or CPU-related

**Comment by sitsofe** [comment]
@Amd0905 Arguably it's both - it's the time between when fio sent sent the I/O and fio receiving notification that the I/O is complete. See Vincent's explanation in https://github.com/vincentkfu/fio-blog/wiki/How-does-fio-measure-latency .
