### ISSUE TITLE
Understanding "Laying out IO file" in fio

### ISSUE THREAD

**Issue by aksatish19** [axboe/fio#1111]
Hello, I am trying to understand what really happens when in the "Laying out IO file". I have btrfs installed on a raw block device and whenever I run fio with the following configuration, I see the laying out step takes about 40 minutes to complete before the actual fio job starts to perform IO

```
runtime=600
rw=readwrite
rwmixwrite=90
random_distribution=random
percentage_random=100
size=50%
iodepth=16
ioengine=libaio
direct=1
bs=4096
time_based=1
fallocate=none
directory=/tmp/fs_d765f32a-1a34-11eb-8644-61649a50b743
write_lat_log=/tmp/ll
log_avg_msec=500
log_unix_epoch=1
log_max_value=1
filesize=8GB
```

If you see the following lines, the command is started at 15:19:51 and Laying out file finishes at 15:58:31 (about 40 minutes laying out the file). I tried looking through the source code and it seems like laying out occurs whenever the program decides to extend a file. I am assuming laying out then happens only if there are reads in the fio configuration but its a bit unclear to me at this point as to why it should take 40 minutes. Appreciate some insight into what really goes on here.

```
2020-10-29 15:19:51,583 [MainThread] - root - DEBUG - Fio job output: job-0: (g=0): rw=rw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=16
fio-3.16
Starting 1 process
job-0: Laying out IO file (1 file / 4096MiB)

2020-10-29 15:58:31,896 [MainThread] - root - DEBUG - Fio job output:
job-0: (groupid=0, jobs=1): err= 0: pid=70: Thu Oct 29 22:58:31 2020
....
....
```

**Comment by aksatish19** [comment]
Sure. Also, can you help explain what really happens while "Laying out a file" and how different is it when fio actually runs and times the IO? The source code seems to be issuing writes during laying out files.

I am trying to understand why this is needed when there are reads in the fio configuration (because reads can hit an unallocated sector?) and if there is a way to skip Laying out files step?

**Comment by sitsofe** [comment]
When you have a read job you want to know that the file been read isn't sparse (otherwise the filesystem can cheat and return the read back to extremely quickly because it knows there's nothing there and doesn't actually have to send an I/O to the disk). If we're talking Linux (which I guess we must be because your ioengine is libaio) then if the filesystem supports [`fallocate(2)`](https://man7.org/linux/man-pages/man2/fallocate.2.html) then we can just ask it to REALLY allocate the extents that back the file in a fast manner...

> The source code seems to be issuing writes during laying out files

...if it doesn't we end up having to write the file ourselves to force the extents to be allocated but we might not use especially big blocks to do so it can take a while.

> is a way to skip Laying out files step

Yup. If you check the [fio documentation for `fallocate` ](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-fallocate) you will see various options but you may not want to trust your (read) results after using them...

**Comment by sitsofe** [comment]
(also note that using `fallocate=none` is just turning off preallocation and preallocation is what speeds things up if when it works!)

**Comment by axboe** [comment]
We still write to the file, so it should be safe to do reads, and they will hit media, afterwards. It sounds like it's fallocate being very slow with btrfs, so trying fallocate=none might indeed be a good idea.

**Comment by sitsofe** [comment]
@aksatish19 
- What is the output of `df -h /tmp`
- How slow is is layout when you set `fallocate=native`?

**Comment by sitsofe** [comment]
@axboe Looking closer I think I need to correct myself because as you say fio will ensure writes to file... by "Laying out IO file" :-) 

If the file doesn't already exist at a large enough size and we are doing ANY reads we force layout (i.e. write to every region of the file as part of Laying out IO file):
- https://github.com/axboe/fio/blob/fio-3.23/filesetup.c#L1169
- https://github.com/axboe/fio/blob/fio-3.23/filesetup.c#L1213
- https://github.com/axboe/fio/blob/fio-3.23/filesetup.c#L133-L136

Preallocation doesn't change this (https://github.com/axboe/fio/blob/fio-3.23/filesetup.c#L178  ).

@aksatish19 a few clarifications:
- You set filesize=8GB but your output says the file created was 4 gigabytes in size?
- How much of the time is consumed by https://github.com/axboe/fio/blob/fio-3.23/filesetup.c#L212-L242 ?

**Comment by sitsofe** [comment]
@aksatish19 ping?

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Comment by pavlozt** [comment]
Hello .

I observe similar behavior on recent versions of fio 3.33 and regular file systems like ext4.

here is my task file:
```

[global]
ioengine=libaio
direct=1
fallocate=native
[test1]
directory=./data/
write_iops_log
write_bw_log
write_lat_log
log_avg_msec=250
iodepth=16
readwrite=randrw
size=16Gb
time_based=1
ramp_time=30
runtime=120
```

It takes a long time to create a small 16Gb file and message output  "Laying out IO file" if the parameter rw=readwrite and the file has not yet been created.
However, I can run the test once with the rw=write parameter and then the file is created quite quickly.

I'm using a regular debian kernel and a regular ext4 filesystem :
`Linux version 6.1.0-11-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08)`

```
cat /proc/mounts | grep vdb
/dev/vdb /data ext4 rw,noexec,relatime 0 0
```

My disk device is a network virtual one and is limited to a speed of 1000 iops.
On physical and close disks, with 70000 write iops, initialization is also noticeable, but even in these cases it takes a couple of minutes.

It's just a 16GB file. Why so long?

@sitsofe please reopen

**Comment by pavlozt** [comment]
I noticed that the fallocate() is working. 
`du` and `df` report used size is 16Gb file, but the fio doing some other work.

What is the logic behind how the fio works here?

**Comment by kookin** [comment]
I am having the same issue. Laying out takes WAY too long. I am running a Ceph RDB pool backed by 10x NVMe's. I previously ran FIO on these same servers with an older Proxmox installation and the layout happened in a few seconds. These are my params: fio --name=blockchain_test --ioengine=libaio --iodepth=64 --rw=randrw --rwmixread=70 --bs=8k --direct=1 --size=5G --numjobs=8 --runtime=600 --group_reporting

**Comment by sitsofe** [comment]
@kookin since you have opened a new ticket let's continue the conversation over in #1851 .
