### ISSUE TITLE
Clarification about I/O type and block size

### ISSUE THREAD

**Issue by GabrieleMn** [axboe/fio#1137]
Hello, I have some doubts regarding the meaning of I/O type and block size in FIO. I'm using sync as ioengine to test write and read operations.

My doubts are:

1. Does random writing means a sequence of write, lseek, write, lseek when writing to the file?
2. What the block size changes is the **size_t count** of the buffer written by write?

thank you.

**Comment by sitsofe** [comment]
Hi,

> Does random writing means a sequence of write, lseek, write, lseek when writing to the file?

If you really mean the `sync` ioengine then yes (see https://github.com/axboe/fio/blob/fio-3.23/engines/sync.c#L102 for where the `lseek` is done). If you mean the `psync` ioengine (which is the default everywhere but Windows) then no because [pwrite(3)](https://man7.org/linux/man-pages/man3/write.3p.html) takes an offset - https://fio.readthedocs.io/en/latest/fio_man.html#i-o-engine.

> What the block size changes is the size_t count of the buffer written by write?

I would guide you to towards reading the source code for the sync ioengine (e.g. https://github.com/axboe/fio/blob/fio-3.23/engines/sync.c#L208 / https://github.com/axboe/fio/blob/fio-3.23/engines/sync.c#L229 )... Based on what you see there how would you answer your query?

**Comment by GabrieleMn** [comment]
Thank you @sitsofe for your reply.

Yes I meant sync, that was what I was looking for.

With regards to the block size, i'm not sure I'm interpreting correctly the source code you linked. From what I can see each time we write io_u->xfer_buflen bytes, that should correspond to the block size specified when running FIO command. Am I wrong?

**Comment by sitsofe** [comment]
> From what I can see each time we write io_u->xfer_buflen bytes, that should correspond to the block size specified when running FIO command. Am I wrong?

No you're not wrong or put another a more positive way - you're correct, it should correspond to block size! You can also check via a tool like `strace` if you limited the amount of io you're doing (e.g. https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-number-ios) and if you set fio to use threads to avoid the forking of processes (https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-thread)!
