### ISSUE TITLE
--filename=Nopath

### ISSUE THREAD

**Issue by projectHolsey** [axboe/fio#1171]
I'm aware this is a not the most intelligent thing to do, however using this argument for FIO seems to crash the program and cause it to 'stop working'. I'm not in need of a fix, just wanted to bring it to your attention incase it was previously unknown.

On windows (server 2016) this displays an error dialog, centre screen :

![Capture_fio_stopped_working](https://user-images.githubusercontent.com/34950923/105019729-52e2ce80-5a3e-11eb-8f4d-361b5045004e.JPG)

**Comment by sitsofe** [comment]
@projectHolsey Hello there!

Your issue is missing information requsted in https://github.com/axboe/fio/blob/master/.github/SUPPORT.md#reporting-bugs / https://github.com/axboe/fio/blob/master/REPORTING-BUGS#L12 . Can you edit ALL this information into your previous comment as without it we will have to close this issue. Thank you!

**Comment by projectHolsey** [comment]
FIO version 3.25
Arguments used:

fio --name=job1 --size=300% --rw=randwrite --runtime=10 --filename=Nopath


The issue was reported as a filename issue 
However, I can see the size is 300% as opposed to max size of 100%

**Comment by sitsofe** [comment]
(FYI: percentages on size should only be used when the file already exists but it looks like the logic enforcing this sometimes fails)
