### ISSUE TITLE
FIO reports a wrong READ bw result on usb flash drive

### ISSUE THREAD

**Issue by sgon00** [axboe/fio#1212]
OS: MacOS Big Sur (11.2.3)
FIO Version: `fio-3.26`

I am trying to test READ/WRITE bw value on a USB Flash Drive. The write result looks OK. But when I test READ bw, the result is 5187MB/s. That is not correct. That cheap USB drive should have 150MB/s at most. I am not sure if this is a bug or not. Did I do anyting wrong? The command I used:

```
$ fio -direct=1 -iodepth=64 -rw=read -ioengine=posixaio -bs=1024k -size=1G -numjobs=1 -runtime=1000 -group_reporting -filename=iotest -name=NAME

fio-3.26
Starting 1 process

Read_PPS_BW_Testing: (groupid=0, jobs=1): err= 0: pid=4925
  read: IOPS=4946, BW=4947MiB/s (5187MB/s)(1024MiB/207msec)
    slat (nsec): min=0, max=40000, avg=1347.66, stdev=1551.41
    clat (usec): min=1001, max=206081, avg=3211.30, stdev=9545.73
     lat (usec): min=1003, max=206084, avg=3212.65, stdev=9545.87
    clat percentiles (usec):
     |  1.00th=[  1237],  5.00th=[  1352], 10.00th=[  1467], 20.00th=[  1631],
     | 30.00th=[  1680], 40.00th=[  1745], 50.00th=[  1762], 60.00th=[  1811],
     | 70.00th=[  1860], 80.00th=[  1893], 90.00th=[  2114], 95.00th=[  4621],
     | 99.00th=[ 55313], 99.50th=[ 56361], 99.90th=[ 77071], 99.95th=[206570],
     | 99.99th=[206570]
  lat (msec)   : 2=87.70%, 4=6.15%, 10=3.12%, 20=0.59%, 50=1.27%
  lat (msec)   : 100=1.07%, 250=0.10%
  cpu          : usr=4.37%, sys=2.91%, ctx=1029, majf=0, minf=28
  IO depths    : 1=0.1%, 2=0.2%, 4=0.4%, 8=41.8%, 16=57.5%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=99.5%, 8=0.5%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=1024,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
   READ: bw=4947MiB/s (5187MB/s), 4947MiB/s-4947MiB/s (5187MB/s-5187MB/s), io=1024MiB (1074MB), run=207-207msec
```

**Comment by sitsofe** [comment]
@sgon00 What happens if you run
```
sudo purge
```

and then do you fio command?

**Comment by sitsofe** [comment]
(setting to needreporterinfo pending a reply from @sgon00 )

**Comment by sgon00** [comment]
@sitsofe 
Sorry about the late update. Today I tried to reproduce the problem before trying the `purge` command, but magically, the problem is gone and NOT reproducible. It shows `141MB/s` bw now. I have no ideas what happened at the day I opened this issue. I am sure that I did everything correct and use the same command, the same device, the same OS, everything the same at that day. 
You can close this issue since I can not reproduce it now. 
Thanks a lot for your reply.

**Comment by sitsofe** [comment]
@sgon00 At a guess it might have been that the data was somehow already in the macOS' Unified Buffer Cache. Once data is cached on macOS it's difficult to forcefully evict (short of reading a lot of other data thus far I've only found `purge` does it) and otherwise it keeps being used for reads despite the `direct=1`. If the data is NOT already in the cache then `direct=1` avoids it being added and behaves as expected.

See https://github.com/axboe/fio/issues/48#issuecomment-328012610 , https://stackoverflow.com/questions/459537/clear-buffer-cache-on-mac-os-x (where someone curiously mentions fio :-) and the [ditto tool man page](https://ss64.com/osx/ditto.html) which mentions this on its `--nocache` option:

> Files read and written will not be cached, although if the file is already present in the cache, the cached information will be used.

Other OSes like [Linux don't have this problem because they have defined operations that can drop the cache](https://github.com/axboe/fio/blob/fio-3.26/os/os-linux.h#L152) although you have to typically be root for this to work.
