### ISSUE TITLE
mixed trim and write with percentage?

### ISSUE THREAD

**Issue by gang2015** [axboe/fio#122]
I want to test ssd by randomized mixed trim and write with given percentage. It seems there is no workaround in fio for that test purpose. 

rw = trimwrite
But it can't set the percentage for trim.

trim_percentage = 20
It seems doesn't change anything

my full config:

mixed_trim_write.fio
----------------------------------
[global]
filename=/dev/sdb
ioengine=libaio
iodepth=32
direct=1
time_based
runtime=10h
disable_lat=1
disable_slat=1
[mixed_trim_write]
rw = trimwrite
trim_percentage = 20

**Comment by axboe** [comment]
trim_percentage has to do with write verify, where trim_percentage defines the percentage of writes that get trimmed instead of verified. It does not related to trimwrite. For trimwrite, fio just trims before writing to that location. This means the trims and writes are inherently tied to each other.

If you want a pure mix, consider using two jobs instead. One could randomly write, one randomly trim. Or whatever you want. You can tie them together with flows, if you want/need to do that.

**Comment by gang2015** [comment]
Thanks Axboe for clarification.

I want the pure mix of trim and write/read. I created two jobs in parallel. In case of 10% percent trim and rest for read/write, the following configuration with flow seems work well.

[global]
filename=/dev/sdb
ioengine=libaio
iodepth=32
direct=1
time_based
runtime=10h
disable_lat=1
disable_slat=1
[rand_write]
rw=randrw
#  90% write/read
flow=-1
[rand_trim]
rw=randtrim
# 10% trim
flow=9
bs=1M
