### ISSUE TITLE
Fio has problem with filling 95% of 1TB disk 

### ISSUE THREAD

**Issue by KamilStachera** [axboe/fio#1397]
**Description of the bug:**
When trying to fill empty 1TB disk with FIO, after about one hour it spits out that device has no more space (fio: pid=4228, err=28/file:io_u.c:1846, func=io_u error, error=No space left on device), but this device still has 145GB free space when error occurs. This disk has 954GB writable space, and we are trying to write 905GB on it. 

Here output from CMD:
![image](https://user-images.githubusercontent.com/46875341/167427145-7cf691d6-5ca4-48da-9046-af61e932b013.png)

**Environment**: 
Windows 11 version 21H2 (OS BUILD 22000.613)

**fio version**: 
2.30

**Reproduction steps**
CMD parameters used to run FIO : fio-2.30-x64\fio.exe --name=fullFill --direct=1 --rw=write --ioengine=windowsaio --filesize=32M-240M --nrfiles=12000 --bs=8M-64M --size=905G --directory=F\:\FillDirectory

1. On 1TB empty disk run above command
2. Wait for result

**Comment by axboe** [comment]
This isn't a fio issue. If fio gets "Out of space" to a write command, that's coming from the file system. There's nothing fio can do at this point but to stop writing, since any further write would likely yield ENOSPC as well. I don't know much about Windows file systems, but it's likely the fs using a lot of data for metadata or being overly cautious on the write.

**Comment by KamilStachera** [comment]
@axboe Thats interesting because on the almost same disk model (differs only in size, 512GB instead od 1TB) it works like a charm

**Comment by axboe** [comment]
Yeah I have no idea, but one thing is for certain, fio isn't making up the ENOSPC error, it's simply reporting what it's getting...
