### ISSUE TITLE
fio rbd engine timestamp not reliable

### ISSUE THREAD

**Issue by jjhuo** [axboe/fio#148]
Have ran fio rbd with ceph SSD/HDD RBD pool for a lot times, and noticed that the timestamps in the log file (write_iops_log=LOG_FILE) are not accurate from time to time. The worst case was with HDD RBD, below is the beginning of that iops log file output:

1103, 1049, 1, 4096
2771, 38, 1, 4096
3492, 88, 1, 4096
3994, 235, 1, 4096
4502, 2080, 1, 4096
5034, 1231, 1, 4096
6034, 180, 1, 4096
6758, 80, 1, 4096
8079, 43, 1, 4096
9433, 47, 1, 4096
10743, 48, 1, 4096
11260, 566, 1, 4096
11787, 2144, 1, 4096
12787, 813, 1, 4096
13771, 65, 1, 4096
15003, 99, 1, 4096
15508, 126, 1, 4096
16866, 42, 1, 4096
17411, 106, 1, 4096
20779, 35, 1, 4096
23664, 21, 1, 4096
24189, 1916, 1, 4096
24729, 1946, 1, 4096
25791, 235, 1, 4096
27392, 39, 1, 4096
28734, 47, 1, 4096
29438, 78, 1, 4096
29999, 105, 1, 4096

In the above log file, the time interval between two lines vary from 0.5, 1 to 2.5 seconds. Because of this, the iops reported in the log file are not accurately either.

When running fio against raw device, it gives relatively very stable time interval, 0.5 second by default, and very tiny drifting over time.

**Comment by bengland2** [comment]
which clocksource are you using?  default is gettimeofday, which is very expensive compared to clock_gettime.   I ran into a problem with inaccurate IOPS reporting when fio was running inside KVM virtual machines - it was worst when I had the most KVM guests doing random reads (high IOPS).  Switching to clocksource=clock_gettime seems to resolve the problem.

**Comment by jjhuo** [comment]
I used default, will try clock_gettime. Thanks!

**Comment by sitsofe** [comment]
@bengland2 Are you sure fio is defaulting to `gettimeofday()` on KVM? The [HOWTO](https://github.com/axboe/fio/blob/fio-2.15/HOWTO#L1745) doesn't mention the full order explicitly but fio prefers clocks in this order (from most preferred to least preferred): CPU, `clock_gettime()`, `gettimeofday()`. You can see that `clock_gettime()` should be preferred to `gettimeofday()` in [`os/os.h`](https://github.com/axboe/fio/blob/fio-2.15/os/os.h#L165). If deemed reliable the CPU is used in preference to other clocks due to the overriding code in [`fio_clock_init()`](https://github.com/axboe/fio/blob/fio-2.15/gettime.c#L376) ( which in turn requires the platform to say the TSC is reliable which is done on x86 in [`arch_init_intel`](https://github.com/axboe/fio/blob/fio-2.15/arch/arch-x86-common.h#L37) )

The [fio HOWTO says CPU clock as the default clocksource is only the case on x86_64 if TSC invariant is supported](https://github.com/axboe/fio/blob/fio-2.15/HOWTO#L1745). Digging further and looking at QEmu's release notes, [if your KVM VM supports migration/savevm it won't/can't expose TSC invariant](http://wiki.qemu.org/ChangeLog/2.1#KVM) (see the `invtsc` feature). So if you haven't enabled `invtsc` shouldn't fio's use `clock_gettime()` on KVM?

**Comment by axboe** [comment]
What does:

$ fio --cpuclock-test

say?

**Comment by bengland2** [comment]
on my VM, it says [this](http://pastebin.com/XnYSH7XR)

**Comment by bengland2** [comment]
whereas on baremetal it says reliable_tsc: yes [here](http://pastebin.com/ybqX0hdC)

**Comment by axboe** [comment]
OK, then the CPU clock source is working as expected at least, disabled on vm and working on the bare metal.

As to gettimeofday vs clock_gettime, there should not be a huge difference between them. On Linux, we should be accessing both through the vdso. Why is one more expensive than the other on your test?

**Comment by sitsofe** [comment]
@bengland2 out of curiousity, what do you get if apply the patch from https://gist.github.com/sitsofe/75b14c33f137aada18a95a32d60c6d7f and run `fio --debug=time [usual paramaters...] | grep clocksource` ?

**Comment by axboe** [comment]
If we don't have invariant TSC, it should fall back to clock_gettime().

**Comment by sitsofe** [comment]
@axboe in that case I'm unsure how explicitly setting `clocksource=clock_gettime` as mention in https://github.com/axboe/fio/issues/148#issuecomment-261143839 could make a difference...

Additionally could it be that in @jjhuo's case I/Os are backing up when submitted by rbd in a manner that doesn't happen with a raw device (i.e. could using `io_submit_mode=offload` make a difference)?

**Comment by axboe** [comment]
I agree - one thing is theory, the other is practice ;-). So would be good to double check in any case.

For the logging, the granularity is controlled by the IO completion times. So if it's a slow or erratic media, then they will be jumpy. One way to avoid that would be to use log_avg_msec, since that pulls the logging out of the IO completion path. That should help.

**Comment by sitsofe** [comment]
@jjhuo did things get better with `--clocksource=clock_gettime` and if so can this issue be closed?

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
