### ISSUE TITLE
fio : Bad opttion  <trigger-file=/tmp/touchme.txt> 

### ISSUE THREAD

**Issue by deepaktawri** [axboe/fio#155]
trigger-file option does not work when given in job file, however it works at command line :

# cat junk.job
;Write pattern B
[junk]
direct=1 
ioengine=sync 
rw=randwrite
time_based
runtime=10
filename=/dev/disk1
trigger-file=/tmp/touchme.txt
trigger="echo hello world"

# fio ./junk.job
Bad option <trigger-file=/tmp/touchme.txt>
Bad option <trigger="echo hello world">
fio: job junk dropped

Where as equivalent command line (generated using fio --showcmd) works fine :

fio --name=junk --direct=1 --ioengine=sync --rw=randwrite --time_based --runtime=10 --filename=/dev/disk1 --trigger-file=/tmp/touchme.txt --trigger="echo hello world"

**Comment by axboe** [comment]
That's by design, job options can always be command line options, but not vice versa. The exception are options that apply globally, like the trigger.

**Comment by deepaktawri** [comment]
Thanks for your quick reply.

Not sure why is this by design!, in other words Why --trigger-file option not allowed in job file ?

Btw, following works for me : 

fio junk.job --trigger-file=/tmp/touchme.txt --trigger="echo hello world"

**Comment by axboe** [comment]
Because, as mentioned in the original reply, it's a global option. The job options are all per-job, unless they are in a global section of course. But if trigger-file worked as a job option, then it would not matter if it was in a global or job section, either of them would apply globally. This is confusing, and can even cause problems if multiple jobs in a file use the same option in conflicting ways.

**Comment by axboe** [comment]
And yes, using a combo like you did is the way to do it, you don't have to go full bore command line just because of this.

**Comment by deepaktawri** [comment]
Thank you for the detail reply.
