### ISSUE TITLE
fio param size > disk size with random write not full disk write

### ISSUE THREAD

**Issue by llicety** [axboe/fio#1563]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
if we use fio param size > disk size with random write, fio will not full write the disk.

**Environment**: 

**fio version**: 
fio-3.19

**Reproduction steps**

fio conf
[global]
ioengine=libaio
direct=1
buffered=0
thread
group_reporting
numjobs=1
ramp_time=0
[bio]
filename=/dev/vdb
iodepth=128
bsrange=512-1048576
rw=randwrite
offset=0G
size=3G
verify_pattern=0x0101
verify=pattern

1. have a disk /dev/vdb as 2GiB size
2. run fio with size param 3G

the fio output
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/21215997/234750310-6eeca8bc-6e54-4856-8f0d-bfd2dde5a421.png">

I use the fio config above and set rw=read to check the write. fio verify error. 
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/21215997/234751127-edc0bfee-5a48-45f1-9101-03f004e49389.png">

use hexdump out put the data in mismatch position like offset 148992 not the pattern 0x0101
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/21215997/234751426-973c7501-4547-4a58-905f-eed8f29f5870.png">

fio will not write full disk. it because function io_u_fits use f->io_size check offset + buflen, but fill_io_u use file->real_file_size to check.
Did I misuse fio or is it better to use file->real_file_size in io_u_fits?

**Comment by ankit-sam** [comment]
Hi @llicety, yes the offset + buflen > real_file_size check from fio causes it to not write the actual size. This is snippet where it happens when I enabled debug=io 
```
io       1032  complete: io_u 0x55b759d061c0: off=0x6a86000,len=0xf000,ddir=1,file=/dev/nvme0n1
io       1032  io_u 0x55b759d061c0, off=0x7fffd000 + len=0xe6000 exceeds file size=0x80000000
io       1032  io_u 0x55b759d061c0, setting file failed
io       1032  get_io_u failed
io       1032  io_u_queued_complete: min=127
io       1032  getevents: 127
```
this can actually happen because of multiple reasons:
1. Specifying bsrange instead of a single blocksize.
2. Specifying a mix of sequential and random workload (option percentage_random)
3. Having holes while doing an I/O, can see if you specify (rw=write:4k)

and similar issues have been reported in past   https://github.com/axboe/fio/issues/1486
The only solution is to use  `io_size` instead of `size` as there was no easy way to fix this, so we updated the document in past https://github.com/axboe/fio/commit/942d66c85ee8f007ea5f1097d097cf9a44b662a0

And, I guess for your second issue with read pattern verify, fio is reading from a location which was actually never written.
