### ISSUE TITLE
'randseed=1' does not ensure same data across multiple runs

### ISSUE THREAD

**Issue by nilotpal1984** [axboe/fio#158]
FIO version : 2.2.6

Ran the following command : sudo /usr/local/bin/fio --name=nn-0-run-3 --ioengine=libaio --bsrange=1m-1m --rw=randwrite --nrfiles=1 --iodepth=50 --directory=/home/NN/fio_test  --direct=1  --size=5g --thread=1 --loops=1 --group_reporting --fallocate=none  --randseed=1
and then ran the same command just by changing the file name .

The data inside the files are not same. Please let me know if I am missing anything.

**Comment by axboe** [comment]
The data isn't going to be the same. Fio will offset scramble writes by default, and that includes factors that aren't predictable or runtime repeatable. If you did refill_buffers=1, then I think the contents would end up being the same, since we'd use a seeded generator for the IO buffers then. randseed=x governs only the random generators, so your IO patterns would be the same, block size mix, etc.
