### ISSUE TITLE
fio: Input/output error

### ISSUE THREAD

**Issue by yfming** [axboe/fio#1592]
fio -direct=1 -iodepth=32 -rw=randwrite -ioengine=libaio -bs=4k -size=100% -numjobs=1 -time_based=1 -runtime=300 -output-format=json -norandommap=1 -ramp_time=0 -random_generator=tausworthe64 -randrepeat=0 -thread=1 -group_reporting -rwmixread=30 -filename=/dev/nvme5n1 -name=test 
fio: io_u error on file /dev/nvme5n1: Input/output error: write offset=2359502831616, buflen=4096
 
then fix bs=16k, test ok.

**Comment by ankit-sam** [comment]
Hi @yfming its really hard to figure out the exact issue by the limited information you provided. Perhaps you can try few things such as:
1. sequential workoad (`-rw=write`) instead of random.
2. Check if the issue always happens at the same offset, try to run without without specifying (`-time_based`), also change the (`-size`) parameter.
3. The most important part enable debug log (`-debug=io`). You can check other debug options, see the supported ones via `fio --help`
4. `dmesg` would be helpful in this case.

**Comment by Nitheesh1609** [comment]
Hi @yfming , You could also check for the Format of the SSD or the LBA format. If the format is in 4k or 512. This might be an lba size formating issue.
