### ISSUE TITLE
What is the purpose of  iodepth_batch_complete_min = 0 ?

### ISSUE THREAD

**Issue by arashoot** [axboe/fio#167]
I am using FIO to measure the performance of very high speed SSDs.
So, I reviewed the options to reduce the measured latency while keeping high iodepth (2048~) and found **iodepth_batch_complete_min**.

The HOWTO says: 
If this variable is set to 0, then fio will **always check for completed events before queuing more IO.** This helps reduce IO latency, at the cost of more retrieval system calls.

Based on this explanation, I thought that if iodepth_batch_complete_min is set to 0,  the checking completed events is done by non-blocking manner and thus FIO can proceed more queueing.

However, I tried with the below script and the result was that 100% of io depth was 1.
[read]
rw=read
bs=4k
filename=/dev/sda
ioengine=libaio
direct=1
iodepth=4096
iodepth_batch_complete_min=0

**Do I misunderstand the purpose of the option?**
**Is there any other option proper to my purpose? ( FIO checks the completions and if not found, immediately returns and continues queueing more IOs )**

To clarify, I reviewed source code (fio-2.8) and found the code related to the iodepth_batch_complete_min options.

In wait_for_completes ( backend.c),  even in polling mode,  minimum events is changed to 1

```
 if ((full && !min_evts) || !td->o.iodepth_batch_complete_min)
        min_evts = 1;
```

Finally, fio_libaio_getevents applies actual_min (iodepth_complete_min). Howerver, the check condition does NOT allows this function to exit when r == 0 because min is not zero.

```
           r = io_getevents(ld->aio_ctx, actual_min,
                max, ld->aio_events + events, lt);
       }
       if (r > 0)
            events += r;
        else if ((min && r == 0) || r == -EAGAIN) {
            fio_libaio_commit(td);
            usleep(100);
        }

```

So, FIO always waits for the completion before issuing more IOs. Is my code reading correct?
What is the right usage of iodepth_complete_min option ?

**Comment by sitsofe** [comment]
This is less of an "issue" and more of a "large number of how do I/what does X do" questions so it might be more suitable to have sent these to the mailing list.

How `iodepth_complete_min=0` works depends on the internals of the ioengine being used (and seems to only make sense on asynchronous ioengines that define `commit()`). By default fio queues I/Os one at a time. In the libaio ioengine case, if no completion events are found it will try and commit I/Os that had to be **previously parked** (e.g. because too much I/O already in flight at the original queuing time) and then sleep briefly. Continuing on with the one I/O queued at a time case with `iodepth_complete_min=0`: once `fio_libaio_getevents()` is entered and no completion events occur, it won't find anything to queue (because nothing had to be parked) when `fio_libaio_commit()` is called. Thus you will end up waiting for the completion of the single I/O before submitting exactly one **new** I/O batch.

I'm guessing things are arranged this way to prevent completion being starved by submission - for a  given batch of I/Os you will wait for at least one completion before submitting a branch new batch. In the `iodepth_complete_min=0` case this probably means you should be using `iodepth_batch_submit` to set a "batch" bigger than one.

So to summarise answers to your questions:
1. The purpose of `iodepth_batch_complete_min=0` is to allow the queuing of I/O that had **previously been attempted for queuing but had to be parked**.
2. It does look like you misunderstood the purpose of `iodepth_batch_complete_min=0` - It's not there to allow completely brand new I/O to be queued when no completions are found - only to allow the more rapid queuing of previously "parked" I/Os **from the current batch**.
3. Is there a better option to achieve your goal is a broad question that would be better asked on the mailing list ("How do I...?"). By default submission and reaping happen inline so if one goes slow the other goes slow too. Perhaps you want a different option from the `iodepth_batch_*` options (e.g. `iodepth_batch_submit=4 iodepth_batch_complete_max=4`) as you can amortize various costs. Another idea could be to use `io_submit_mode=offload` to decouple things but there's no such thing as a free lunch.
4. fio waits for at least one completion before submitting a new batch of I/O. If your batch size is one...
5. Your code reading seemed roughly correct but was incomplete.
6. Correct usage of `iodepth_complete_min` depends on the ioengine, how you want to batch your I/O and where you want the batching to take place.

**Comment by sitsofe** [comment]
Further code inspection shows some mistakes in my previous explanations:
* Changing `iodepth_batch_submit` to be greater than 1 *won't* make the amount queued greater (it will only have an influence when there is more than one I/O queued but not yet committed).
* Because `iodepth_complete_min` is 0, by default `iodepth_batch_complete_max` will also be 0 (see the HOWTO). Because both are 0 this will cause `io_in_polling()` to return true:

backend.c:
```C
 566 static inline bool io_in_polling(struct thread_data *td)
 567 {
 568         return !td->o.iodepth_batch_complete_min &&
 569                    !td->o.iodepth_batch_complete_max;
 570 }
```

When `io_in_polling` returns true every time an I/O is **queued** (notice how it won't even have even been committed yet) fio will trigger a wait for completion:
backend.c:
```C
 724                 ret = td_io_queue(td, io_u);
 725 
 726                 if (io_queue_event(td, io_u, &ret, ddir, NULL, 1, NULL))
 727                         break;
 728 
 729                 /*
 730                  * if we can queue more, do so. but check if there are
 731                  * completed io_u's first. Note that we can get BUSY even
 732                  * without IO queued, if the system is resource starved.
 733                  */
 734 reap:
 735                 full = queue_full(td) || (ret == FIO_Q_BUSY && td->cur_dept     h);
 736                 if (full || io_in_polling(td))
 737                         ret = wait_for_completions(td, NULL);
```

Committing will take place when the libaio ioengine finds no events in `fio_libaio_getevents()`:
engines/libaio.c:
```C
145 static int fio_libaio_getevents(struct thread_data *td, unsigned int min,
146                                 unsigned int max, const struct timespec *t)
147 {
148         struct libaio_data *ld = td->io_ops_data;
149         struct libaio_options *o = td->eo;
150         unsigned actual_min = td->o.iodepth_batch_complete_min == 0 ? 0 : min;
[...]
159         do {
160                 if (o->userspace_reap == 1
161                     && actual_min == 0
162                     && ((struct aio_ring *)(ld->aio_ctx))->magic
163                                 == AIO_RING_MAGIC) {
164                         r = user_io_getevents(ld->aio_ctx, max,
165                                 ld->aio_events + events);
166                 } else {
167                         r = io_getevents(ld->aio_ctx, actual_min,
168                                 max, ld->aio_events + events, lt);
169                 }
170                 if (r > 0)
171                         events += r;
172                 else if ((min && r == 0) || r == -EAGAIN) {
173                         fio_libaio_commit(td);
174                         usleep(100);
175                 } else if (r != -EINTR)
176                         break;
177         } while (events < min);
```
Given this, when the `iodepth_batch_complete_max` option is 0, setting the `iodepth_batch_complete_max` option to 1 or above should allow I/O queues deeper than 1 to occur (assuming `iodepth` is greater than 1).

I guess this means the intent of `iodepth_complete_min=0` is to reduce the overhead of measuring completion latency by putting the committing of the I/O and the noticing of its completion as close together as possible (this may mean you don't send I/O as efficiently though).

**Comment by sitsofe** [comment]
@arashoot If the above has answered your question could you close this issue?

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Comment by calebsander** [comment]
I also stumbled across this surprising behavior recently. As the reporter says, there's nothing in the documentation that suggests that `--iodepth_batch_complete_min=0` waits for each I/O to complete immediately after submitting it. I really don't think this makes sense as the default behavior for `--iodepth_batch_complete_min=0` regardless of `--iodepth`; if the user really wants to submit a single I/O at a time and busy-poll for completions, it would be expected to use `--iodepth 1` (which is the default). If this is the intended behavior (or maybe it's too late to change it), I would suggest at least adding an example to the documentation section under `iodepth_batch_complete_min` and `iodepth_batch_complete_max` for this case.

Setting `--iodepth_batch_complete_max` to `iodepth` as suggested by @sitsofe does allow achieving the full `iodepth`. However, the ioengine's `->getevents()` is still called with `min=1` due to this code in `wait_for_completions()` that treats `iodepth_batch_complete_min=0` as 1 instead:
```c
min_evts = min(td->o.iodepth_batch_complete_min, td->cur_depth);
if ((full && !min_evts) || !td->o.iodepth_batch_complete_min)
	min_evts = 1;
```
That will result in putting the thread to sleep until completions are available. That seems to contradict the documentation, which says "if none of I/O has been completed yet, we will NOT wait and immediately exit the system call."
