### ISSUE TITLE
JSON Output Should Be Single-line

### ISSUE THREAD

**Issue by civik** [axboe/fio#174]
Multi-line JSON can often be a pain to parse and a lot of applications that one may use for aggregation of metrics don't understand multi-line JSON.  

Output should be in single-line JSON.  Just leave it to the user to pass the output through jq or something similar.

**Comment by axboe** [comment]
You're going to have to be more specific. What lines are being broken up?

**Comment by civik** [comment]
the JSON output is 'prettyprinted' for human readability, but that complicates machine readability.  Ideally its output as a single line.

`{"json":{"format":"singleline"}}`

vs

```
{
	"json": {
		"format": "multiline"
	}
}
```

**Comment by axboe** [comment]
I fail to see how that complicates parsing it. One of the nice advantages of the json output is that it IS humanly readable as well. If that was one huge line, then that would be severely compromised. I'm not going to change that. If your parser struggles because of the newlines, stripping them is equally trivial.

**Comment by civik** [comment]
JSON is for parsability.  If you wanted readability, you'd just pick the regular output.  JSON is for capturing serialized data and by convention should be output as compactly as possible - IE no linefeeds or whitespace.  Consider the example where I want to pass the JSON output as an argument to a script or application to parse into a hash. I cant pass it through a pipe with the 'prettyprint' because an argument parser can't handle that. Another example: I'm using --status-interval to drop the JSON outputs to a file.  I end up with a file that is not valid JSON with arbitrary line counts for each run depending on the options I select. I pass the output through JQ then I can get output where each JSON object is on its own line, that can be easily iterated through. Although I CAN work around the formatting, I shouldn't HAVE to for output that is intended for ease of parsability.

**Comment by axboe** [comment]
> JSON is for parsability. If you wanted readability, you'd just pick the regular output

As I said, the nice part is that it can be both. A parser that breaks because of new lines is very poorly written, imho. JSON output with new lines is valid JSON.

There's an easy fix for this - just add a json output variant that doesn't output newlines, json-terse or something like that.

If there's an issue with spurious new lines in the output, then surely that should be fixed. If fio isn't outputting valid json, then of course that should be fixed up.
