### ISSUE TITLE
random write performance with zipf

### ISSUE THREAD

**Issue by zhouyuan** [axboe/fio#196]
Hi, I'm trying to understand the random write performance on my DC3700 SSD here:

- w/o zipf: iops=24773, lat=39.44 us

- w/ zipf(1.2): iops=22522 lat=43.34 us

I repeated the tests several times and the gap seems stable.

below is my fio script:

> fio --filename=/dev/sdb --direct=1 --rw=randwrite --bs=4k --numjobs=1 --iodepth=64 --runtime=60 --time_based --group_reporting --name=ssd-test --random_distribution=zipf:1.2

my question is: why is the performance w/ zipf a bit lower? Is it due to some extra overhead from fio?

thanks, -yuan

**Comment by axboe** [comment]
You can gauge overhead of various options by using the 'null' IO engine, --ioengine=null. zipf does have a bit of overhead, but it should not be much. I suspect your lower numbers on the SSD are due to the fact that with zipf, you'll have more overwrites of the same blocks instead of uniformly random writes.

**Comment by zhouyuan** [comment]
@axboe Thanks for the help!
