### ISSUE TITLE
"Filename too long" :  FIO on windows

### ISSUE THREAD

**Issue by sellerb5** [axboe/fio#228]
Trying to run fio on windows and running in to following issue. Any suggestions?

fio --create_on_open=1 --runtime=60 --size=84120139622 --thread=4 --direct=1 --ioengine=windowsaio --bssplit=4k/5:8k/5:30k/80:60k/5:64k/5 --iodepth=4 --nrfi
les=100 --rw=randrw --directory=D\:/ --name=randio_mul_file --time_based --filename_format=testfiles.$jobnum.$filenum

fio-2.6
Starting 4 threads
fio: pid=3272, err=38/file:ioengines.c:316, func=td_io_queue, error=Filename too long
fio: pid=8300, err=38/file:ioengines.c:316, func=td_io_queue, error=Filename too long

**Comment by axboe** [comment]
Hmm weird. Does this also happen if you don't give filename_format?

**Comment by priyankopaul** [comment]
This error is not related to "filename_format"
Actually the parameter --directory=D:/ has to be changed to --directory=D\:/
If the wanted filename does need to include a colon, then escape that with a '\' character.

Also in windows it has been observed that if "--rw=randrw" is used "--create_on_open" has to be set to '0', else same error is observed. I also tried "--create_on_open=1" but in that case "--rw=randwrite" should be used.
I believe this is because "--rw=randrw " is expecting files to be present which is satisfied by "--create_on_open=0"
So if we have to use  "--rw=randrw " in windows "--create_on_open=0" is required. else "--create_on_open=1" can be used but IO type has to be --rw=randwrite"

**Comment by sellerb5** [comment]
Yup, the incorrect drive letter was the issue in my case. Thanks.

**Comment by axboe** [comment]
Thanks Paul!

**Comment by luisa123456** [comment]
Long Path tool can resolve error messages like: path too long, cannot delete file, too long path, destination path is too long, etc.
