### ISSUE TITLE
Feature Request: Be able to select a read source for write

### ISSUE THREAD

**Issue by jlpetz** [axboe/fio#284]
fio is a great tool. Perhaps I'm missing something, but fio seems well place for use to replace dd for doing device copies?

I wanted to test copy performance between two devices on a system and naturaly thought fio might be a good choice after having used it to write random data to the source ready for the copy. It seems though that you can't provide fio with a source device/file to be read from as the source of data for a sequential write. Again pardon my ignorance if this is actually possible.

**Comment by szaydel** [comment]
@jlpetz - I think what you saying is you want to specify source and destination separately, as opposed to now only having a single definition which is both source and destination, is that correct?

In general, if you are trying to use `fio` to replace `dd`, I am not sure I can rationalize why. If you want to specify tests where you explicitly define source and destination, you could have a profile where there are two [job] specifications one which does a read, in some form, and one which does a write, be that sequential, random, or whatever mix of the two. Of course, you can still control minutiae of variables, like offsets, record sizes, etc., etc.

**Comment by jlpetz** [comment]
Correct in the being able to specify source & destination for a single job.

Two reasons.

1. It just seems logical. Fio has great parrellel read & write abilities well beyond dd for perf testing. Thats why everyone uses it above dd.  But if i need to move real data, fio cant. While you can just script a multithreaded dd, it still lacks functionality and ease of use. Being able to specify source and destination would enable you do move real data fast without dd trickery.

2. What if your wanting to test bandwidth over a sata bus, controller, morherboard  bridge/chipset between multiple devices. You want to try and simulate real world transfers as much as possible. Doing independent jobs doesnt seem like the ideal way to test for this? Perhaps this is just my uninformed opinion. But I would much prefer being able to pull data off the source pushing it to a destination and the checksum after(validate copy if needed).

The particular use case I was thinking about here was for a customer. They are using EC2 and have a scaling setup where essentially they need to duplicate a 800TB volume as fast as possible to scale their app. Not ideal architeture, but regardless I was essentially benchmarking how to make this duplication process faster.

 Ie.
-Pause writes to the source vol
-duplicate vol with block level copies to destination blank volume
- restart app on source(resume writes)
- detach and move duplicate volume to a new system to scale up

**Comment by jlpetz** [comment]
FYI, to benchmark I ended up trying both multi process dd and btrfs send/receive.

I settled on timing the btrfs send/receive. Iostat was showing similar perf than multi dd. Though there was some intense cpu spike. Bit it was nicer in that the process was an exact block for block copy which mean't no duplicate volume lables or guid.

**Comment by jlpetz** [comment]
"Was an exact block copy" <-- should be "wasn't" for btrfs send/receive

Dd was an exact block copy thoug. Which wasnt an issue if you detached the duplicate vols quickly. If you didnt though btrfs gets in a pickle with duplicate vol guids for a raid0 stripe

**Comment by szaydel** [comment]
If you are trying to replicate anything semi-real-world with `dd`, you are really not close to begin with, but I am assuming you already know this. And, to be fair, real world is a fairly vague and broadly defined, because there are a lot of ways in which IO happens, and in some cases you have things like read ahead at the disks and in the filesystems, and in some cases only in the filesystems, and in some cases only in the disks, etc. You have a nearly infinite set of permutations that you could all be considered real-world. `dd` could be thought of as a very naive real-world model for doing sequential file copying, whereas what you are describing is perhaps much more involved. Doing a sequential read in one job and a sequential write in another is a good representation of what `dd` would do. You are basically reading a chunk and writing a chunk, obviously with `dd` you are working with same chunks, which won't be the case here. But perhaps there is a way to implement this with `fio` and I am just not thinking of a method.

Having said that, what you are trying to do to me sounds like should be done at a filesystem level, if possible, ideally with filesystem that supports snapshots, and snapshot replication, ZFS comes to mind. If you have 800TB of data, no matter how fast the underlying media are, that's a lot of data, it seems like partial copy would be preferred here.

Overall, I think what you are suggesting makes sense, though I would argue that `fio` is not well suited for the sort of testing you are attempting to do, and so challenges you are observing are probably for this reason.

For the record, if you are doing a sequential copy of something, whether or not you use `dd`, you are subject to limitations of both the filesystem, assuming there is one, and the underlying media's ability to stream your IOs. In other words if you are observing excellent sequential performance, because in general only single thread is doing IO and underlying media can stream without having to seek (assuming mechanical here, solid state obviously plays by different rules) to reposition heads, whether your tool is `dd` or something else, merits of tool choice will be tiny, probably not even worth thinking about. Some tools of course are faster than others, but in general other factors will be far more major than tool choice for what sounds like a byte-for-byte copy.

**Comment by sitsofe** [comment]
For straight up sequential I/O from a single disk going through your OS's cache fio won't be much faster than dd when both are using a big enough block size unless your disk is so fast that a single core can't keep up (with current server grade CPUs you're talking faster than gigabytes per second).

In the buffered case the kernel has already detached submission from completion for you. In the unbuffered case you would have to replicate such a mechanism yourself (and that buffer needs to be big enough). Making that fast AND safe will be a challenge. If you can just do a boring buffered read then it's less challenging but then is it fast and will it be any faster than dd?

Given all this I can't see anyone working on this anytime soon so I'm going to close this ticket but if someone creates and submits a decent patch implementing this we'll definitely take a look!
