### ISSUE TITLE
MD5 verify fails with fio-2.17-17-g9cf1 when used with blocksize_range option. fio 2.16 works fine.

### ISSUE THREAD

**Issue by deepaktawri** [axboe/fio#296]
Hi,

With fio-2.17-17-g9cf1, hitting MD5 verification failure consistently when run following command whereas the same command had been working fine with fio 2.16/2.15 etc. Any idea if its regression ?

fio --ioengine=sync --rw=randrw --runtime=30 --time_based --iodepth=16 --verify=md5 --group_reporting --disable_lat=1 --disable_clat=1 --disable_slat=1 --disable_bw_measurement=1  --blocksize_range=4K-32K,32K-1024K --direct=1  --name=job1 --filename=/dev/nvme1n1 --name=job2 --filename=/dev/nvme2n1 

md5: verify failed at file /dev/nvme1n1 offset 121077760, length 32768
       Expected CRC: 4e125fe43c72ed9ba8d1366a6eeac328
       Received CRC: 74e229c66f022665b7f30e25c8110793
md5: verify failed at file /dev/nvme2n1 offset 4821581824, length 32768
       Expected CRC: 160b949bcd1ae4d206ef9fdfec8e9fbd
       Received CRC: 7d948a6a1c2759e1e8339bc8ec7a6d87

**Comment by sitsofe** [comment]
@deepaktawri Any chance you can do a git bisection to narrow down the point this might have been introduced in fio?

**Comment by sitsofe** [comment]
But there is one thing to note in the parameters ```--rw=randrw [...] --verify=md5```. Because this is doing mixed reads and writes with verify on it will potentially try and verify data which hasn't been written by this fio run in a similar way to ``--rw=randread [...] --verify=md5```. If the data from the previous pass doesn't match up (e.g. because it chose a different block size at that offset) you will have immediate failures. This should also happen with older versions of fio though...

**Comment by deepaktawri** [comment]
Thanks for the quick response. Changing --rw=randwrite worked.
Not sure why earlier versions of fio didn't throw this error. Thanks again.

**Comment by sitsofe** [comment]
Because you're using timeout I'll just add the usual caveat: you won't get a verify pass if you timeout before the write pass completes....

**Comment by deepaktawri** [comment]
I am not using do_verify option, so write phase and verify phase are not different. Right ? In other words, verify should happen after each write ?

Is timeout the reason it was working with earlier version of fio ?

**Comment by sitsofe** [comment]
Yes and no. When the write phase finishes a verification phase is started. It's not a separate job but it doesn't happen concurrently to the writes. If you're looking to do a few writes then a bit of verifying, then more writes I would recommend looking at verify_backlog (http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-verify_backlog ).

**Comment by sitsofe** [comment]
A quick amendment:
When the write phase finishes a verification phase is started IF verify= is being used (see http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-do_verify - "Run the verify phase after a write phase. Only valid if verify is set. Default: true.")

**Comment by deepaktawri** [comment]
So is following correct ?

I am not using do_verify option, so write phase and verify phase are not different. Right ? In other words, verify should happen after each write ?

**Comment by sitsofe** [comment]
@deepaktawri the write “phase” and read “phase” are different - they just happen in the same job.

We’re getting off topic for a bug report - “is this correct?” questions are better asked on the mailing list (see https://github.com/axboe/fio/blob/fio-2.17/README ). 

```
Example 1:
--filename=/dev/nullb0 --direct=1 --do_verify=1 --rw=write --name=example
```

Will do a write phase from the start to the end of `/dev/nullb0`. Even though it is 1, `do_verify` won't take effect because `verify` hasn’t been set.

```
Example 2:
--filename=/dev/nullb0 --direct=1 --rw=write --name=example
```

Same as previous because `do_verify` defaults to 1 if you don't set it but doesn't take effect when there's no `verify=`.

```
Example 3:
--filename=/dev/nullb0 --direct=1 --do_verify=1 --runtime=50ms --rw=write --name=example
```
 
Will do a write phase from the start to the end of `/dev/nullb0` but if 50 milliseconds passes it will stop early. Even though it is 1, `do_verify` won't take effect etc.

```
Example 4:
--filename=/dev/nullb0 --direct=1 --do_verify=1 --runtime=1h --time_based --rw=write --name=example
```
 
Will do a write phase from the start to the end of `/dev/nullb0 `. If the write phase gets to the end but 1 hour hasn't passed it will just loop back round to the beginning and continue (this is due to `time_based`). After 1 hour has passed the job (and hence the phase) will stop regardless of how many times the phase looped round or how far the current phase got. Even though it is 1, `do_verify` won't take effect etc.

```
Example 5:
--filename=/dev/nullb0 --direct=1 --do_verify=1 --verify=md5 --rw=write --name=example
```

Will do an initial write phase which writes from the start to the end of `/dev/nullb0`. What is written will contain a header which contains an md5 checksum of what is written. **After** the write **phase** reaches the end of the disk, a verifying read phase will be done from the start to the end of `/dev/nullb0`. This read phase takes place because `verify` was set and `do_verify` is 1.

```
Example 6:
--filename=/dev/nullb0 --direct=1 --verify=md5 --rw=write --name=example
```

Same as previous because `do_verify` defaults to 1 if you don't set it.

```
Example 7:
--filename=/dev/nullb0 --direct=1 --do_verify=0 --verify=md5 --rw=write --name=example
```

Will do only one phase which is a write phase from the start to the end of `/dev/nullb0`. What is written will contain a header etc. No verification phase takes place because `do_verify` is 0.

```
Example 8:
--filename=/dev/nullb0 --direct=1 --runtime=50ms --time_based --verify=md5 --rw=write --name=example
```

`do_verify` defaults to 1 because it hasn’t been set etc but see later. Will do an initial write phase which writes from the start to the end of `/dev/nullb0`. What is written will contain a header etc. If the write phase gets to the end but 50 milliseconds hasn't passed it will just loop back round to the beginning and continue (this is due to `time_based`). After 50 milliseconds has passed the job will stop regardless of how many times the current phase looped, how far the current phase got or whether there are phases yet to be done. Because the write phase never ends before the job exits (either it is cut short on the first pass or loops then is stopped) the verification phase never starts. An alternative summary of this situation is also given in http://www.spinics.net/lists/fio/msg04995.html .

**Comment by deepaktawri** [comment]
Thank you so much for detail reply. If I have any queries, will follow it up over the mailing list.
