### ISSUE TITLE
FIO 2.15/2.17 max completion latency (cLat) value per second in json output not  getting updated and reporting wrong data 

### ISSUE THREAD

**Issue by akoundal** [axboe/fio#308]
@axboe @sitsofe 
While running some quick workloads its been seen that the "max " value for the cLAT in the Json output is not getting updated for per second data. 
I did some experiments and when i enable the write max log i can see that each second the values are different which makes sense. (write_lat_log)

Now when you look at the json output with the status-internal=1s the max cLAT changes for first 2-3 seconds but then it gets stuck to a given max value and doesn't change. 

I am attaching the logs to show the difference. 
**Correct updates in (write_lat_log)** 
[clat.1.txt](https://github.com/axboe/fio/files/767856/clat.1.txt)

**Bad file of json  output using output-format=json --status-interval=1s**
[json.txt](https://github.com/axboe/fio/files/767864/json.txt)

This is causing wrong data to be charted if per second cLAT values are used for  plotting

**Comment by sitsofe** [comment]
@akoundal As mentioned in https://github.com/axboe/fio/blob/master/REPORTING-BUGS we at least need the fio command line + jobfile used to investigate most issues.

**Comment by akoundal** [comment]
My bad. here is the file which can be used use to regenerate the issue being reported. 
you will see that as i mentioned in my above clat.txt the max latency values are changing (cLAT values, completion latency), the test log file where the data is in json format is not updating the cLAT (max) value per second. 

here is the command i used : 
fio latency.txt  --status-interval=1s --output-format=json --output=test.log 


[latency.txt](https://github.com/axboe/fio/files/785608/latency.txt)

**Comment by sitsofe** [comment]
@akoundal I think this issue stems from a misunderstanding of what is displayed when `--status-interval` is used. It doesn't show only the average of statistics gathered in the current (status-interval) period - it shows the average of all statistics ever gathered (like the final summary you get at the end of run but up to that point in time). So if the worst I/O had a maximum completion latency of 10 in the first second, 100 in the second, then 10 in the third and fourth seconds and you were using a status-interval of 1s then the json output would report the max clat as 10, 100, 100, 100. An easy way to think about this is to consider what total_ios is printing and whether it ever goes down as I/O is done.

Issue #281 and issue #130 are already filed requests to have status-interval output average over stats from the current period rather than all time.

**Comment by sitsofe** [comment]
@akoundal before I forget did you see https://github.com/axboe/fio/issues/199#issuecomment-280565258 ?

**Comment by akoundal** [comment]
Thanks @sitsofe  I got the point. i thought it may the case exactly as what you are mentioning above but wanted to confirm from the experts. Appreciate your time in clarifying this. I am looking forward for the fixes reporting in the issue #281 and issue #130. 

Now regarding your #199 (comment)  ==> yes there is no confusion why the lat and clat are same. I am clear on that and currently have no confusions on that front.

**Comment by sitsofe** [comment]
@akoundal OK! Given that this issue has essentially been reported already and #199 seems to have been resolved could you close both issues?

**Comment by akoundal** [comment]
yes closing this now and looking forward for the fix for #281 and #130
