### ISSUE TITLE
fio endianness error on Windows

### ISSUE THREAD

**Issue by sitsofe** [axboe/fio#314]
While trying to prepare fio to run on appveyor I found that `make test` fails with an error message when using commit a0cb220bbb28c68fab0b175d01dcfce38a6f835c with a fresh build on Windows:

```
$ make test
./fio --minimal --ioengine=null --runtime=1s --name=nulltest --rw=randrw --iodepth=2 --norandommap --random_generator=tausworthe64 --size=16T --name=verifynulltest --rw=write --verify=crc32c --verify_state_save=0 --size=100M
fio: endianness settings appear wrong.
fio: not configured to any endianness
fio: please report this to fio@vger.kernel.org
make: *** [Makefile:452: test] Error 1
```

Reverting the following commit makes the error go away:
```
commit d0f2828f6e49613d944a980e018cbfc02901264b
Author: Tomohiro Kusumi <tkusumi@>
Date:   Tue Feb 14 17:19:42 2017 +0200

    configure: Drop default CONFIG_LITTLE_ENDIAN for Cygwin

    It's a bit strange that Cygwin is assumed to be le by default when
    no other platforms have such assumption even if they only target
    a single or certain arch (e.g. non-Android Linux often runs on x86,
    DragonFlyBSD only runs on x86, and so on..).

    Endianness will be detected by pointer arithmetic anyway, and it's
    better to rely on it to handle any sort of newly supported archs
    in the future.

    Signed-off-by: Tomohiro Kusumi <tkusumi@>
    Signed-off-by: Jens Axboe <axboe@>
```

@kusumi any ideas on this one?

**Comment by kusumi** [comment]
What does part say on ./configure ? I assume it doesn't even appear.

# grep "output_sym \"CONFIG_BIG_ENDIAN\"" ./configure -n -B1
1841-if test "$bigendian" = "yes" ; then
1842:  output_sym "CONFIG_BIG_ENDIAN"

It seems the problem comes from below where Cygwin finishes its ./configure without going through the pointer check (cast uint32 0x01234567 to uint8_t and tell endianness).
This is a special case for Cygwin (which only supports x86) and all other platforms go through the normal process which is better also for Cygwin to do.

# grep "exit 0" ./configure -n
332:  exit 0

I'll install Cygwin and try to fix this. It might be better to just revert this if it's not that easy to adapt regular ./configure process on Cygwin. Sorry for breaking.

**Comment by kusumi** [comment]
Sorry, I meant to ask what does this part say..
   echo "Big endian                    $bigendian"

**Comment by sitsofe** [comment]
Aha. The semi-helpful answer:
```
$ ./configure
Forcing known good options on Windows
```

so Windows actually doesn't run detection. Here's some extra output:
```
$ bash -x ./configure
+ test '!' -z ''
+ test '!' -z ''
+ TMPDIR1=/tmp
+ TMPC=/tmp/fio-conf-5089-1772-20148.c
+ TMPO=/tmp/fio-conf-18980-1772-19424.o
+ TMPE=/tmp/fio-conf-9456-1772-19436.exe
+ trap 'rm -f /tmp/fio-conf-5089-1772-20148.c /tmp/fio-conf-18980-1772-19424.o /                                 tmp/fio-conf-9456-1772-19436.exe' EXIT INT QUIT TERM
+ rm -rf config.log
+ config_host_mak=config-host.mak
+ config_host_h=config-host.h
+ rm -rf config-host.mak
+ rm -rf config-host.h
+ CFLAGS='-D_GNU_SOURCE -include config-host.h'
+ BUILD_CFLAGS=
++ date
+ echo '# FIO configure log Sun, Feb 19, 2017  8:08:40 AM'
+ printf '# Configured with:'
+ printf ' '\''%s'\''' ./configure
+ echo
+ echo '#'
+ echo '/*'
+ echo ' * Automatically generated by configure - do not modify'
+ printf ' * Configured with:'
+ printf ' * '\''%s'\''' ./configure
+ echo ''
+ echo ' */'
+ targetos=
+ cpu=
+ show_help=no
+ exit_val=0
+ gfio_check=no
+ libhdfs=no
+ pmemblk=no
+ devdax=no
+ disable_lex=
+ disable_pmem=no
+ prefix=/usr/local
+ test no = yes
+ cross_prefix=
+ cc=gcc
+ check_define __ANDROID__
+ cat
+ compile_object
+ do_cc -D_GNU_SOURCE -include config-host.h -c -o /tmp/fio-conf-18980-1772-1942                                 4.o /tmp/fio-conf-5089-1772-20148.c
+ echo gcc -D_GNU_SOURCE -include config-host.h -c -o /tmp/fio-conf-18980-1772-1                                 9424.o /tmp/fio-conf-5089-1772-20148.c
+ gcc -D_GNU_SOURCE -include config-host.h -c -o /tmp/fio-conf-18980-1772-19424.                                 o /tmp/fio-conf-5089-1772-20148.c
+ return 1
+ check_define __linux__
+ cat
+ compile_object
+ do_cc -D_GNU_SOURCE -include config-host.h -c -o /tmp/fio-conf-18980-1772-1942                                 4.o /tmp/fio-conf-5089-1772-20148.c
+ echo gcc -D_GNU_SOURCE -include config-host.h -c -o /tmp/fio-conf-18980-1772-1                                 9424.o /tmp/fio-conf-5089-1772-20148.c
+ gcc -D_GNU_SOURCE -include config-host.h -c -o /tmp/fio-conf-18980-1772-19424.                                 o /tmp/fio-conf-5089-1772-20148.c
+ return 1
+ check_define __OpenBSD__
+ cat
+ compile_object
+ do_cc -D_GNU_SOURCE -include config-host.h -c -o /tmp/fio-conf-18980-1772-1942                                 4.o /tmp/fio-conf-5089-1772-20148.c
+ echo gcc -D_GNU_SOURCE -include config-host.h -c -o /tmp/fio-conf-18980-1772-1                                 9424.o /tmp/fio-conf-5089-1772-20148.c
+ gcc -D_GNU_SOURCE -include config-host.h -c -o /tmp/fio-conf-18980-1772-19424.                                 o /tmp/fio-conf-5089-1772-20148.c
+ return 1
+ check_define __sun__
+ cat
+ compile_object
+ do_cc -D_GNU_SOURCE -include config-host.h -c -o /tmp/fio-conf-18980-1772-1942                                 4.o /tmp/fio-conf-5089-1772-20148.c
+ echo gcc -D_GNU_SOURCE -include config-host.h -c -o /tmp/fio-conf-18980-1772-1                                 9424.o /tmp/fio-conf-5089-1772-20148.c
+ gcc -D_GNU_SOURCE -include config-host.h -c -o /tmp/fio-conf-18980-1772-19424.                                 o /tmp/fio-conf-5089-1772-20148.c
+ return 1
+ check_define _WIN32
+ cat
+ compile_object
+ do_cc -D_GNU_SOURCE -include config-host.h -c -o /tmp/fio-conf-18980-1772-1942                                 4.o /tmp/fio-conf-5089-1772-20148.c
+ echo gcc -D_GNU_SOURCE -include config-host.h -c -o /tmp/fio-conf-18980-1772-1                                 9424.o /tmp/fio-conf-5089-1772-20148.c
+ gcc -D_GNU_SOURCE -include config-host.h -c -o /tmp/fio-conf-18980-1772-19424.                                 o /tmp/fio-conf-5089-1772-20148.c
+ return 1
++ uname -s
+ targetos=CYGWIN_NT-6.3
+ echo '# Automatically generated by configure - do not modify'
+ printf '# Configured with:'
+ printf ' '\''%s'\''' ./configure
+ echo
+ echo CONFIG_TARGET_OS=CYGWIN_NT-6.3
+ test '' = yes
+ test '' = yes
+ case $targetos in
+ echo 'Forcing known good options on Windows'
Forcing known good options on Windows
+ test -z ''
+ test '!' -z ''
+ CC=x86_64-w64-mingw32-gcc
+ test -e ../zlib/contrib/vstudio/vc14/x64/ZlibStatReleaseWithoutAsm/zlibstat.li                                 b
+ output_sym CONFIG_LITTLE_ENDIAN
+ echo CONFIG_LITTLE_ENDIAN=y
+ echo '#define CONFIG_LITTLE_ENDIAN'
+ test '!' -z ''
+ output_sym CONFIG_64BIT_LLP64
+ echo CONFIG_64BIT_LLP64=y
+ echo '#define CONFIG_64BIT_LLP64'
+ output_sym CONFIG_FADVISE
+ echo CONFIG_FADVISE=y
+ echo '#define CONFIG_FADVISE'
+ output_sym CONFIG_SOCKLEN_T
+ echo CONFIG_SOCKLEN_T=y
+ echo '#define CONFIG_SOCKLEN_T'
+ output_sym CONFIG_FADVISE
+ echo CONFIG_FADVISE=y
+ echo '#define CONFIG_FADVISE'
+ output_sym CONFIG_SFAA
+ echo CONFIG_SFAA=y
+ echo '#define CONFIG_SFAA'
+ output_sym CONFIG_RUSAGE_THREAD
+ echo CONFIG_RUSAGE_THREAD=y
+ echo '#define CONFIG_RUSAGE_THREAD'
+ output_sym CONFIG_WINDOWSAIO
+ echo CONFIG_WINDOWSAIO=y
+ echo '#define CONFIG_WINDOWSAIO'
+ output_sym CONFIG_FDATASYNC
+ echo CONFIG_FDATASYNC=y
+ echo '#define CONFIG_FDATASYNC'
+ output_sym CONFIG_CLOCK_MONOTONIC
+ echo CONFIG_CLOCK_MONOTONIC=y
+ echo '#define CONFIG_CLOCK_MONOTONIC'
+ output_sym CONFIG_GETTIMEOFDAY
+ echo CONFIG_GETTIMEOFDAY=y
+ echo '#define CONFIG_GETTIMEOFDAY'
+ output_sym CONFIG_CLOCK_GETTIME
+ echo CONFIG_CLOCK_GETTIME=y
+ echo '#define CONFIG_CLOCK_GETTIME'
+ output_sym CONFIG_SCHED_IDLE
+ echo CONFIG_SCHED_IDLE=y
+ echo '#define CONFIG_SCHED_IDLE'
+ output_sym CONFIG_TCP_NODELAY
+ echo CONFIG_TCP_NODELAY=y
+ echo '#define CONFIG_TCP_NODELAY'
+ output_sym CONFIG_TLS_THREAD
+ echo CONFIG_TLS_THREAD=y
+ echo '#define CONFIG_TLS_THREAD'
+ output_sym CONFIG_STATIC_ASSERT
+ echo CONFIG_STATIC_ASSERT=y
+ echo '#define CONFIG_STATIC_ASSERT'
+ output_sym CONFIG_IPV6
+ echo CONFIG_IPV6=y
+ echo '#define CONFIG_IPV6'
+ echo CC=x86_64-w64-mingw32-gcc
+ echo 'BUILD_CFLAGS=-D_GNU_SOURCE -include config-host.h -I../zlib -include con                                 fig-host.h -D_GNU_SOURCE'
+ exit 0
+ rm -f /tmp/fio-conf-5089-1772-20148.c /tmp/fio-conf-18980-1772-19424.o /tmp/fi                                 o-conf-9456-1772-19436.exe
```

**Comment by kusumi** [comment]
Btw, are you running this from Cygwin ?  I supposed fio is only supported on POSIX (like) environment ,but not regular Win32 environment.

**Comment by sitsofe** [comment]
@kusumi Yes I am - I have Cygwin installed but note that mingw is used.

**Comment by sitsofe** [comment]
Let me try that again (somehow the wrong button was pressed):
@kusumi Yes I am running this via Cygwin. I have Cygwin installed and I launch mintty via the Cygwin64 Terminal start menu link and do the configure within it.

Note that the configure script actually uses MinGW for the compiling so the binary produced will be for "native" non-Cygwin environments. A similar effect is seen when compiling like so:

```
C:\cygwin64\bin\bash.exe -lc 'cd "$OLDPWD"; make clean && make -j -l 2.0 test'
```

Thus saying that this is targetting the Cygwin platform is a bit of a misnomer because while we use some of the tools while building the final binary doesn't actually "run" in a POSIX environment (`--server` fails due to a lack of `fork`).

**Comment by kusumi** [comment]
ok, I have also confirmed it on Cygwin.

 $ ./configure
 Forcing known good options on Windows
 $ make -j8  (<- using mingw gcc for x86_64)
 ...
 $ ./fio.exe
 fio: endianness settings appear wrong.
 fio: not configured to any endianness
 fio: please report this to fio@vger.kernel.org

btw, I also saw a warning which I didn't see a few months ago on Cygwin.

 os/windows/posix.c:43:5: warning: 'vsprintf_s' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
 int vsprintf_s(
     ^

**Comment by kusumi** [comment]
It turned out that just removing exit 0 compiles using the normal configure process (that all other platforms go through).
I still need to see details of it, or why Cygwin happened to do it this way, but will hopefully either send a new patch or ask Jens to revert the existing commit.

 $ make clean
 ./FIO_VERSION = fio-2.17-59-ga0cb-dirty
 $ ./configure
 Forcing known good options on Windows
 Operating system              CYGWIN_NT-10.0
 CPU                           x86_64
 Big endian                    no       (<----- endian check pointer arithmetic detected LE)
 Compiler                      x86_64-w64-mingw32-gcc
 Cross compile                 no
 
 Static build                  no
 Wordsize                      32
 zlib                          no
 Linux AIO support             no
 POSIX AIO support             no
 POSIX AIO support needs -lrt  no
 POSIX AIO fsync               no
 <snip>.....
 bool                          yes
 march_armv8_a_crc_crypto      no
 Consider installing zlib-dev (zlib-devel), some fio features depend on it.

Try make

 $ make -j8 > /dev/null
 FIO_VERSION = fio-2.17-59-ga0cb-dirty
 os/windows/posix.c:43:5: warning: 'vsprintf_s' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
  int vsprintf_s(
      ^
 $ echo $?
 0

Try make test

 $ make test
 ./fio --minimal --ioengine=null --runtime=1s --name=nulltest --rw=randrw --iodepth=2 --norandommap --random_generator=tausworthe64 --size=16T --name=verifynulltest --rw=write --verify=crc32c --verify_state_save=0 --size=100M
 fio: this platform does not support process shared mutexes, forcing use of threads. Use the 'thread' option to get rid of this warning.
 fio: this platform does not support process shared mutexes, forcing use of threads. Use the 'thread' option to get rid of this warning.
 <snip>.....
 $ echo $?
 0

**Comment by kusumi** [comment]
This is the diff in case you want to use it right now.

 $ git diff
 diff --git a/configure b/configure
 index be29db9..5d17efb 100755
 --- a/configure
 +++ b/configure
 @@ -329,7 +329,6 @@ CYGWIN*)
    echo "CC=$CC" >> $config_host_mak
    echo "BUILD_CFLAGS=$CFLAGS -I../zlib -include config-host.h -D_GNU_SOURCE" >> $config_host_mak
 
 -  exit 0
    ;;
  esac

**Comment by sitsofe** [comment]
Thanks!

**Comment by sitsofe** [comment]
Hmm leaving the configure test output as is after the fixups is going to confuse people as it claims certain things are disabled even though the symbol may have been output. From https://ci.appveyor.com/project/sitsofe/fio/build/1.0.22/job/8ihlbj03do1b6oa0 :

```
bash.exe -lc "cd \"${APPVEYOR_BUILD_FOLDER}\" && ./configure ${CONFIGURE_OPTIONS} && make.exe -j 2
Forcing known good options on Windows
Operating system              CYGWIN_NT-6.3-WOW
CPU                           x86
Big endian                    no
Compiler                      i686-w64-mingw32-gcc
[...]
POSIX fadvise                 no
POSIX fallocate               no
sched_setaffinity(3 arg)      no
sched_setaffinity(2 arg)      no
clock_gettime                 no
CLOCK_MONOTONIC               no
CLOCK_MONOTONIC_RAW           no
CLOCK_MONOTONIC_PRECISE       no
clockid_t                     yes
gettimeofday                  yes
fdatasync                     no
sync_file_range               no
EXT4 move extent              no
Linux splice(2)               no
GUASI                         no
Fusion-io atomic engine       no
libnuma                       no
strsep                        no
strcasestr                    no
strlcat                       no
getopt_long_only()            yes
inet_aton                     no
socklen_t                     no
__thread                      yes
RUSAGE_THREAD                 no
SCHED_IDLE                    no
TCP_NODELAY                   no
Net engine window_size        no
TCP_MAXSEG                    no
RLIMIT_MEMLOCK                no
pwritev/preadv                no
pwritev2/preadv2              no
IPv6 helpers                  no
Rados Block Device engine     no
rbd blkin tracing             no
setvbuf                       yes
Gluster API engine            no
s390_z196_facilities          no
HDFS engine                   no
MTD                           no
libpmem                       no
libpmemblk                    no
NVML pmemblk engine           no
NVML dev-dax engine           no
lex/yacc for arithmetic       no
getmntent                     no
getmntinfo                    no
Static Assert                 yes
bool                          yes
march_armv8_a_crc_crypto      no
Consider installing zlib-dev (zlib-devel), some fio features depend on it.
```
and yet from forced options in configure:
```
 314   output_sym "CONFIG_FADVISE"
 315   output_sym "CONFIG_SOCKLEN_T"
 316   output_sym "CONFIG_FADVISE"
 317   output_sym "CONFIG_SFAA"
 318   output_sym "CONFIG_RUSAGE_THREAD"
 319   output_sym "CONFIG_WINDOWSAIO"
 320   output_sym "CONFIG_FDATASYNC"
 321   output_sym "CONFIG_CLOCK_MONOTONIC"
 322   output_sym "CONFIG_GETTIMEOFDAY"
 323   output_sym "CONFIG_CLOCK_GETTIME"
 324   output_sym "CONFIG_SCHED_IDLE"
 325   output_sym "CONFIG_TCP_NODELAY"
 326   output_sym "CONFIG_TLS_THREAD"
 327   output_sym "CONFIG_STATIC_ASSERT"
 328   output_sym "CONFIG_IPV6"
```

Look at what happened with

**Comment by kusumi** [comment]
Yeah, that was my concern when it mentioned about checking details.

The real problem here is that Cygwin has hard-coded output_sym() switch rather than going through generic tests used by all other OSes. The endianness test was just one of those.
If Cygwin _knows_ whatever results from compile_prog() during configure process are wrong and wants to override the result with hard-coded output_sym(), maybe it can do that after that process.
It currently does before that process with "Forcing known good options on Windows", and this is Cygwin specific.

By Looking at small details of compile_prog() tests (without looking into Cygwin details), I wonder why Cygwin failed to compile posix_fadvise(). If hard-coded output_sym() for fadvise says it's supported why does this not compile on Cygwin ?

     72 /tmp/fio-conf-15556-8368-1496.c:5:11: warning: implicit declaration of function 'posix_fadvise' [-Wimplicit-function-declaration]
     73    int r = posix_fadvise(0, 0, 0, POSIX_FADV_NORMAL);
     74            ^
     75 /tmp/fio-conf-15556-8368-1496.c:5:34: error: 'POSIX_FADV_NORMAL' undeclared (first use in this function)
     76    int r = posix_fadvise(0, 0, 0, POSIX_FADV_NORMAL);
     77                                   ^

**Comment by kusumi** [comment]
@sitsofe Which CONFIG are you specifically talking about for the mismatch ?  CONFIG_FADVISE I mentioned in the previous post as an example seems just a plain wrong(unused) CONFIG which is another problem of this script.

For the possible solution (that just came to my mind I haven't even coded), Cygwin switch-case part could have just set
variable="yes"

and change the compile_prog() part to initialize that variable with "no" only if it hasn't been set to "yes" or something.
This way, we don't see "something    no" even if compile_prog() somehow fails to compile.

Cygwin somehow wants to use the shell variables rather than directly doing output_sym() in Cygwin specific rule to be a generic configure script,  or we could just revert my commit and stick with what we had for now.

**Comment by kusumi** [comment]
OK, monotonic one.
The solution I mentioned is something like this.
I've applied this only against CONFIG_CLOCK_MONOTONIC for now as a showcase since that's the one you brought up, but this way, Cygwin goes through generic configure tests based on compile time switch, yet able to handle special cases like this with generic (non ad-hoc) code.

$ git diff
diff --git a/configure b/configure
index be29db9..3db3f27 100755
--- a/configure
+++ b/configure
@@ -318,7 +318,6 @@ CYGWIN*)
   output_sym "CONFIG_RUSAGE_THREAD"
   output_sym "CONFIG_WINDOWSAIO"
   output_sym "CONFIG_FDATASYNC"
-  output_sym "CONFIG_CLOCK_MONOTONIC"
   output_sym "CONFIG_GETTIMEOFDAY"
   output_sym "CONFIG_CLOCK_GETTIME"
   output_sym "CONFIG_SCHED_IDLE"
@@ -326,10 +325,10 @@ CYGWIN*)
   output_sym "CONFIG_TLS_THREAD"
   output_sym "CONFIG_STATIC_ASSERT"
   output_sym "CONFIG_IPV6"
+  clock_monotonic="yes" # We statically know we have this regardless of what compilers say
   echo "CC=$CC" >> $config_host_mak
   echo "BUILD_CFLAGS=$CFLAGS -I../zlib -include config-host.h -D_GNU_SOURCE" >> $config_host_mak

-  exit 0
   ;;
 esac

@@ -770,7 +769,9 @@ echo "clock_gettime                 $clock_gettime"

 ##########################################
 # CLOCK_MONOTONIC probe
-clock_monotonic="no"
+if test "${clock_monotonic}" != "yes" ; then
+  clock_monotonic="no"
+fi
 if test "$clock_gettime" = "yes" ; then
   cat > $TMPC << EOF
 #include <stdio.h>

**Comment by kusumi** [comment]
OK, monotonic one.
The solution I mentioned is something like this.

I've applied this only against CONFIG_CLOCK_MONOTONIC for now since that's the one you brought up, but this way, Cygwin goes through generic configure tests based on compile time switch, yet able to handle special cases like this with generic (non ad-hoc) code.

```
$ git diff
diff --git a/configure b/configure
index be29db9..70367fb 100755
--- a/configure
+++ b/configure
@@ -318,7 +318,6 @@ CYGWIN*)
   output_sym "CONFIG_RUSAGE_THREAD"
   output_sym "CONFIG_WINDOWSAIO"
   output_sym "CONFIG_FDATASYNC"
-  output_sym "CONFIG_CLOCK_MONOTONIC"
   output_sym "CONFIG_GETTIMEOFDAY"
   output_sym "CONFIG_CLOCK_GETTIME"
   output_sym "CONFIG_SCHED_IDLE"
@@ -326,10 +325,10 @@ CYGWIN*)
   output_sym "CONFIG_TLS_THREAD"
   output_sym "CONFIG_STATIC_ASSERT"
   output_sym "CONFIG_IPV6"
+  clock_monotonic="yes" # We statically know we have this regardless of what compilers say
   echo "CC=$CC" >> $config_host_mak
   echo "BUILD_CFLAGS=$CFLAGS -I../zlib -include config-host.h -D_GNU_SOURCE" >> $config_host_mak

-  exit 0
   ;;
 esac

@@ -770,7 +769,9 @@ echo "clock_gettime                 $clock_gettime"

 ##########################################
 # CLOCK_MONOTONIC probe
-clock_monotonic="no"
+if test "${clock_monotonic}" != "yes" ; then
+  clock_monotonic="no"
+fi
 if test "$clock_gettime" = "yes" ; then
   cat > $TMPC << EOF
 #include <stdio.h>
```

**Comment by sitsofe** [comment]
@kusumi Sadly that's one of many:

```
 314   output_sym "CONFIG_FADVISE"
doesn't actually match anything (closest would be POSIX fadvise which is no)
 315   output_sym "CONFIG_SOCKLEN_T"
socklen_t                     no
 316   output_sym "CONFIG_FADVISE"
[Doesn't match anything... again]
 317   output_sym "CONFIG_SFAA"
__sync_fetch_and_add          yes [correctly found]
 318   output_sym "CONFIG_RUSAGE_THREAD"
RUSAGE_THREAD                 no
 319   output_sym "CONFIG_WINDOWSAIO"
[not tested for]
 320   output_sym "CONFIG_FDATASYNC"
fdatasync                     no
 321   output_sym "CONFIG_CLOCK_MONOTONIC"
CLOCK_MONOTONIC               no
 322   output_sym "CONFIG_GETTIMEOFDAY"
gettimeofday                  yes [correctly found]
 323   output_sym "CONFIG_CLOCK_GETTIME"
clock_gettime                 no
 324   output_sym "CONFIG_SCHED_IDLE"
SCHED_IDLE                    no
 325   output_sym "CONFIG_TCP_NODELAY"
TCP_NODELAY                   no
 326   output_sym "CONFIG_TLS_THREAD"
__thread                      yes [this one is correct]
 327   output_sym "CONFIG_STATIC_ASSERT"
Static Assert                 yes [this one is correct]
 328   output_sym "CONFIG_IPV6"
IPv6 helpers                  no
```
There are so many that are being overridden I think it would be safer to revert for now. What is really needed is the ability to say to a test that its output has been forced so the result can explicitly say "forced". It's that or rewrite the tests to have `#ifdef` Windows paths...

All this behaviour stems from the fact that there is platform specific code that is plugged in place when the regular method is not found. I think the setting of `CONFIG_FADVISE` is actually buggy - nothing references it! The windowsaio engine could have used it to determine whether to translate hints but it always hardcodes hints regardless of what the user asks for. A better example might be CONFIG_FDATASYNC which is quietly shimmed to fsync which in turn is shimmed to `FlushFileBuffers` within `os/windows/posix.c`. Also remember the compiler is from MinGW not Cygwin so it won't have access to all of Cygwin's POSIX shims...

**Comment by kusumi** [comment]
I've sent a series of patches including revert of this for now, and removal of CONFIG_FADVISE. POSIX fadvise is CONFIG_POSIX_ADVISE and it doesn't compile on Cygwin, or at least the test code embedded in our ./configure script doesn't compile on Cygwin.

>  What is really needed is the ability to say to a test that its output has been forced so the result can explicitly say "forced". 

Why do we need to show users it's forced ? We don't need to make any external changes, and fio's Cygwin port has never done it too. It's works as long as Cygwin port knows what are the right configuration, then we can safely ignore whatever a compiler said.

> A better example might be CONFIG_FDATASYNC which is quietly shimmed to fsync which in turn is shimmed to FlushFileBuffers within os/windows/posix.c. Also remember the compiler is from MinGW not Cygwin so it won't have access to all of Cygwin's POSIX shims...

Why would implementation matter here ? All we need here is again to safely override what compilers said and enable what Cygwin thinks/knows is correct.

The diff snippet I pasted in my previous post would hopefully solve this without having ad-hoc code like any sort of Windows specific ifdefs (except that the snippet is only made for the monotone one you mentioned). This will also be usable for anyone who wants to override whatever compilers think in the future. i.e. makes the whole fio more portable and less platform (Linux) dependent.

To be more specific for this Cygwin case,
1. For the endianness, it really doesn't need to be output_sym'd there as I've mentioned in the original commit, plus we already know that the regular compile_prog() based switch works.
2. CONFIG_WINDOWSAIO (or maybe any other?) needs to be output_sym'd here since this is 100% Windows specific configuration.
3. For other feature level configs that aren't Windows specific, making CYGWIN* case use variables instead of directly calling output_sym() (as shown in previous post) should work. The important thing here is that all variables need to be tested if they've already been set to "yes" or not before initializing them with "no".

**Comment by sitsofe** [comment]
> Why do we need to show users it's forced ? Whether it's forced or not is just an internal logic of our configuration script

My thought was we only do that if we were to still run all the configure tests rather than just short circuiting them as we do today. That way you aren't fooled into thinking your platform provides the   `clock_gettime` function when it is actually emulated within fio. Perhaps the word "emulated" would have been a little closer to the truth.

> [Re CONFIG_FDATASYNC] Why would implementation matter here ? 

Because technically Windows fio doesn't have fdatasync - it has something more akin to fsync. If I were comparing two platforms where one had a real fdatasync and the other was using Windows fio's emulated one I would actually be biasing things in favour of the one with the real fdatasync (such is life). My thinking went that if the user were to compile fio I might get a hint as to what was going on if it told me features that were emulated.

I do see that you're saying "the fact that it emulated doesn't mean we can't just say yes" though. Further, your recent commits fix this issue so thanks for taking a look and I'll close this issue!

**Comment by kusumi** [comment]
I still don't get this. Why would the fact some syscall equivalent doesn't exist in Windows matter here ? Some BSDs don't have fdatasync(2) too and they still go through the regular configure path that Linux goes through. BSDs don't say some syscalls behave differently on ./configure. There are lots of those if you look into manpages or os/os-*.h in fio itself. For example, Linux is the only platform that can clear page cache using a Linux specific ioctl. BSDs or Solaris or whatever don't say page cache flush does nothing on ./configure, though it could have been written in HOWTO.

Because of this, we aren't talking about whether a certain implementation behaves the same or not here. That's a totally different topic from making fio run regular configure path. If your intention is to say that we should somehow let users know "Windows does something other than fdatasync(2)" while running configure script (by showing for e.g. "something yes (but emulated or something)"), that should be done in a different commit by not limiting it to Windows/Cygwin.

If you really want to show its's "emulated", you somehow need to do that for other platforms that don't have fdatasync(2) as well or even other syscalls/etc preferably. If fdatasync(2) is the only syscall with the  "emulation" notification message, then users would think that's the only one behaves differently. Some syscalls/etc not existing or not doing the exact same thing as Linux kernel (or Linux kernel not doing the same thing for whatever originates in other Unix like) is a quite common thing. It's not something special for Windows/Cygwin, so we shouldn't care about that in this Windows/Cygwin topic.

**Comment by sitsofe** [comment]
@kusumi OK that a comprehensive explanation as to why we can only say yes regardless of whether fio has to emulate it or whether it found a native function (because we don't necessarily know how it is emulated at configure time).
