### ISSUE TITLE
Verify Issue

### ISSUE THREAD

**Issue by ShuaiGeng** [axboe/fio#322]
When i do the verify case with following commands:
Looks like i don't see any verify data after verify command ?

**Write Phase**
[root@localhost Shuai]# fio --ioengine=libaio --iodepth=16 --runtime=60 --time_based --bs=4k --verify=pattern --verify=pattern --verify_pattern=0xfffffffff --group_reporting --disable_lat=1 --disable_clat=1 --disable_slat=1 --disable_bw_measurement=1 --rw=randwrite --do_verify=0 --verify_state_save=1  --name=job1 --filename=/dev/nvme0n1
job1: (g=0): rw=randwrite, bs=4096B-4096B,4096B-4096B,4096B-4096B, ioengine=libaio, iodepth=16
fio-2.18
Starting 1 process
Jobs: 1 (f=1): [f(1)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:00s]       
job1: (groupid=0, jobs=1): err= 0: pid=23129: Mon Feb 27 22:36:01 2017
  write: IOPS=48.8k, BW=191MiB/s (200MB/s)(11.2GiB/60003msec)
    clat percentiles (usec):
     |  1.00th=[    0],  5.00th=[    0], 10.00th=[    0], 20.00th=[    0],
     | 30.00th=[    0], 40.00th=[    0], 50.00th=[    0], 60.00th=[    0],
     | 70.00th=[    0], 80.00th=[    0], 90.00th=[    0], 95.00th=[    0],
     | 99.00th=[    0], 99.50th=[    0], 99.90th=[    0], 99.95th=[    0],
     | 99.99th=[    0]
  cpu          : usr=4.44%, sys=18.91%, ctx=10842, majf=0, minf=26
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=100.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=0,2926599,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
  WRITE: bw=191MiB/s (200MB/s), 191MiB/s-191MiB/s (200MB/s-200MB/s), io=11.2GiB (11.1GB), run=60003-60003msec

Disk stats (read/write):
  nvme0n1: ios=61/2835057, merge=0/0, ticks=3/97767647, in_queue=97901910, util=99.45%

**Verify Phase**
[root@localhost Shuai]# fio --ioengine=libaio --iodepth=16 --runtime=60 --time_based --bs=4k --verify=pattern --verify=pattern --verify_pattern=0xfffffffff --group_reporting --disable_lat=1 --disable_clat=1 --disable_slat=1 --disable_bw_measurement=1 --rw=randread --do_verify=1 --verify_state_load=1  --name=job1 --filename=/dev/nvme0n1
job1: (g=0): rw=randread, bs=4096B-4096B,4096B-4096B,4096B-4096B, ioengine=libaio, iodepth=16
fio-2.18
Starting 1 process
Jobs: 1 (f=1): [V(1)][100.0%][r=43.6MiB/s,w=0KiB/s][r=11.2k,w=0 IOPS][eta 00m:00s]
job1: (groupid=0, jobs=1): err= 0: pid=23177: Mon Feb 27 22:40:42 2017
   read: IOPS=10.4k, BW=40.6MiB/s (42.6MB/s)(2434MiB/60001msec)
    clat percentiles (usec):
     |  1.00th=[    0],  5.00th=[    0], 10.00th=[    0], 20.00th=[    0],
     | 30.00th=[    0], 40.00th=[    0], 50.00th=[    0], 60.00th=[    0],
     | 70.00th=[    0], 80.00th=[    0], 90.00th=[    0], 95.00th=[    0],
     | 99.00th=[    0], 99.50th=[    0], 99.90th=[    0], 99.95th=[    0],
     | 99.99th=[    0]
  cpu          : usr=2.74%, sys=7.35%, ctx=623267, majf=0, minf=51
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=100.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=623223,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
   READ: bw=40.6MiB/s (42.6MB/s), 40.6MiB/s-40.6MiB/s (42.6MB/s-42.6MB/s), io=2434MiB (2553MB), run=60001-60001msec

Disk stats (read/write):
  nvme0n1: ios=622171/0, merge=0/0, ticks=53806/0, in_queue=53732, util=89.59%
[root@localhost Shuai]#

**Comment by sitsofe** [comment]
This is to be expected - you have the following:
` --runtime=60 --time_based [...] --rw=randwrite`

This will make the randwrite phase chew up all 60s of the runtime so the job will end before the verify phase can begin. See https://github.com/axboe/fio/issues/187#issuecomment-223633831 and https://www.spinics.net/lists/fio/msg04990.html for other explanations of this behaviour. One of the proposed patches in https://github.com/axboe/fio/pull/313 for a patch that prints out a warning related to this.

**Comment by sitsofe** [comment]
@ShuaiGeng I apologise, I've reread your jobs and your second job looked like this:
```
--runtime=60 --time_based --verify=pattern [...] --rw=randread [...] --do_verify=1 --verify_state_load=1
```

The `--do_verify=1` is only used if the job does writes so it has no affect here. However the output you included says this:

```
Jobs: 1 (f=1): [V(1)][100.0%][r=43.6MiB/s,w=0KiB/s][r=11.2k,w=0 IOPS][eta 00m:00s]
```

That capital V means it was a verify job rather than a plain read job. Given that you're loading a state file it means those reads for areas that the state file says were written (and were undamaged by later writes) will actually result in the data that was read also being verified (and those for other areas won't be). What extra verify output were you expecting to see?

The problem with trying to do verification of jobs that used time_based verification is that it's hard to control just how much ends up being verified. If the verify job ends early because of the runtime is exceeded it could be that some areas that could have been verified remain unverified.

**Comment by ShuaiGeng** [comment]
@sitsofe Thanks for the explanation, i just wanna do a normal data verification test and can see the data verify visibly after verify , do you have any recommendation in the fio command ?

**Comment by sitsofe** [comment]
@ShuaiGeng fio takes the attitude that if no verification errors were found very little extra output is shown but when verification errors ARE found that information is displayed. For example, run the following in a normal interactive terminal (as opposed to within some remote script or non-interactively) and see what happens:
```
dd if=/dev/zero of=/tmp/zero bs=256K count=1
fio --name=verify --rw=read --verify=pattern --verify_pattern=0xaa --filename=/tmp/zero
```

With regard to structuring the verification part: 
1. If you're happy verifying everything and time is not a problem use the "verify phase" that you get with `do_verify=1` on write jobs that have `verify` set.
2. If 1. can't be done (e.g. because it's not desirable to write/verify everything) look into limiting the write/verify by region ([`size`](http://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-size) / [`offset`](http://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-offset)).
3. If 2. is undesirable (e.g. you want to do only do 1Mbyte but you don't want to just do it to the first 1Mbyte of the disk) try and set a deterministic limit using something other than time (e.g. [`io_size`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-io_size)).
4. Perhaps only running for a particular time is absolutely necessary and you're willing to accept a tradeoff that some written data might not be verified. You can use the inline verify option [`verify_backlog`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-verify_backlog) with `runtime`. Obviously when the time the job ends the very last outstanding batch of writes might not be verified.
5. Perhaps 4. is unacceptable and time must still be obeyed and you must try and verify as much as possible. Use your solution of splitting the writing and verifying into completely separate jobs but avoid setting `runtime` on the second job.

(Perhaps this issue should be closed because it's really close to a "how do I?" question and further discussion moved on to the [mailing list](https://github.com/axboe/fio/blob/fio-2.17/README#L77))

**Comment by sitsofe** [comment]
(PS: you may want to look at using [`gtod_reduce`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-gtod_reduce))

**Comment by sitsofe** [comment]
@ShuaiGeng has your question been answered? If so do you think you can close this issue?

**Comment by sitsofe** [comment]
@ShuaiGeng can you close this issue if your question has been answered? Thank you.
