### ISSUE TITLE
mmap options dictate a minimum block size of 4k bytes

### ISSUE THREAD

**Issue by gpuy39** [axboe/fio#339]
Hi,

I'm trying to run FIO with workload blocksize parameter value which is less than 4k. Is it possible ? Part of my example jobfile looks like this:

overwrite=1
direct=1
ioengine=mmap
size=$size$
filename=$file_name$
rw=randrw
numjobs=10
iodepth=1
thinktime=0
bs=256
rwmixread=0
percentage_random=0
runtime=300
ramp_time=30
log_avg_msec=500

**Comment by sitsofe** [comment]
Hi @gpuy39,

(This is more of a question that a bug so might have been better sent to the mailing list)

You're using `direct=1` which typically means your I/Os *must* be well aligned and must be a multiple of the size of a sector (see the rules on using O_DIRECT in the notes of http://man7.org/linux/man-pages/man2/open.2.html ). If the minimum sector size of the disk/filesystem you're doing I/O to is 4Kbytes (not unusual for SSDs) then you will be unable to submit directio in amounts smaller than 4Kbytes. Obviously if you're not doing direct I/O this rule doesn't exist but you'll potentially get caching effects.

**Comment by sitsofe** [comment]
Digging a bit deeper the problem actually arises because the mmap ioengine approximates direct I/O by using `msync()` (see https://github.com/axboe/fio/blob/fio-2.19/engines/mmap.c#L189 ).

The address passed to `msync()` call *must* be page aligned (http://man7.org/linux/man-pages/man2/msync.2.html#ERRORS ). It is possible to see the page size on your setup by running `getconf PAGESIZE`. If fio's block sizes aren't multiples of the page size it is clear that not all I/O offsets will obey the `msync()` address requirement (e.g. with a page size of 4096 when using bs=512 the second block has an offset of 512 which is not on a 4096 boundary).

So if your system's page size is 4096, you are using fio's mmap engine and your jobfile contains `direct=1` then it is **not** possible to use a block size (such as 512) that is not a multiple of 4096 bytes.

@gpuy39 hopefully the above answers your question. If so could you close this issue?

**Comment by gpuy39** [comment]
Thanks for all your answers it was VERY helpful. At that moment it was a bit hard to understand how it works but you guys made it very simple so thank you.
