### ISSUE TITLE
FIO won't close and open other files for IO

### ISSUE THREAD

**Issue by panxiao2014** [axboe/fio#358]
FIO: fio-2.19-60-gc55f
OS: Red Hat Enterprise Linux Server release 7.2 (Maipo)

I have the following profile:
[global]
ioengine=libaio
direct=1
refill_buffers=1
time_based=1
runtime=3000000
readwrite=readwrite
bs=8K
numjobs=1
nrfiles=20
openfiles=10
filesize=256k

[0]
directory=/mnt/fs1/nrfile

What I am expecting is that FIO will first serve the first 10 files, have some IO, close them and open the next 10 files for IO. But by watching the FD opened by running FIO process, it looks like FIO never change to the next 10 files:

Every 1.0s: lsof +D /mnt/fs1/nrfile/                                                                             Thu May  4 22:58:48 2017

COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
bash    28310 root  cwd    DIR   0,40     8192 9439 /mnt/fs1/nrfile
fio     30788 root    3u   REG   0,40   262144 9438 /mnt/fs1/nrfile/0.0.0
fio     30788 root    4u   REG   0,40   262144 9440 /mnt/fs1/nrfile/0.0.1
fio     30788 root    5u   REG   0,40   262144 9441 /mnt/fs1/nrfile/0.0.2
fio     30788 root    6u   REG   0,40   262144 9442 /mnt/fs1/nrfile/0.0.3
fio     30788 root    7u   REG   0,40   262144 9443 /mnt/fs1/nrfile/0.0.4
fio     30788 root    8u   REG   0,40   262144 9444 /mnt/fs1/nrfile/0.0.5
fio     30788 root    9u   REG   0,40   262144 9445 /mnt/fs1/nrfile/0.0.6
fio     30788 root   10u   REG   0,40   262144 9446 /mnt/fs1/nrfile/0.0.7
fio     30788 root   11u   REG   0,40   262144 9447 /mnt/fs1/nrfile/0.0.8
fio     30788 root   12u   REG   0,40   262144 9448 /mnt/fs1/nrfile/0.0.9
vim     31128 root  cwd    DIR   0,40     8192 9439 /mnt/fs1/nrfile

I also tried random service type but got the same result. Once FIO chose to open 10 files, it stayed on them and did not change to other files. Could you please check thist? Thanks.

**Comment by sitsofe** [comment]
@panxiao2014 This is due to the impact of [`time_based`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-time-based) on a job which means the starting files are never actually finished with (the user requested fio to continue even when the file has been completely accessed) thus there is never a need to select another file. For example if at a bash prompt I run:
```
rm /tmp/fio/0.0.*
fio --time_based --runtime=10s --rw=write --bs=8K --nrfiles=20 --openfiles=1 --filesize=24k --directory=/tmp/fio/ --buffer_pattern=\"written\" --name=0 
head -c 7 fio/0.0.*
```

I can see only the first file has been written despite thousands of megabytes of I/O having been done.

If instead I do this:
```
rm /tmp/fio/0.0.*
fio --rw=write --bs=8K --nrfiles=20 --openfiles=1 --filesize=24k --directory=/tmp/fio/ --buffer_pattern=\"written\" --name=0 
head -c 7 fio/0.0.*
```

every file is written to.

You might get the effect you're after using one of the other I/O extending options (e.g.
 [`number_ios`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-number-ios), [`io_size`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-io-size), [`loops`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-loops)) with a high number but then using `runtime` (without `time_based`) to cap the time...

**Comment by panxiao2014** [comment]
thanks, it works fine now.
