### ISSUE TITLE
fio sending writes of  "1 Byte" while writing 10G file 

### ISSUE THREAD

**Issue by aspandey** [axboe/fio#376]
We have used following command and options of fio tool to test performance of glusterfs - 

fio --randrepeat=1 --ioengine=libaio --direct=0 --gtod_reduce=1 --name=test --filename=fiotest.fio --iodepth=16 --size=10G --readwrite=write
test: (g=0): rw=write, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=16

We have observed a very low performance. So when we captured and analyzed the packets over the network between client  and server we saw that it is sending a lot of writes of length "1 Bytes"

We have used this on nfs client and also glusetrfs client.

We don't know if it is expected form fio or it is a valid bug in fio tool. If it is expected, please explain the reason behind it.

[fio-nfs-without-truncate-pacp.txt](https://github.com/axboe/fio/files/1040997/fio-nfs-without-truncate-pacp.txt)

**Comment by axboe** [comment]
Fio is writing in 4k chunks, if you don't give the bs= setting. So I'm inclined to blame gluster here. One oddity is that you are doing buffered writes, but you use libaio. This won't give you queue depth, as the writes will be sync (in the sense that they are completed on the OS side when returning, they could just be in the page cache). It's also possible that gluster does something weird with fallocate. You could try and add --fallocate=none to your options.

**Comment by sitsofe** [comment]
@aspandey also just to verify: you're I/O you are doing is going to go into a file called "fiotest.fio" within the directory you are standing in when you run fio. If that isn't actually in your gluster filesystem that may explain the results you see...

**Comment by aspandey** [comment]
Actually, gluster does not even comes into picture. 
The file which I have attached, contains packets between nfs client and nfs server.
I think this issue could be reproduced easily if we just write this fio  on a nfs mount point.

Niels (ndevos@redhat.com) has also faced the same issue and his findings are even more interesting. 
His findings () he did directio- 
It seems that fio does a single byte write at the last byte of each page (a page is 4096 bytes. stracing fio shows:
part of the trace of fio command - 
2314  pwrite(3, "\0", 1, 4095 <unfinished ...>
2314  <... pwrite resumed> )            = 1
2314  pwrite(3, "\0", 1, 8191)          = 1
2314  pwrite(3, "\0", 1, 12287)         = 1
2314  pwrite(3, "\0", 1, 16383)         = 1
2314  pwrite(3, "\0", 1, 20479)         = 1
2314  pwrite(3, "\0", 1, 24575)         = 1
2314  pwrite(3, "\0", 1, 28671 <unfinished ...>
...

Because this is directio, the whole page is expected to be written, but the NFS-client does not seem to write the whole page. Possibly the NFS-client is smart enough to understand that the page can not exist on the server, because the file is newly created.

Possibly related to this, is that fallocate() failed to create the full allocated file before fio starts the pwrites:

2314  open("/mnt/f.0.0", O_WRONLY|O_CREAT, 0644) = 3
2314  fallocate(3, 0, 0, 4294967296)    = -1 EOPNOTSUPP (Operation not supported)
2314  fstat(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
fallocate() is not supported over NFSv3, instead truncate() should be used (or just use pre-existing files?).

**Comment by axboe** [comment]
Lets boil this down into a simple test case. Does it happen locally? If it does, what was run specifically? Does it happen only on NFS?

Fio definitely doesn't split writes, unless the OS returns a short write. In fact, from the trace you show above, the kernel would have errored that with EINVAL, since it's an unaligned O_DIRECT write. So that must be buffered IO as well, not direct.

**Comment by sitsofe** [comment]
OK which version of the OS and which version of fio? Can you make the problem happen with a much smaller size (such as `--size=64k`) and does --debug=all give any clues? Can you make the same thing happen on non-NFS mounts?

**Comment by sitsofe** [comment]
@aspandey fio doesn't truncate a file if preallocation fails - see http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-fallocate . I guess you'll get the file laid out as the I/O happens. Falling back to truncation would potentially make a sparse file (in the case that file needed to be made before doing I/O) which may or may not be desirable but wouldn't really speed things up.

**Comment by aspandey** [comment]
-  OS - 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
- fio-2.2.8
I will definitely try the steps you have asked for and give you more information.
I tried smaller size as --size=1G only. Will see if I can reduce it and face same issue.

In case it helps,  when we did truncate of the file and then tried to run same fio command, it completed in 2m for 10G data and this is what we were expecting. Can not say if the data written was the same data which we wanted to write or we missed something.

**Comment by sitsofe** [comment]
That version of fio is extremely old. Does the problem also happen with the latest fio on your system?

I've just run the following on a local filesystem:
```
strace -f ./fio --thread --randrepeat=1 --direct=0 --gtod_reduce=1 --name=test --filename=fiotestrmme --iodepth=16 --size=128k --readwrite=write
```

using fio-2.20-8-gdbf2-dirty and I got lines like this:
```
[...]
[pid 61565] fadvise64(3, 0, 131072, POSIX_FADV_DONTNEED) = 0
[pid 61565] fadvise64(3, 0, 131072, POSIX_FADV_SEQUENTIAL) = 0
[pid 61565] clock_gettime(CLOCK_MONOTONIC_RAW, {2683567, 981218300}) = 0
[pid 61565] pwrite64(3, "\0\0\0\0\0\0\0\0\2401\227\246\235b5\0074\346\2\34\10\331\367\2\306\\f\220\37\355F\2"..., 4096, 0) = 4096
[pid 61565] clock_gettime(CLOCK_MONOTONIC_RAW, {2683567, 981462300}) = 0
[pid 61565] pwrite64(3, "\0\20\0\0\0\0\0\0\2401\227\246\235b5\0074\346\2\34\10\331\367\2\306\\f\220\37\355F\2"..., 4096, 4096) = 4096
[pid 61565] clock_gettime(CLOCK_MONOTONIC_RAW, {2683567, 981677300}) = 0
[pid 61565] pwrite64(3, "\0 \0\0\0\0\0\0\2401\227\246\235b5\0074\346\2\34\10\331\367\2\306\\f\220\37\355F\2"..., 4096, 8192) = 4096
[...]
```

Doing
```
./fio --debug=all --randrepeat=1 --direct=0 --gtod_reduce=1 --name=test --filename=fiotestrmme --iodepth=16 --size=128k --readwrite=write
```
produced debug something like this:
```
[...]
file     61568 get file fiotestrmme, ref=1
io       61568 fill_io_u: io_u 0x2fff9c0: off=0/len=4096/ddir=1io       61568 /fiotestrmmeio       61568 
io       61568 prep: io_u 0x2fff9c0: off=0/len=4096/ddir=1io       61568 /fiotestrmmeio       61568 
io       61568 queue: io_u 0x2fff9c0: off=0/len=4096/ddir=1io       61568 /fiotestrmmeio       61568 
io       61568 io complete: io_u 0x2fff9c0: off=0/len=4096/ddir=1io       61568 /fiotestrmmeio       61568 
file     61568 put file fiotestrmme, ref=2
file     61568 trying file fiotestrmme 31
file     61568 goodf=1, badf=2, ff=31
file     61568 get_next_file_rr: 0x7efe947b7510
file     61568 get_next_file: 0x7efe947b7510 [fiotestrmme]
file     61568 get file fiotestrmme, ref=1
io       61568 fill_io_u: io_u 0x2fff9c0: off=4096/len=4096/ddir=1io       61568 /fiotestrmmeio       61568 
io       61568 prep: io_u 0x2fff9c0: off=4096/len=4096/ddir=1io       61568 /fiotestrmmeio       61568 
io       61568 queue: io_u 0x2fff9c0: off=4096/len=4096/ddir=1io       61568 /fiotestrmmeio       61568 
io       61568 io complete: io_u 0x2fff9c0: off=4096/len=4096/ddir=1io       61568 /fiotestrmmeio       61568 
file     61568 put file fiotestrmme, ref=2
[...]
```

**Comment by aspandey** [comment]
OK. So we just did "yum install fio" and thought this would be the latest version of fio. 

We will again check it with latest version you have mentioned "fio-2.20-8-gdbf2-dirty" and will let you know our findings. In case you want us to try any other version of fio , please let us know.

**Comment by sitsofe** [comment]
@aspandey 2.20 should be fine if you don't want the very latest version out of git. I think the key points are:
1. Can you make this happen on a local filesystem?
2. Can you make this happen when size is small?
3. Does fio's debug agree that the it is sending down a small amount of data?
4. Ensure the command line you are sending us is the exact same one (job files and all) as the one being run and include the contents of any fio job files that may contain extra parameters.

**Comment by sitsofe** [comment]
I forgot one more:

5. Include the full output that fio produces on the non-debug fio runs.

**Comment by sitsofe** [comment]
@nixpanic can you provide any extra information on what you were running?

**Comment by nixpanic** [comment]
The details that I have seen are from a fio run whith directio and non-existing (to be created) or too small (need to be extended) files. The `job.ini` that made it reproducible for me (fio cloned from git on 2017-05-08), looked like this:
```
[global]
rw=write
fsync_on_close=1
size=4g
bs=64k
openfiles=1
startdelay=0
ioengine=sync
direct=1
[write]
directory=/gluster-mount
nrfiles=1
filename_format=f.$jobnum.$filenum
numjobs=8
```
I did run this on a system mounting an NFSv3 export, ust a single fio process.

The problem was reported with Gluster/NFS, but any (v3?) NFS-server should behave the same here (it only received the 1-byte writes over the network). More details are in the [original bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1428687). As Jens pointed out, I'm not sure why these 1-byte writes are accepted when `O_DIRECT` is enabled, they are surely not aligned (last byte of a page)... [guessing] Maybe because the `offset > EOF` condition?

So, [my conclusion](https://bugzilla.redhat.com/show_bug.cgi?id=1428687#c16) was that the `fallocate()` in fio might need a fall-back or alternative allocation strategy in case `fallocate()` is not supported on the filesystem (like NFSv3).

**Comment by sitsofe** [comment]
Hmm. Looking at the strace output doing I/O to an NFS mount I see that the layout phase seems to be doing:
```
[pid 13493] pwrite64(3, "\0", 1, 4095)  = 1
[pid 13493] pwrite64(3, "\0", 1, 8191)  = 1
[pid 13493] pwrite64(3, "\0", 1, 12287) = 1
[pid 13493] pwrite64(3, "\0", 1, 16383) = 1
```

but when it comes to time to actually do I/O I see this:
```
[pid 13495] fadvise64(3, 0, 131072, POSIX_FADV_DONTNEED) = 0
[pid 13495] fadvise64(3, 0, 131072, POSIX_FADV_SEQUENTIAL) = 0
[pid 13495] clock_gettime(CLOCK_MONOTONIC_RAW, {1605, 158116800}) = 0
[pid 13495] clock_gettime(CLOCK_MONOTONIC_RAW, {1605, 158159600}) = 0
[pid 13495] clock_gettime(CLOCK_MONOTONIC_RAW, {1605, 158222300}) = 0
[pid 13495] write(3, "\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252"..., 65536) = 65536
[pid 13495] clock_gettime(CLOCK_MONOTONIC_RAW, {1605, 159274500}) = 0
[pid 13495] clock_gettime(CLOCK_MONOTONIC_RAW, {1605, 159382700}) = 0
[pid 13495] clock_gettime(CLOCK_MONOTONIC_RAW, {1605, 159461500}) = 0
[pid 13495] clock_gettime(CLOCK_MONOTONIC_RAW, {1605, 159536200}) = 0
[pid 13495] clock_gettime(CLOCK_MONOTONIC_RAW, {1605, 159608200}) = 0
[pid 13495] write(3, "\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252"..., 65536) = 65536
```

@nixpanic are you sure you weren't being bamboozled by the layout pwrites rather than the actual job writes?

**Comment by sitsofe** [comment]
@aspandey OK one more question: when the files don't initially exist, if you use `--buffer_pattern=0xaaaaaaaa --fallocate=none` do they only contain 'a's when you look at them with hexdump? Are speeds still slow?

**Comment by sitsofe** [comment]
The plot thickens! If `posix_fallocate` is used glibc will quitely emulate `fallocate` if it finds it it is not supported: https://www.gnu.org/software/libc/manual/html_node/Storage-Allocation.html#index-posix_005ffallocate . Guess what is happening when fio goes to create a new file on NFS? That's why `--fallocate=none` is making the mysterious `pwrite64`s go away...

**Comment by axboe** [comment]
Yes, that's why I initially suggested trying with fallocate=none, since glibc will manually fill data if the fs doesn't support it.

**Comment by nixpanic** [comment]
On Thu, Jun 01, 2017 at 02:55:28PM -0700, Sitsofe Wheeler wrote:
> @nixpanic are you sure you weren't being bamboozled by the layout
> pwrites rather than the actual job writes?

Right, I most likely was! Because this caused the problem on the Gluster
side, I did not verify if it ever passed the layout stage.

The `--fallocate=none` option should be good as explained in other
comments. But maybe an error (or fallback?) should be given when
`fallocate()` fails? That would help other users that run into the same
problematic behaviour.

Thanks!

**Comment by axboe** [comment]
fallocate() isn't failing, that's part of the issue. For some versions of glibc, if fallocate() isn't available, it'll write the file itself. Which is a problem for two reasons, at least:

1) If fallocate() is available, we'll just get the meta data written so that the extents are directly available. We don't actually need the data written.
2) Apparently the fill is suboptimal, I'd even say buggy. If we end up doing small writes, well than that truly sucks.

Not sure how we can improve on this, to be honest. There's no good way to detect if fallocate() is available directly, or just emulated by glibc.

**Comment by axboe** [comment]
The problem is that we're defaulting to posix_fallocate(). We can avoid this mess if we just do fallocate(), and fall back to manual layout if we get EOPNOTSUPP. At least with the manual layout, we still get optimal writes, and not the stupid behavior of posix_fallocate().

**Comment by nixpanic** [comment]
Ok, is doing a manual layout in the case fallocate() returns EOPNOTSUPP an acceptable approach? If so, one of us should be able to send a patch for that.

**Comment by axboe** [comment]
It's either that, or not laying it out at all. I think it's acceptable, it should be a full speed layout and not silly 1 byte writes. The layout will default to the maximum write block size that the user has specified, basically the same that will happen if you do fallocate=none and fio needs to lay out a file.

**Comment by sitsofe** [comment]
The sad thing is I don't think there is anything easily portable. Is the suggestion to add a fallocate=native that checks for EOPNOTSUPP, prints a warning if it fails and exits if fio is in fatal warnings mode fails otherwise doing the manual layout the same way fallocate=none does?

Even if this were added I don't think it could be the default on any platform that doesn't expose a native fallocate...

**Comment by sitsofe** [comment]
I've got an experimental branch that uses a the native `fallocate` and defaults to "continue" mode if it fails: https://github.com/sitsofe/fio/tree/fallocate_native . Does this seem along the right lines?

**Comment by axboe** [comment]
Hmm, it's a tough one. I'm leaning towards always using the native, and if that fails with ENOSYS _and_ the option hasn't been explicitly set to "posix", then we just don't do fallocate. We know that if the native one isn't available, we are going to fall back to the horrible glibc version which writes the whole file. That's not the intent of it for fio, we're much better off laying out the file ourselves at that point.

You can use fio_option_is_set() to explicitly check whether an option has been set, or if it's unset (or just using the default value). It'll only return true if the user specified this option.

**Comment by sitsofe** [comment]
@axboe OK that's more subtle. Is this a correct interpretation of what you're asking for:

If the user is on default options and has a native fallocate:

1. Try doing a native fallocate first. If that fails with ENOSYS don't do the fallocate and continue on. If it fails with anything else throw an error and quit?

If the user sets "posix" and has a native and posix fallocate:

2. Try doing a native fallocate first? If that fails try a posix fallocate. If that fails throw an error and quit?

If the user sets "posix" and does **not** have a native fallocate:

3. Try a posix fallocate. If that fails throw an error and quit?

If the user is on default options and does **not** have a native fallocate (even if they have a posix fallocate):

4. Don't attempt fallocate.

In the above a posix fallocate will never be a default - it can only be explicitly asked for.

I guess 1. is a very strict reading of what you're suggesting. Perhaps the following would be enough:

5. Try doing a native fallocate first. If that fails for any reason print a warning and continue on.

Perhaps for 2. it's also enough to go straight to a posix fallocate (perhaps it has different semantics etc)?

**Comment by axboe** [comment]
I think we basically want what we have now, but with the exception of always using the native fallocate() unless "posix" has been explicitly set. For all cases we'll be using the native fallocate, and only error out if:

a) the option has been set
b) or the native fails with something other than ENOSYS.

Does that make more sense? I don't want to make it too tricky.

**Comment by sitsofe** [comment]
@axboe OK I understand what you're asking for - thanks for taking the time to re-explain this!

**Comment by sitsofe** [comment]
@axboe I've updated my test commit. Does this look closer to what you're asking for?

**Comment by sitsofe** [comment]
A quick summary: I've added a fallocate=try mode. This is the default if you have a native or posix fallocate. Try mode only uses a native fallocate if it's implemented otherwise it does nothing. It will error if a native fallocate that IS implemented fails for any reason and this patch works around some nastiness found in an old glibc where errno was not being set.

**Comment by axboe** [comment]
Yes, that looks better. A few changes I'd make:

1) Should not need to clear errno
2) Move the fallocate switch/code into a helper, instead of inlining in extend_file()
3) Check if we need all that debug info
4) Do we really need "try" as an option? I'm having a hard time thinking of a case where failure to fallocate() is fatal. If some fatal condition does exist, then we'll catch it when we start the job. Hence I'd be inclined to leave "posix" as the default, and have the 'try' behavior for that. We should only be using posix_fallocate() is the user really specified "posix". Maybe even change the default to native, if we make that change that none of them are fatal. By all means print an error, but don't abort a run because of it.

**Comment by axboe** [comment]
I pushed a change to move it out, that will make your job a bit easier.

**Comment by sitsofe** [comment]
@axboe OK I've rebased atop of your change and included your suggestions. Nearly there?

**Comment by axboe** [comment]
I think so. You need to rewrite the changelog since you got rid of the TRY mode.

**Comment by sitsofe** [comment]
OK I've submitted a pull request for this...

**Comment by nixpanic** [comment]
Many thanks guys! 👍
