### ISSUE TITLE
FIO issues just one command at a time (even when iodepth is 8) when asked to read from the same 4kb area of the device

### ISSUE THREAD

**Issue by ratnadeep-joshi** [axboe/fio#384]
This is with libaio and direct=1
For (iodepth=8,bs=4k,offset=0,filesize=4k,size=100mb), FIO just issues one command at a time

How do I ask FIO to issue multiple 4k read or write commands to the same 4k range of the device?

**Comment by axboe** [comment]
See the iodepth submit batch option. This is documented.

**Comment by ratnadeep-joshi** [comment]
Thanks for the quick response. I had checked it and its default value is same as iodepth (which is 8).
iodepth_batch=int
Number of I/Os to submit at once. Default: iodepth.

So, why FIO is issuing 1 I/O at a time when both iodepth and iodepth_batch are 8? Am I missing something?

**Comment by axboe** [comment]
Where are you reading that? I checked the man page and HOWTO, and both state it defaults to 1. The online help also says:

./fio --cmdhelp=iodepth_batch
       iodepth_batch: Number of IO buffers to submit in one go
               alias: iodepth_batch_submit
                type: integer value (opt=100)
             default: 1
               range: min=0, max=-1

Are you using an ancient version of fio? If so, upgrade first.

**Comment by sitsofe** [comment]
@ratnadeep-joshi it would have helped if you included the full version of fio you are running, the full command line you're using along with the full output that you see (see https://github.com/axboe/fio/blob/fio-2.20/REPORTING-BUGS )...

Most fio jobs respect `size` (or `filesize`) when it comes to working out when a "loop" has been completed. Since your `filesize` is the the same as your `bs` I'm guessing a loop can only consist of one I/O and because you only have to do one I/O per loop that's all you'll achieve in terms of depth. I'm going to use a different way of "running on the spot" (courtesy of seeking) but can you say how the following perform?

```
./fio --stonewall --ioengine=libaio --direct=1 --filename=/tmp/fiofile2 \
    --iodepth=16 --io_size=100M --bs=4k --rw=read:-4k \
    --name=rereadsize4k --size=4k \
    --name=rereadsize8k --size=8k \
    --name=rereadsize1M --size=1M
```

You can see the above uses [`io_size`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-io-size)  to try and decouple the amount of I/O to be done from the region but I'm guessing `size` still has an effect.

Another approach is to try and escape the binds of a loop by using a [`time_based`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-time-based) job:
```
./fio --ioengine=libaio --direct=1 --filename=/tmp/fiofile2 --iodepth=16 \
    --bs=4k --rw=read --time_based=1 --runtime=5s \
    --name=reread --size=4k
```

Again, can you tell us how that performs?

Obviously if you only ever want to submit exact batches of 16 (rather than between 1-16) you should add the [`iodepth_batch`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-iodepth-batch-submit) option as Jens suggested.

**Comment by ratnadeep-joshi** [comment]
Thanks axboe and sitsofe for the responses. I will check this and come back with queries, if any.

**Comment by sitsofe** [comment]
@ratnadeep-joshi Come back! :-) Before you go, can you let us know if the posted examples show a difference?
