### ISSUE TITLE
[Fio Feature Request]: Mix Seq/Rnd option with rate control 

### ISSUE THREAD

**Issue by akoundal** [axboe/fio#403]
This is to request a feature where user can generate a mixed workload of SEQ+RND with rate control for each. 
Traditionally it has been either SEQ only or RND only 
I have used flow option to get the mixed seq/rnd behavior but it will be nice to have option like "rwmix"
Currently using the flow user cant control the **rate** of e.g. Write or Read. The rate gets globally applied. 

e.g. SEQ_WR 80% , RND_RD 20% but SEQ_WR needs to be capped at x rate. 
Please close if this request sounds irrelevant.

**Comment by sitsofe** [comment]
> Currently using the flow user cant control the rate of e.g. Write or Read. The rate gets globally applied.

@akoundal I'm not sure I understand what you mean when you say "globally applied". Here's an example job:

```
$ fio --size=10M --ioengine=null --time_based --runtime=10s --name=SEQ_WR --rw=write --flow=-1 --rate=10M --name=RND_RD --rw=randread --flow=4 --rate=100M
[...]
Jobs: 2 (f=2), 0B/s-110MiB/s: [W(1),r(1)][81.8%][r=2558KiB/s,w=9.00MiB/s][r=639,w=2559 IOPS][eta 00m:02s]
[...]
SEQ_WR: (groupid=0, jobs=1): err= 0: pid=24779: Thu Jul 13 06:36:38 2017
  write: IOPS=2559, BW=9.00MiB/s (10.5MB/s)(100MiB/10001msec)
[...]
RND_RD: (groupid=0, jobs=1): err= 0: pid=24780: Thu Jul 13 06:36:38 2017
   read: IOPS=665, BW=2663KiB/s (2726kB/s)(26.0MiB/10001msec)
```

fio is saying the user has set a maximum combined rate cap of 110MiB/s and I don't see the rate being applied "globally" but I do see the rate of the slowest piece impacting the one the job that wanted to be faster in this particular example (look at BW= to see the bandwidth achieved). You have multiple constraints so what is going to happen when they combine?

Let's say you want SEQ_WR 80% rate of 10MBytes/s, RND_RD 20% rate of 100MBytes/s. The RND_RDs are going to want to go faster but for every one that issued you are eventually going to **have** to wait for **4** SEQ_WR I/Os to be issued and they are being issued slower than the RND_RD  issue rate. Because you have to maintain the proportion between the different types of I/O the rate of the RND_RD I/Os is essentially capped to at most 25% of the rate of the SEQ_WR I/Os. How do you envision solving this to allow independent rates?

**Comment by akoundal** [comment]
@sitsofe  Thanks for the detail information. One thing that i have not tried is to give the rate option to both the threads, let me try that out and see if that makes a different. Below is what i tried when i filed the request. Such that it will 4:1 (i.e 4times SEQ_WR vs RND_RD).
[SEQ_WR] 
stonewall
rate=x 
flow=-1 
[RND_RD]
flow=4

**Comment by sitsofe** [comment]
@akoundal after the discussion which led to http://www.spinics.net/lists/fio/msg06053.html (where there were recommendations not to use flow) do you feel this is still an issue?

**Comment by sitsofe** [comment]
@akoundal can this issue be closed?

**Comment by akoundal** [comment]
@sitsofe yes, this is good to be closed and not to use the flow with the capping b/w :). 
Thx for all the support and feedback
