### ISSUE TITLE
crc32c: verify failed at file /dev/nvme0n1 (related MDTS)

### ISSUE THREAD

**Issue by dlroxor** [axboe/fio#411]
Hello,
Currently I found interesting error report regaring verify=crc32c option with NVME SSD.

Here is the FIO parameters.
[global]
group_reporting
buffered=0
direct=1
ioengine=libaio
overwrite=1
verify=crc32c
verify_backlog=1m
verify_dump=1
continue_on_error=verify
time_based
runtime=12h

[nvme1n1-write]
new_group
norandommap
do_verify=1
rw=randrw
rwmixwrite=100
bs=512k
iodepth=32
numjobs=1
filename=/dev/nvme1n1
size=10m
offset=0

[nvme1n1-read]
new_group
norandommap
do_verify=0
rw=randrw
rwmixwrite=0
bs=16k
numjobs=4
iodepth=32
filename=/dev/nvme1n1
size=10m
offset=0

Error Message:
crc32c: verify failed at file /dev/nvme1n1 offset 4194304, length 524288PS][eta 11h:59m:15s] 
       Expected CRC: 4318f333
       Received CRC: ab2810b6
       received data dumped as nvme1n1.4194304.received
       expected data dumped as nvme1n1.4194304.expected

When I check the dump, data corruption srarted from 0x40000 (256KB)
The interesting thing is this nvme SSD has 256KB MDTS(Max Data Transfer Size)

So I test another nvme SSD which has 128KB MDTS
Then data corruption started from 0x60000(386KB)
If I use MDTS 512KB SSD, then there is no problem. (note. the write job bs=512k)
So I think linux kernel(nvme driver) transfer the I/O using MDTS but FIO doesnot consider this.
It happens only using verify=crc , if I use verify=pattern, there is no problem.
I thnk this problem appears from fio 2.1.3 to 2.99
Could you please look into this issue?

**Comment by sitsofe** [comment]
@dlroxor Your first job (nvme1n1-write) writes (and verifies) blocks in sizes of 512k, your second job (nvme1n1-read) will try and immediately verify using a block size of 16k (see http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-verify for a description of this behaviour with pure reads). This can't end well...

You are running these jobs **simultaneously** against the same disk so the verifying reads are racing against the write job!  This can't end well either...

You are using runtime with your initial writes job. This may cause another issue i the future because a later job doesn't know how far the first job got without help (did it write half all the disk? Did it write it two and half times before getting stopped so you have to know that not all the data from the first pass is there etc.) and so will most likely mismatch...

I'm not sure verify_backlog takes the units you think it does. I'd read http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-verify-backlog and check the final sentence.

I'm afraid it's unclear what you're trying to achieve and your jobs seem to have many conflicting options in them. As such I doubt there is an fio bug so I won't follow up further here. Perhaps you would be better off closing this issue and asking for help on the fio mailing list: https://github.com/axboe/fio/blob/fio-2.99/README#L58 ?

**Comment by sitsofe** [comment]
@dlroxor Could you close the issue here and try clarifying the issues you're seeing via the fio mailing list?
