### ISSUE TITLE
fio: mutex.c:23: fio_mutex_remove: Assertion `mutex->magic == 0x4d555445U' failed.

### ISSUE THREAD

**Issue by grinapo** [axboe/fio#437]
Any idea why this may have happening? 
As a stress-test plenty of fio's running within lxc containers, and most of them result this before crashing with sig11 (while running for a looooong time).

**Comment by axboe** [comment]
Hard to help, when you don't say

1) What job you are running
2) What version of fio you are running

It's like calling the mechanic and saying "my car stopped running, what's wrong?" and expect him to figure it out with no more info than that.

**Comment by axboe** [comment]
If I crystall ball it, then my guess would be that you are running an older version that doesn't include:

```
commit 5ba01402d96e113ac451441f45d0c8b4dd281f4d
Author: Jens Axboe <axboe@fb.com>
Date:   Mon Apr 3 08:46:34 2017 -0600

    backend: move freeing of td->mutex to main thread
```

If so, upgrade to 3.0 and see if it works for you.

**Comment by sitsofe** [comment]
@grinapo as Jens said we really need at least the information in https://github.com/axboe/fio/blob/fio-3.0/REPORTING-BUGS to be added here to even make a start on your issue (unless Jens' crystal-ball/psychic debugging turns out be correct).

**Comment by grinapo** [comment]
My deepest and sincerest apologies, Lords!

Indeed, I have been sinned. The version was the one in Debian/jessie, which happens to be 2.1.11. To be honest, despite all my evil intents Jens still laughed into my face and guessed the problem just right, so I have to work very hard to be able to ask a trick question of him, ever again, which I wouldn't dare anyway.

Since Debian/strech (which happens to be the current stable) still contains 2.16 I have to work pretty hard to reach the required level of "not lame bug reporter". It's so far away! 

Forever yours truly.

**Comment by sitsofe** [comment]
> My deepest and sincerest apologies, Lords!
>
> Indeed, I have been sinned. [...]

@grinapo Heh!

For what it's worth, I don't think Jens was trying to put the smackdown(?) (I'm non-American and far from hip so I can only hope that word means what I guess it might) on you but probably desired to spend a short amount of time saying why your issue was difficult to solve and then taking a guess at where the problem may lie. However, let me use this opportunity to try and reply to your comment in an all too serious manner:

Distributions regularly carry "out of date" binary versions of software and it's just the way that many LInux binary distributions have been traditionally been engineered due to requirements for stability coupled with pressures on time (especially for non-core software or people to perform the  packaging). Sometimes this works great and sometimes the outcome is, well, less great. An [example of where this distro packaging process broke down was the Debian packaging for ownCloud](https://lwn.net/Articles/670566/).

More recently there are a number of discussion about the role of Linux distribution packaging (https://lwn.net/Articles/712318/ , https://lwn.net/Articles/730630/ ) and we are seeing reactions such as docker, Flatpack, Snappy and AppImage as another means of creating binary packages for Linux distribution that are not under distribution control. Time will tell how these new efforts pan out but for now it's not uncommon for users to be drawn to out of date packages.

fio is also a volunteer effort and there a limits on what you can expect from people working in their free time. I would like you to read [Consider the maintainer](https://lwn.net/Articles/712215/) and ask yourself "if I were looking at issues unpaid how might I react?" and ask yourself would you ever respond in a similar fashion to how Jens did? I personally do sporadic work for the project but there are more users and [issues](https://github.com/axboe/fio/issues) than man power to address them. C'est la vie.

BTW you aren't alone in pointing out distributions carry old versions of fio. See this fio bug report where a [user is frustrated about an out of date fio package in RHEL](https://github.com/axboe/fio/issues/256#issuecomment-255342094) and says someone should sort it out (there's a small problem of time). Here's another [bug report where the user notes they are on an old version of fio](https://github.com/axboe/fio/issues/427#issuecomment-323422270).

Ultimately there is a tension between "latest and greatest" and "actively supported". The fio project is too small create binary packages for end users. It is also too small to maintain stable long lived branches. As such the project has chosen to address bugs by only fixing them in the master branch. Consequently, if you are not running the latest master there's a chance that you may find your bug has already been fixed :-). As one of the other [bug reporters found the fio build process is not /too/ difficult ](https://github.com/axboe/fio/issues/427#issuecomment-323512138)(see https://github.com/axboe/fio/blob/fio-3.0/README#L130 for some brief instructions) as the number of dependencies is fairly low. If you've never tried it, give it a go - you might be pleasantly surprised or find another bug that you can safely report '-)

**Comment by grinapo** [comment]
@sitsofe I try strongly reject my habit to spill tons of text here, so I may sound brief. 

Thanks for your all too serious reply, I **honestly** thank the friendly reactions and the resolution. 

I forgot to mention that one reason behind actually opening an issue was that google found zero useful solutions, or even the possibility of the problem, and now it's indexed and searchable. Helping others. (As for specific questions about the tests: there is almost every kind of aio test running in those lxc containers I have mentioned, with wildly varying parameters. As a sidenote, upgrding to 2.16 seem to have resolved mutex errors.)

Am am familar with the topic since I've been a Debian maintainer myself. I just reply (and please understand that _this is not about smaller projects_ like fio) because there's this: lots of projects actually maintain their own packages, some of them actually by asking Debian maintainers (or ex maints) to do it (off Debian), some do maintain their own packages inside Debian. This probably the surest and fastest way to keep distro packages up to date. 

The reason behind that is that lots of packages require lots of fiddling, mostly patching bugs upstream hesitate or reject to apply, some of them only affecting small percent of the userbase. Pulling these through new versions consumes time of volunteers. Sometimes new packages depend on libs not yet packaged, or clashing with other parts of the distro (this been the case with some of digikam parts which required 18+ months to be included due to library incompatibilities, and Debian version is seriously out of date due to the uncompilability of the new version within the environment).

Sometimes I package things but only when they're "not too difficult", which means they use autotools or reasonably self-contained builds, since I do not have the time to fiddle with the build and dependency mess some people accumulate. 

In case of **fio** the current maintainer explicitely stated that he's [willing](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=869686#10) to accept outside help, I will check how fio does help me doing that.

But all of this is just explaining from me. The process mainly works. In case of fio I'll see whether I can help. Honestly, I never have had any problem with it, and it's an extremely useful thing to have. Again, thanks for all the help and replies. This text is longer than I have would desired. ;-)

**Comment by grinapo** [comment]
[Packaged 3.00 just fine and sent to the maintainer. Some minor patches are still pending, shall I open an issue?]

**Comment by sitsofe** [comment]
@grinapo I did notice Martin was snowed under in that bug report when I looked a few weeks ago so it's great you've tried to help out!

Re minor patches - yes please (can't promise when they'll be actioned but it's nearly always worth trying). The only one that I'm aware of already from Debian that hasn't gone anywhere is https://github.com/axboe/fio/pull/182 which is to do with inserting build flags.

**Comment by sitsofe** [comment]
@grinapo forgot to say that a reproducible build patch has been added (see https://github.com/axboe/fio/commit/785e49c659023df1735bff195ad4ba133ebd23a7 ).

**Comment by axboe** [comment]
Wow, that's a lot of text! For what it's worth, my initial reply was not a smack down. If it was, then neither of you would have been in doubt if that was the case or not :-)

We don't do stable branches since releases are supposed to be stable. I try pretty hard to ensure that we don't introduce regressions, which is the best way to move forward. In that regard, my model tries to follow the same that I use on the Linux kernel side. Stable branches tend to get stagnant and cause users to continue using an older version, where as I would much rather push users towards the latest and greatest instead. Otherwise you end up with the master branch and new features being unused, and you don't get the critical feedback you need to move the project forward in a sensible manner.

So I'd very much encourage some activity around pushing vendors to upgrade their packages.

**Comment by axboe** [comment]
> So I'd very much encourage some activity around pushing vendors to upgrade their packages.

To that end, if distros are carrying patches that make upgrading difficult, we should work on getting them integrated and easing the workflow for them.

**Comment by sitsofe** [comment]
A modified fio2gnuplot-manpage fix went in as https://github.com/axboe/fio/commit/aed4796b989d3b33f86fb3be6b915e532df2d59d .

**Comment by sitsofe** [comment]
While I'm here I will also note that some dedicated soul has created the [Repology site](https://repology.org/) that tracks packages across multiple package systems. Here's the entry for for fio - https://repology.org/metapackage/fio/versions .
