### ISSUE TITLE
More documentation for esx compiling needed

### ISSUE THREAD

**Issue by rustyscottweber** [axboe/fio#464]
I attempted to use the "--esx" parameter for the configure script as those are the instructions for compiling for esx.  However, I can't seem to find a scenario or combination of parameters which work to compile fio on ESX.  Is there a more comprehensive set of instructions that one can use to compile fio for esx?  Is this committed to a help file somewhere?

**Comment by sitsofe** [comment]
@rustyscottweber I've managed to compile fio for ESXi 6.0 but finding an appropriate environment to do so in was a pain because I was looking for a distro with a glibc that was 2.12 or older. I didn't see comprehensive instructions anywhere but here's roughly what I did:

1. Boot 64 bit CentOS 6 (I happened to use a LiveCD but that was also something of a pain to find).
2. Use sudo yum to install a compiler, make, git, zlib-devel etc.
3. Run
```
git clone --depth 25 https://github.com/axboe/fio/
cd fio
./configure --esx
make
```
4. Copy binary to ESXi 6.0 host.
5. Run
```
./fio --size=16k --filename=/tmp/fiofile --name=esxtest
```

(An attempt to use Ubuntu 16.04 and a statically linked fio fell flat - running the created fio on the ESXi 6.0 box crashed with "Segmentation fault" even though that same fio binary worked on the CentOS 6 box!)

**Comment by sitsofe** [comment]
For anyone wondering why it was a distro with glibc 2.12 or earlier that I was interested in finding it is because that is the version of glibc returned in the Linux component of ESXi when I ran /lib/libc.so.6 .

@rustyscottweber did the above instructions help? If so could you close this issue? Thanks!

**Comment by sitsofe** [comment]
@rustyscottweber - any update on this?

**Comment by rustyscottweber** [comment]
I have a VM which I will use to check compilation.  However, I have not yet had time to check this as other projects have kept me occupied.

**Comment by sitsofe** [comment]
@rustyscottweber As there are some steps here and this isn't really a bug in fio per se (as VMware should really specify how you build software for their platform) could you close this issue for now?

**Comment by rustyscottweber** [comment]
Sure.. If I can't get it to work, I'll open a ticket with vmware.

**Comment by markbeierl** [comment]
Here is a dockerfile that I used to build FIO and run on ESXi 6.5.
```
FROM multiarch/alpine:x86_64-v3.6
RUN apk --no-cache add --update \
    git \
    alpine-sdk \
    coreutils \
    linux-headers \
    libaio \
    libaio-dev \
    zlib-dev

RUN git config --global http.sslVerify false
RUN git clone http://git.kernel.dk/fio.git fio
RUN cd fio && ./configure --esx
RUN cd fio && EXTFLAGS="-static" make -j $(grep -c ^processor /proc/cpuinfo) install
```

Build it and use docker cp to pull the FIO binary out of the container.

```
docker build . -t fio
docker run -d fio sleep 600
docker cp 69e64de38659d350fb07e45b5d7d2d4098c642ec1ca81a6eb18a9b34e622082f:/fio/fio .
```

SCP the file over to ESXi and run as normal.

**Comment by rustyscottweber** [comment]
Getting back into this as time allows.
@markbeierl 
I tried this for esx 6.7 with unsuccessful results.
```
[root@r3i1:/tmp] ./fio --help
Illegal instruction

```
Contacting esxi for support on something like this is a joke.. They don't care unless you are a paying customer. I am just the guy who has to qualify hardware and make sure it runs on ESXI... I guess they don't understand that they lose when I can't get my work done.. :(
Maybe I'll try once more.

**Comment by Have-a-question-about-this-project** [comment]
I've attached fio I built against glibc-2.29 linux-4.4.171 libaio_0.3.107 zlib-1.2.8 with gcc-8.2.0 and binutils-2.30
It not perfect, it shouts about "cs: bug in atomic sequence!" a lot when you start it, but it runs ok with a command line like:
`fio --filename=/vmfs/devices/disks/t10.NVMe____Samsung_SSD_970_PRO_512GB_______________2106B09157382500 --name=test --bs=4k --size=100G  --readwrite=randread
--iodepth=32  --direct=1
`
[fio.gz](https://github.com/axboe/fio/files/3819355/fio.gz)

**Comment by thekoma** [comment]
For 6.7  the configure changes slightly.
```Dockerfile 
FROM multiarch/alpine:x86_64-v3.6

RUN apk --no-cache add --update \
    git \
    alpine-sdk \
    coreutils \
    linux-headers \
    libaio \
    libaio-dev \
    zlib-dev

RUN git config --global http.sslVerify false
RUN git clone http://git.kernel.dk/fio.git fio
RUN cd fio && ./configure --esx --disable-numa --build-static
RUN cd fio && EXTFLAGS="-static" make -j $(grep -c ^processor /proc/cpuinfo) install
```
