### ISSUE TITLE
Is it valid to set direct=0 when using libaio?

### ISSUE THREAD

**Issue by renzhengeek** [axboe/fio#512]
Hello,

In example job (fio/examples/fio-seq-read.job), it has the following settings:
```
[global]
direct=0
...
[file1]
ioengine=libaio
```

However,  `man fio`  says about libaio as below:

```
 libaio Linux native asynchronous I/O. Note that Linux may  only  support  queued  behavior  with  non-buffered  I/O  (set `direct=1' or `buffered=0').  This engine defines engine specific options.
```

So, I'm confused:

1. Is it valid to set direct=0 when using libaio?
I tested DM raid5 device with this job. The seq read performance with "direct=1" is much better than "direct=0". So, I'm asking this question :)

2. what does "queued" behavior mean in the man doc?

Thanks for your time!

**Comment by renzhengeek** [comment]
@Venutiwa , hello, could you please shed some light on this issue? Thanks in advance.

**Comment by sitsofe** [comment]
@renzhengeek 
> 1. Is it valid to set direct=0 when using libaio

You can do it but I wouldn't recommend it. With today's Linux kernels the I/O is submission is likely to become blocking (and thus no longer asynchronous) which can limit the amount of parallel I/O achieved. There's a strong argument that fio examples should NOT encourage that such a combination of options...

> 2. what does "queued" behavior mean in the man doc?

If you mean the sentence "Note that Linux may only support queued behavior with non-buffered I/O" (over in http://fio.readthedocs.io/en/latest/fio_doc.html#i-o-engine ) I think it's trying to say:

"Rather than blocking on the submission syscall until the I/O has gone down AND come back from the lowest disk device (blocking behaviour), when using direct=1 with libaio you can submit an I/O and have it queued by the kernel allowing the submission syscall to return straight away and opening the opportunity for you to queue other submissions before the I/O completes".

**Comment by renzhengeek** [comment]
@sitsofe Hi, very clear explanations to me. Thanks very much.

I will leave this issue open in case someone wants to update the fio example job (fio/examples/fio-seq-read.job).

**Comment by axboe** [comment]
Fio used to warn if you used libaio/direct=0, but that was removed about 10 years ago or so when I hacked up some patches for libaio to support async buffered IO. That never went anywhere, and now in 2018, libaio is still only async for O_DIRECT. 

I will update that job file, it's misleading.
