### ISSUE TITLE
Not all arguments can be placed in a jobfile

### ISSUE THREAD

**Issue by brycepg** [axboe/fio#517]
I've noticed that some arguments cannot be placed in the fio jobfile; some are cli-only.

Namely:

- `output-format`
- `output`
- `eta`
- `eta-newline`

Any chance fio can be changed to allow these into the jobfile?

**Comment by axboe** [comment]
That's by design, as some of these options are not per-job. I don't have any plans to change that, as it would create a situation where a per-job option would have impact wider than that, which would be confusing. That is why they are command line only. Even in a global section it would be problematic, if you use multiple job files at once.

**Comment by brycepg** [comment]
That makes sense when thinking about multiple job files. Thanks for the quick response
