### ISSUE TITLE
CLOCK_MONOTONIC_RAW slows IO in certain cases

### ISSUE THREAD

**Issue by Seth5141** [axboe/fio#533]
I ran into this issue while performing bench-marking in a virtual machine and saw a sharp (~25%) decrease in the iops between fio-2.1.10 and fio-3.3 on the same benchmark.

I was able to whittle the issue down to the patch c544f6047b8b6f238a (gettime: add support for CLOCK_MONOTONIC_RAW). I was able to confirm that this was in fact the reason for the disparity by removing the check for clock_monotonic_raw from fio-3.3 and running the benchmark again.

I then confirmed that clock_monotonic_raw seemed to be slowing the io path by supplying "-cpu host,migratable=no,+invtsc" as part of my Qemu command line ensuring that the cpu would supply accurate clock cycles and fio would not fall back to the gettime path. The numbers I got from fio-3.3 using the cpu time stamp agreed almost exactly with the numbers I got from fio-2.1.10 which uses CLOCK_MONOTONIC.

My coworker @dverkamp-intel  and I were confused as to why there would be such a large difference in the reporting from CLOCK_MONOTONIC and CLOCK_MONOTONIC_RAW. He looked in the vDSO code for x86 and saw that CLOCK_MONOTONIC_RAW is not actually served through the vDSO, and when it is used, the system will have to resort to using a fallback system call. We believe the added overhead of system calls in this path may make CLOCK_MONOTONIC_RAW a less reliable source for bench-marking than CLOCK_MONOTONIC.

VM OS: CentOS 7
Kernel Version: 3.10.0-693.17.el7.x86_64

**Comment by sitsofe** [comment]
I was struggling to believe it but the whole "`CLOCK_MONOTONIC_RAW` is slower than `CLOCK_MONOTONIC` because it doesn't go through the vDSO" is seemingly a known thing:

* https://bert-hubert.blogspot.co.uk/2017/03/on-linux-vdso-and-clockgettime.html warns about this.
* The Java folks found it was slow over in https://bugs.openjdk.java.net/browse/JDK-8006942 .
* Netflix spotted in their "rend" tool over in https://github.com/Netflix/rend/issues/96#issuecomment-245816993 .

Looking around it seems that that recent Linux on ARM kernels have `CLOCK_MONOTONIC_RAW` in its VDSO but this doesn't apply to x86/x86_64. This means the other programs mentioned just use `CLOCK_MONOTONIC` and are done with it.

Perhaps fio can offer up a `CLOCK_MONOTONIC_RAW` choice if the user wishes to explicitly use it but it shouldn't be the default on Linux...

**Comment by sitsofe** [comment]
@Seth5141 Something that has just occurred to me - is it the case that your TSC is unreliable? fio should default to the CPU clock if all the following are true:
* The TSC doesn't change frequency with power states (i.e. is invariant)
* A multicpu clock test doesn't fail

`--cpuclock-test` may say more...

**Comment by Seth5141** [comment]
@sitsofe When I run --cpuclock-test on the host, it reports as reliable. As far as I know, the reason that fio was defaulting to the gettime() path in the guest is because qemu enables cpu migration by default. When I added "-cpu host,migratable=no,+invtsc" to my qemu parameters list, running --cpu-clocktest in the guest also reported a reliable tsc.

**Comment by sitsofe** [comment]
(A quick FYI: from the 5.3 Linux kernel onwards the disparity in the speeds of the calls was finally fixed (so calling `clock_gettime()` with `CLOCK_MONOTONIC_RAW` should be no slower to call than `CLOCK_MONOTONIC`). See ["[PATCH v7 00/25] Unify vDSOs across more architectures"](https://lore.kernel.org/linux-arm-kernel/20190621095252.32307-1-vincenzo.frascino@arm.com/ ) for details)

**Comment by Seth5141** [comment]
@sitsofe Thank you for posting that information. I'm going to close this if that's OK with you. I figure it will still show up for anyone who runs into a similar issue on kernels prior to 5.3
