### ISSUE TITLE
R/W/TRIM workload with Trimmed/ invalidated memory access restriction 

### ISSUE THREAD

**Issue by unitedRed** [axboe/fio#534]
I want to design a workload with R/ W/ Trim, with restricting read or write operation for trimmed or invalidated memory blocks. 
in other words If worker is issuing read, write and trim - mix workload, then I want to avoid reading or writing on trimmed memory locations. 

Can I do it using FIO  ?

**Comment by sitsofe** [comment]
@unitedRed 

fio currently can't do what you're asking because for starters there's no such thing as a "readwritetrim" I/O pattern (see http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-readwrite for the `rw` options). If you were to use two or more different simultaneous jobs it won't really help in your case because no job knows what the others have done to the disk.

Your workload is also unusual because as more time passes it will only be able to do trims to the disk so a mixed workload trying to maintain percentages of reads to writes to trims would eventually stop making sense.

As this is less of an issue an more of a question for the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.4/README#L58) you are probably better off closing this issue and taking further conversation there.

**Comment by unitedRed** [comment]
@sitsofe 
I do know there is no readwritetrim I/O pattern, but I was thinking to create a workload with read , write , trim like this, with ratio 75:24:1 ratio for read to write to Trim as,
bssplit=256k/75,256k/24,128k/1
[rand_read]
rw=read
[rand_wr]
rw=write
[trim]
rw=trim

As without norandommap option FIO does keep I/O history to cover every block, I was curious to know if FIO also keeps track of trim history. 

I do understand this is not an issue I will take my doubt to the mailing list, 

Thank you

**Comment by sitsofe** [comment]
@unitedRed you can try what you're proposing but as I said

> If you were to use two or more different simultaneous jobs it won't really help in your case because no job knows what the others have done to the disk

This is exactly the scenario you've constructed with your three jobs (rand_read, rand_wr, trim). The "rand_read" job has no way of knowing what the "trim" job has done therefore even if it wanted to it can't avoid the trimmed regions. Things like the randommap only work within a job - not across two different jobs.

(PS: don't forget to close the issue here on Github!)
