### ISSUE TITLE
regression in fio v3.5 vs v2.14

### ISSUE THREAD

**Issue by bengland2** [axboe/fio#540]
I got a report that fio v3.3 and fio v2.14 were giving different results, so I decided to check it out on my NVDIMM server, since that should expose any bottlenecks in fio.  So I did git clone of fio and built a v3.5 fio executable, then I build a v2.14 version with "git checkout tags/fio-2.14".   Then I run the same test repeatedly on both versions, and what I find is that fio v3.5, at 1145 MB/s, is 42.3% slower than v2.14 at 1992 MB/s, with a 1% deviation over 5 samples.  Ughh.  But there is no difference in throughput if I add the --direct=1 parameter; now both run at 1550 MB/s +- 1%.  If I run the test that shows the huge difference, but only run it for 10 seconds, no significant difference is observed then either.  Is it buffer cache hits?  Maybe fio v2.14 can keep up with cached reads, and fio v3.5 cannot?  This is a skylake processor, not slow.  Granted, this is a pretty nasty test with 4-KB I/O on a single thread for a very fast device.  But still, thought you'd want to know.  Can probably reproduce by just doing cached read tests.

Here's my repeat.sh script:
```
drop_cache() {
    sync 
    echo 1 > /proc/sys/vm/drop_caches 
}

run_test() {
    numactl -N 1 -p 1 -- \
        ./fio --name=ben --filename=/dev/pmem1 --bs=4k --size=30G \
              --time_based=1 --runtime=100 --rw=read  | \
        awk '/fio-/||/ read/'
}

for n in `seq 1 5` ; do 
    drop_cache
    pushd fio214/fio
    run_test
    drop_cache
    popd 
    pushd fio35/fio
    run_test
    popd
done
```

I used numa pinning because I didn't want unpredictable behavior based on which NUMA node happened to be running fio.

**Comment by sitsofe** [comment]
@bengland2 Sounds fairly bad. Any chance you can git bisect this one down? There have been loads of changes including the big nanosecond patches that landed in fio-3.0...

**Comment by bengland2** [comment]
agreed. bisection is next step.  Also it turns out Spectre/Meltdown CVE's were all enabled when I did these runs, am looking at what happens when I turn them off.  I understand that this is a tough workload for fio to do (3 usec per read) but at least we want fio to have stable results, even if it can get CPU bottlenecked in certain cases.

**Comment by bengland2** [comment]
With /sys/kernel/debug/x86/*_enabled = 0, the regression is bigger, ~54% +/- 1%.  Just wanted to be sure that it wasn't all caused by the CVE patches.    On Monday I'll do bisection.

**Comment by bengland2** [comment]
I think it's between fio-v3.1 and fio-v3.2, can reproduce using a 5-second test with this:

```
numactl -N 1 -p 1 -- \
$tree/fio/fio --name=ben --filename=/dev/pmem1 \
                   --rw=read --bs=4k --size=2G --time_based=1 --runtime=5  | \
 awk '/fio-/||/ read/'
```

fio-3.1    read: IOPS=813k, BW=3175MiB/s (3329MB/s)(15.5GiB/5000msec)
fio-3.2    read: IOPS=394k, BW=1540MiB/s (1615MB/s)(7701MiB/5000msec)
fio-3.1    read: IOPS=792k, BW=3095MiB/s (3246MB/s)(15.1GiB/5000msec)
fio-3.2    read: IOPS=399k, BW=1559MiB/s (1634MB/s)(7795MiB/5001msec)

**Comment by sitsofe** [comment]
Hmm the commit that stands out is this:

https://github.com/axboe/fio/commit/0bcf41cdc22dfee6b3f3b2ba9a533b4b103c70c2 ("io_u: re-invalidate cache when looping around without file open/close")...

**Comment by sitsofe** [comment]
(If it does turn out to be that I have to admit that I didn't know `BLKFLSBUF` in https://github.com/axboe/fio/blob/cd174b909109e527e41ca42ac761c5f7d29f25e5/os/os-linux.h#L143-L146 had the effect of also causing the cache to be dropped rather than just flushed but perhaps the clue is in the name of the function calling it).

**Comment by bengland2** [comment]
I did the classic git bisect on this problem and it actually is this commit above that you referenced.

commit 0bcf41cdc22dfee6b3f3b2ba9a533b4b103c70c2
    io_u: re-invalidate cache when looping around without file open/close
 
I then noticed that if I set --invalidate=0  , the "regression" disappears.  So this is really not a bug, it's just that the user has to be more aware of caching behavior when running --time_based=1 .  It's not enough to drop the cache, you have to set --invalidate=1 to force fio to keep dropping the cache on every pass through the file.

**Comment by sitsofe** [comment]
> it actually is this commit above that you referenced

All the clues seemed to fit (e.g. no speed difference with `direct=1` should have been a tip off to me but it was only when you gave a narrow range I was able to work it out by looking at the summaries).

> you have to set --invalidate=1 to force fio to keep dropping the cache on every pass through the file

`invalidate=1` is the default: http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-invalidate . The difference is that 0bcf41c changes fio to drop the cache at the start of every loop pass rather than just at the start of the first pass. Perhaps the help pages should document the per loop dropping behaviour?

Given the "effectiveness" of fio's cache dropping it looks like your `echo 1 > /proc/sys/vm/drop_caches` is unnecessary when `invalidate` isn't explicitly 0...

PS: fio can be built against libnuma to gain NUMA options: http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-numa-cpu-nodes .

**Comment by bengland2** [comment]
And I did build it against libnuma and WOW!  With NVDIMMs it's a huge speedup, I'll try to publish an article about it and post it but it's really important.  I configured the NVDIMMs according to [this article by Jeff Moyer](https://developers.redhat.com/blog/2016/12/05/configuring-and-using-persistent-memory-rhel-7-3/).
