### ISSUE TITLE
IO doesn't time out on failed writes.

### ISSUE THREAD

**Issue by rustyscottweber** [axboe/fio#550]
I've been having some problems testing a multi-path device.  On a staged failover, for a period of time, all IO's will fail while ALUA and multi-path decide which path to accomplish IO on.  Some times, the fail over fails to happen or it doesn't happen in a timely fashion.

Given the following job,  my assumption is that after 60 seconds the IO would time out and the job would fail (Maybe the assumption is incorrect).  Am I missing a parameter that would more appropriately deal with a device that might potentially be be completely failing because no paths to the device exist or taking too long to find the correct path?  Are there mechanisms for dealing with completely failed devices?
```

[global]
numjobs=1
thread=1
bs=64k
iodepth=128
direct=1
ioengine=sync
verify_fatal=1
verify_dump=1
verify=meta
verify_pattern=0xaa555aa5
verify_interval=512
time_based=1
runtime=3d
rw=write
verify_backlog=1
ioengine=posixaio
ramp_time=3
max_latency=60000000000
disable_lat=0
disable_clat=0
disable_slat=0
disable_bw_measurement=1

[mpatha1]
filename=/dev/mapper/mpatha1
```

**Comment by sitsofe** [comment]
@rustyscottweber it's not 100% clear where your issue lies so I'll make some vague statements.

> Given the following job, my assumption is that after 60 seconds the IO would time out and the job would fail 

Not quite:
1. `max_latency` actually means if you see a returned I/O that took longer than the specified time then error.
2. 60000000000 microseconds is 60000 seconds (or close to 17 hours). Did you know you can just use `max_latency=60s` (see http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-max-latency )?

On point 1., normally I/Os have a maximum in-flight time (e.g. Linux's SCSI block layer has a chunk of logic to ensure I/Os time out) but when you use dm-multipath you can subvert this. For example in `multipath.conf` you can set your configuration to hold on to I/Os indefinitely when no paths are available but if you chose to do this I will just point you toward the [unkillable task warning in the multipath.conf man page](https://linux.die.net/man/5/multipath.conf):

> **Known Issues**
> The usage of queue_if_no_path option can lead to D state processes being hung and not killable in situations where all the paths to the LUN go offline. It is advisable to use the no_path_retry option instead.

Most fio ioengines need their I/Os to return - the I/O can fail or succeed but they are not expected to remain in-flight indefinitely. A big part of this is because you can end up blocking on a syscall forever and you might find the process that made the syscall is unkillable even if you did have an outside agent that could detect it had become stuck...

> Am I missing a parameter that would more appropriately deal with a device that might potentially be be completely failing because no paths to the device exist or taking too long to find the correct path? 

`max_latency` is as close as you can get but it will only take effect after the I/O has returned.

> Are there mechanisms for dealing with completely failed devices?

Normally a completely failed device results in Linux refusing/erroring all I/Os rather than simply accepting I/O submissions and not returning their result forever. There's nothing in fio to handle the later but you might be able to handle this at a lower level by arranging for your multipath configuration to have a maximum number of times it will retry when there's no path available.

Does this help?

**Comment by sitsofe** [comment]
@rustyscottweber if the above answers your question could you close this issue? Thanks!

**Comment by rustyscottweber** [comment]
Very helpful.  However, I'm still trying to find the best solution.  The reason we had the multipath.conf setup the way we did relates to advice that was given a long time ago by "Mike Christy" who was the maintainer of multipathd.  Changing the multipath.conf to contain no_path_retry_count will eventually fail the IO.  I will continue testing with the new settings.

**Comment by rustyscottweber** [comment]
@sitsofe , I believe I have done some more research into the subject and believe that permanently changing the multipath.conf file to include a "no_path_retry_count" variable is the path to take.  According to the documentation, "no_path_retry_count" implies "queue_if_no_path" but sets a limit on how many times to retry IO's in the queue before failing them.  Given that the advice is really old, it should be safe to change.

Adding "exitall=1" to the job defaults should fix the rest of my problems.
