### ISSUE TITLE
Estimating the latency of batched random read IOs on SSD

### ISSUE THREAD

**Issue by minjiaz** [axboe/fio#559]
Hi,

I am trying to have an evaluate on the best latency an SSD can achieve with random read accesses. The behavior I am trying to simulate with fio is an application thread does the following operations:
- sending 100 random reads to SSD at once
- retrieve results from 100 reads
- wait 5ms
- submit the next batch of reads and repeat 
And I'm trying to estimate how long it takes to send and receive 100 reads as a batch. The 5ms wait time is added to simulate some "pause" after issuing 100 reads.

The command I use is:
fio --name=randread --ioengine=libaio --iodepth=100 --iodepth_batch_submit=100 --iodepth_batch_complete=1 --iodepth_low=0 --thinktime=5000 --thinktime_blocks=100 --rw=randread --bs=4k --direct=1 --size=4096M --numjobs=1 --runtime=240  --group_reporting

The result I got:
randread: (g=0): rw=randread, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=100
fio-2.2.10
Starting 1 process
Jobs: 1 (f=1): [r(1)] [100.0% done] [59140KB/0KB/0KB /s] [14.8K/0/0 iops] [eta 00m:00s]
randread: (groupid=0, jobs=1): err= 0: pid=36296: Mon Mar 12 10:53:33 2018
  read : io=4096.0MB, bw=59031KB/s, iops=14757, runt= 71053msec
    slat (usec): min=5, max=2051, avg=983.87, stdev=145.51
    clat (usec): min=4, max=4010, avg=255.85, stdev=218.26
     lat (usec): min=337, max=4862, avg=1239.84, stdev=198.15
    clat percentiles (usec):
     |  1.00th=[   11],  5.00th=[   19], 10.00th=[   31], 20.00th=[   60],
     | 30.00th=[   94], 40.00th=[  143], 50.00th=[  215], 60.00th=[  262],
     | 70.00th=[  314], 80.00th=[  434], 90.00th=[  588], 95.00th=[  660],
     | 99.00th=[  940], 99.50th=[  996], 99.90th=[ 1128], 99.95th=[ 1192],
     | 99.99th=[ 1912]
    bw (KB  /s): min=58015, max=60317, per=100.00%, avg=59084.05, stdev=312.87
    lat (usec) : 10=0.49%, 20=4.69%, 50=11.38%, 100=15.06%, 250=25.37%
    lat (usec) : 500=26.40%, 750=14.21%, 1000=1.97%
    lat (msec) : 2=0.44%, 4=0.01%, 10=0.01%
  cpu          : usr=2.52%, sys=18.71%, ctx=176750, majf=0, minf=277
  IO depths    : 1=0.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=100.0%
     submit    : 0=0.0%, 4=50.2%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=49.8%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued    : total=r=1048576/w=0/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=100

Run status group 0 (all jobs):
   READ: io=4096.0MB, aggrb=59030KB/s, minb=59030KB/s, maxb=59030KB/s, mint=71053msec, maxt=71053msec

Disk stats (read/write):
  sdc: ios=1044091/5, merge=3209/10, ticks=530040/0, in_queue=525800, util=24.46%

My question is:
The 95th percentile completion latency is 660us, and the IOPS is 14757. Should the total latency of sending 100 reads and receiving results be estimated as: 660 + 10^6 /14757 * 99 = 7368.6806 us = 7.4ms? Here, the latency is estimated as a combination of 95th latency and throughput.
In the case when the thinktime is not 0, does 10^6 / IOPS still give the average latency per read request?

**Comment by sitsofe** [comment]
@minjiaz Hi, I'm not sure how meaningful what you're attempting is from a statistical perspective and there may be other flaws too.

You're taking an average that was calculated over all I/Os (the IOPS) and trying to use it with another statistic (the 95th percentile latency) that is over a different (and skewed) range of values...

Another issue appears to be that not all the I/O submission batches are achieving the depths you're requesting - see the "submit :" line. You would need to check how many inflight I/Os your kernel says it can take for that device (if it's SATA you might find you're limited to 32).

Something else to be aware of: the iops= value is a calculated average: (total I/Os done) / (runtime in seconds). So in your example 1048576 / (71053 / 1000). In your case that value necessarily includes the thinktime gaps within it - you weren't doing the maximum possible I/O across the whole period. Knowing this are you sure it represents the value you were after?

> Should the total latency of sending 100 reads and receiving results be estimated as: 660 + 10^6 /14757 * 99 = 7368.6806 us = 7.4ms?

I'd say you don't know - you can't deduce that result because I don't think it is meaningful to use those values in that manner.

You might be better served recording each I/O's latency to a file (so long as you don't have too many values) and then calculating your own statistics from those. With recent versions of fio the first part can be done using the `write_lat_log` option mentioned on http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-write-lat-log but note the version of your fio compared to what we're up to now on https://github.com/axboe/fio/releases . The documentation linked is for the most recent fio version...

PS: As this isn't so much an issue in fio and more of a "how do I?" question it might be better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.5/README#L58). If you're done for now could you close this issue? Thanks!

**Comment by minjiaz** [comment]
Thanks a lot for the detailed reply, sitsofe. That's a lot of helpful information! I will give the recent version of fio a try and move to the fio mailing list if I have more findings and questions.
