### ISSUE TITLE
___

### ISSUE THREAD

**Issue by shashank9003** [axboe/fio#607]
____

**Comment by sitsofe** [comment]
@shashank9003 It's not clear 100% clear precisely what steps you took initially (the order you run things and their exact options matter) but looking at your job shows you have

```
#verify=crc32c
```

If we assume that line was uncommented at the time you ran your read job one explanation for what you saw is as follows:

For a read verification run using crc32c headers to be successful, fio has to have **previously written** the file **with crc32c verification headers** using near enough the **same job parameters**. Imagine I have a file `myfile` full of random or empty data and I run fio like this:

```
fio --name=verifyheaderdata --size=1M --filename=myfile --rw=read --verify=crc32c 
```

this run will fail with a verification error (because the verification headers will not be found). Similarly if I do something like this:
```
fio --name=writenoheader    --size=1M --filename=myfile --rw=write
fio --name=verifyheaderdata --size=1M --filename=myfile --rw=read  --verify=crc32c
```

The second fio will fail (again no verification headers will be found). Something like this:

```
fio --name=writenoheader    --size=1M --filename=myfile --rw=write --verify=crc32c
fio --name=verifyheaderdata --size=1M --filename=myfile --rw=read  --verify=crc32c
```

will work because the first job prefixed headers to the start of each block it wrote. See http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-verify for more details.

If this answers your question could you close this issue? Thanks!

**Comment by shashank9003** [comment]
Thank you very much

**Comment by shashank9003** [comment]
Thank you very much so will this work?

job file is as follows:

[global]
filename=/home/ufs_fio_test/fio-seq-reads
#bs=4k
bs=16384k
direct=1
size=4G
numjobs=1
ioengine=libaio
iodepth=16
verify=crc32c
[file0]
rw=write
stonewall
[file1]
rw=read

**Comment by sitsofe** [comment]
@shashank9003

> will this [given job file] work?

In general yes but in this instance your block size is absolutely giant (16384k is 16777216 bytes which is 16Mbytes). This is odd especially given that you're doing direct I/O...

I'm going to stop there because you're breaking netiquette here in a few ways:
* Generally issues should be constrained to the original topic. Reopening a closed issue to ask about non-original issue is cheating :-)
* Most of what I've seen you file here on Github has has been along the lines of "How do I...", "Will this work?", "Does fio have this feature?" which aren't bugs in fio per se but a general theme of "Please help me understand...". Asking that style of question isn't wrong but I feel that for fio the Github issue tracker is not the place to do so. 

I'm going to request that you close this issue here and strongly recommend that you send this and further questions of this style to the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.7/README#L58) (note it will only accept non-HTML email). The mailing list is a better place for these questions because:
* There's a better chance they will be answered by more people
* It's more conversational and better suited to a back and for.
