### ISSUE TITLE
read rate drops with verify enabled Why? I think there is something wrong going on inside fio library

### ISSUE THREAD

**Issue by shashank9003** [axboe/fio#608]
Why does the throughput of read drops drastically when I enable verify:
For example, for the following job file: I get maxb as 750MB/s when verify is disabled, however only 200Mb/s when I enable the verify??
Assuming that we have done a write job (rw=write) immediately before the read job with the same job parameters. The read job file is as follows: 
[global]
filename=fio-seq-reads
rw=read 
bs=4k
direct=0
numjobs=1
#time_based=1
#runtime=10
verify=crc32c  <---

[file1]
size=4G
ioengine=libaio
iodepth=16

**Comment by axboe** [comment]
There shouldn't be a huge difference. If I run this on my laptop, the read difference between verify being on or off, is 1870MiB/sec vs 1992MiB/sec. Please try and run ./fio --crctest and show the speeds there, I'm assuming you're not using the hw accelerated crc32c for some reason. What version of fio are you running?

**Comment by sitsofe** [comment]
@axboe I'm going to guess @shashank9003 is using a moderately old fio (2.7) based on the output of another question...

**Comment by axboe** [comment]
Side note - direct=0 and ioengine=libaio/iodepth=16 don't mix well. libaio requires direct=1 to be async. The above will run single queue depth reads, buffered.

**Comment by axboe** [comment]
And if you are using an ancient version of fio, upgrade first. As it stands, there's too little information in your bug report to do anything about it. See REPORTING-BUGS in the fio repository:

http://git.kernel.dk/cgit/fio/tree/REPORTING-BUGS

**Comment by axboe** [comment]
Feel free to reopen with more information.

**Comment by shashank9003** [comment]
the latest version available on github

**Comment by sitsofe** [comment]
@shashank9003 In summary your results are suggesting the crc32c operation is being done in software. What platform are you on, some sort of ARM based device (note: this is a leading question)?

Here are the results I get running on bare metal machine with a Core i3-4330:

md5:		  630.18 MiB/sec
crc64:		  409.68 MiB/sec
crc32:		  363.10 MiB/sec
crc32c:		 8893.83 MiB/sec

Because the checksum being used is so slow your speeds are going to be limited by that (notice how the speed you say you get is a bit less than that of checksum speed).

> version 2.7[ is it expected that read maxb would differ largely with and without verify on this version??]

Depending on the situation and environment the answer could be a strong yes (note we only support the latest fio. See https://github.com/axboe/fio/releases for which version we're up to). I think Jens is totally correct to point out your fio version is old...

**Comment by shashank9003** [comment]
Thanks a lot buddy. Your answers were quite helpful

**Comment by sitsofe** [comment]
@rohan003 Just for completeness, can you let us know what platform you're running on? Intel x86_64? ARM32? ARM64?

**Comment by shanks9003** [comment]
@sitsofe well sorry, I am not allowed to disclose that (copyright issues).

**Comment by sitsofe** [comment]
@shanks9003 Hehe, OK. Just for the record (and for anyone stumbling here via a search engine) if your platform happens to be ARM64 then the patches that enable accelerated crc32c for that platform "only" arrived in fio 2.17 (see https://github.com/axboe/fio/commit/214e2d5655f79e75f492167fba97785f4ce53d07 ). Changes like that are a good example of why we (the upstream of fio) only support the very latest version...
