### ISSUE TITLE
Behaviour of IOPS and BW rates when using fio on s3fs

### ISSUE THREAD

**Issue by CMCDragonkai** [axboe/fio#692]
I have used fio to test against s3fs. I've noticed a big difference in IOPS and BW rates when using s3fs without cache to using s3fs with cache. Specifically although with cache is much faster by wall clock time, the reported IOPS and BW rates are much worse than the instance without cache.

Here is my fio configuration.

```ini
[readfiles]
nrfiles=1000
filesize=2MiB
bs=4k
rw=read
```

After mounting a bucket and creating a `tmp` directory.

```
s3fs BUCKET ./bucket \
  -o noexec \
  -o noatime \
  -o auto_unmount \
  -o default_permissions \
  -o uid="$(id -u)" \
  -o gid="$(id -g)" \
  -o complement_stat \
  --debug
```

This is the fio report:

```
readfiles: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.5
Starting 1 process

readfiles: (groupid=0, jobs=1): err= 0: pid=26347: Mon Sep 24 17:03:12 2018
   read: IOPS=2979, BW=11.6MiB/s (12.2MB/s)(1906MiB/163778msec)
    clat (nsec): min=523, max=2106.2M, avg=269555.06, stdev=6920148.37
     lat (nsec): min=541, max=2106.2M, avg=269579.20, stdev=6920180.94
    clat percentiles (nsec):
     |  1.00th=[      700],  5.00th=[      756], 10.00th=[      780],
     | 20.00th=[      796], 30.00th=[      812], 40.00th=[      828],
     | 50.00th=[      844], 60.00th=[      860], 70.00th=[      884],
     | 80.00th=[      924], 90.00th=[     1048], 95.00th=[     1192],
     | 99.00th=[   226304], 99.50th=[  1073152], 99.90th=[ 85458944],
     | 99.95th=[101187584], 99.99th=[154140672]
   bw (  KiB/s): min=    7, max=1020720, per=100.00%, avg=12512.64, stdev=96605.01, samples=312
   iops        : min=    1, max=255180, avg=3128.10, stdev=24151.26, samples=312
  lat (nsec)   : 750=4.64%, 1000=83.02%
  lat (usec)   : 2=10.85%, 4=0.10%, 10=0.02%, 20=0.10%, 50=0.04%
  lat (usec)   : 100=0.01%, 250=0.27%, 500=0.26%, 750=0.05%, 1000=0.10%
  lat (msec)   : 2=0.06%, 4=0.03%, 10=0.03%, 20=0.08%, 50=0.09%
  lat (msec)   : 100=0.18%, 250=0.05%, 500=0.01%, 750=0.01%
  cpu          : usr=0.11%, sys=0.47%, ctx=10579, majf=0, minf=16
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=488000,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=11.6MiB/s (12.2MB/s), 11.6MiB/s-11.6MiB/s (12.2MB/s-12.2MB/s), io=1906MiB (1999MB), run=163778-163778msec
```

Specifically the interesting part is this: `read: IOPS=2979, BW=11.6MiB/s (12.2MB/s)(1906MiB/163778msec)`.

Now I unmounted the bucket, remounted it this time with its cache setting enabled.

```
s3fs BUCKET ./bucket \
  -o noexec \
  -o noatime \
  -o auto_unmount \
  -o default_permissions \
  -o uid="$(id -u)" \
  -o gid="$(id -g)" \
  -o complement_stat \
  -o use_cache="$(pwd)/s3fscache" \
  -o check_cache_dir_exist \
  -o del_cache \
  -o enable_noobj_cache \
  --debug
```

This time running it from fio gives me a report like:

```
readfiles: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.5
Starting 1 process

readfiles: (groupid=0, jobs=1): err= 5 (file:filesetup.c:703, func=open(readfiles.0.984), error=Input/output error): pid=11542: Mon Sep 24 17:35:34 2018
   read: IOPS=33, BW=135KiB/s (138kB/s)(3940KiB/29154msec)
    clat (usec): min=10, max=478, avg=133.37, stdev=44.83
     lat (usec): min=11, max=479, avg=133.95, stdev=44.98
    clat percentiles (usec):
     |  1.00th=[   79],  5.00th=[   89], 10.00th=[   99], 20.00th=[  109],
     | 30.00th=[  113], 40.00th=[  116], 50.00th=[  122], 60.00th=[  128],
     | 70.00th=[  141], 80.00th=[  153], 90.00th=[  180], 95.00th=[  196],
     | 99.00th=[  367], 99.50th=[  420], 99.90th=[  478], 99.95th=[  478],
     | 99.99th=[  478]
   bw (  KiB/s): min=   40, max=  176, per=100.00%, avg=145.72, stdev=26.28, samples=54
   iops        : min=   10, max=   44, avg=36.39, stdev= 6.55, samples=54
  lat (usec)   : 20=0.10%, 100=10.66%, 250=87.41%, 500=1.83%
  cpu          : usr=0.07%, sys=0.26%, ctx=3774, majf=0, minf=24
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.1%, 4=99.9%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=985,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=135KiB/s (138kB/s), 135KiB/s-135KiB/s (138kB/s-138kB/s), io=3940KiB (4035kB), run=29154-29154msec
```

Even though running with the cache is clearly faster, it gives me back: `read: IOPS=33, BW=135KiB/s (138kB/s)(3940KiB/29154msec)`. Which has a very low rate of IOPS and bandwidth. I also noticed that it outputs an error, but this error does not exist when running the benchmark.

What's the reason for this?

**Comment by sitsofe** [comment]
@CMCDragonkai Some of those latencies from the first run look extremely low (87% were under a microsecond?) - was most of the I/O just being read out of the kernel page cache?

>  I also noticed that it outputs an error, but this error does not exist when running the benchmark

```
err= 5 (file:filesetup.c:703, func=open(readfiles.0.984)
```

Looks like fio had trouble trying to open one the files. Did you check `dmesg` to see if  `s3fs` logged an internal issue?

From a quick glance these look like things arising from s3fs's behaviour rather so I'd say you are better off having a chat to the `s3fs` developers (@ggtakec can you let @CMCDragonkai know how to do this?) to find out what it actually does under hood.

Further since these aren't so much issues in fio itself and are more "Can you explain these results on a non-traditional filesystem?" questions from an fio perspective they might be better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.10/README#L58)...

**Comment by CMCDragonkai** [comment]
@sitsofe It is possible that reads came from the kernel page cache. I had s3fs cache enabled. So s3fs may store the files first in the cache directory before returning that data back. However I'm not understanding how fio records IOPS and BW in a such a way to show such a small rate compared to the non-cache situation. After all the same amount of data exists, and the wall clock time is much smaller. Shouldn't at least the BW be much higher? Why would the usage of FUSE filesystems affect bandwidth rate calculation?

That error doesn't quite make sense to me. I had s3fs logging that data, but I could not see which file failed to be read. This error also happens on a write test:

```
writefiles: (groupid=0, jobs=1): err= 5 (file:filesetup.c:703, func=open(writefiles.0.981), error=Input/output error): pid=18977: Mon Sep 24 18:10:39 2018
```

**Comment by sitsofe** [comment]
> the wall clock time is much smaller

Didn't fio stop early due to errors? Compare:

> ```
>      issued rwts: total=488000,0,0,0 short=0,0,0,0 dropped=0,0,0,0
> ```

to

> ```
>      issued rwts: total=985,0,0,0 short=0,0,0,0 dropped=0,0,0,0
> ```

Given the difference in the average latencies of the I/Os between the first and second jobs I would expect the second job to be slower if everything were equal though.

> That error doesn't quite make sense to me.

You could try enabling `--debug=file` (see https://fio.readthedocs.io/en/latest/fio_doc.html )...

(note we're venturing further away from a regular issue and deep into discussion now - may I suggest if we need to continue this further that we take it to the mailing list?)

**Comment by sitsofe** [comment]
As this isn't so much an issue in fio and more of a "How do I?/Why is?" question it is better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.10/README#L58) (note that the list only accepts plain text emails).

Given the above I'm going to close the issue here but feel free to continue it on the mailing list.
