### ISSUE TITLE
Sequential Write Speeds Way Too Slow

### ISSUE THREAD

**Issue by Rabcor** [axboe/fio#711]
Sequential write tests on dd:
```
$ dd if=/dev/zero of=tempfile bs=1M count=5120 conv=notrunc oflag=direct status=progress
5291114496 bytes (5,3 GB, 4,9 GiB) copied, 11 s, 481 MB/s
5120+0 records in
5120+0 records out
5368709120 bytes (5,4 GB, 5,0 GiB) copied, 11,1929 s, 480 MB/s

$ dd if=/dev/zero of=tempfile bs=1024M count=5 conv=notrunc oflag=direct status=progress
5368709120 bytes (5,4 GB, 5,0 GiB) copied, 11 s, 490 MB/s
5+0 records in
5+0 records out
5368709120 bytes (5,4 GB, 5,0 GiB) copied, 10,9524 s, 490 MB/s
```

Sequential write tests on fio:
```
$ fio --ioengine=libaio --size=1024m --filename=$HOME/tempfile --direct=1 --loops=5 --name=test --bs=1m --rw=write
....
    write: IOPS=146, BW=147MiB/s (154MB/s)(5120MiB/34894msec); 0 zone resets

$ fio --ioengine=libaio --size=1024m --filename=$HOME/tempfile --direct=1 --loops=5 --name=test --bs=1024m --rw=write
....
    write: IOPS=0, BW=144MiB/s (151MB/s)(5120MiB/35458msec); 0 zone resets
```
(Tested on manjaro linux using ext4 file system)
It is clear that something is going majorly wrong here, with fio reporting writes at less than 1/3 the real sequential write speeds the drive is capable of.

Sequential read and write speeds are typically fairly close together (with writes usually a little bit slower but not really by that much) after searching around I have found no information on the issue, but I have found a bunch of questions by people who think their drives write speeds are actually as slow as fio is reporting it.

**Comment by sitsofe** [comment]
@Rabcor Do you really want blocks of 1 Gigabyte (1024m = 1024 * 1024^2 bytes = 1024^3 bytes = 1073741824 bytes)?

As this isn't so much an issue in fio and more of a "How do I/Why is?" question it is better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.11/README#L58) (note that the list only accepts plain text emails) so can you close it here and post your question there?

**Comment by sitsofe** [comment]
(PS: the contents of the data you are using matters massively)

**Comment by Rabcor** [comment]
@sitsofe Why are you so sure it isn't an issue with fio? And can you clarify what you meant with this?

> (PS: the contents of the data you are using matters massively)

**Comment by sitsofe** [comment]
> @sitsofe Why are you so sure it isn't an issue with fio? And can you clarify what you meant with this?

That's an excellent question! Why don't we take this discussion to the mailing list...

**Comment by Rabcor** [comment]
@sitsofe that's an excellent deflection! Why don't you give me straight answers?

**Comment by axboe** [comment]
Sitsofe has pointed you to the mailing list as a resource on how to get help. If you think fio has some glaringly obvious issue with probably the most basic of workloads, then write an email detailing that issue.
One hint might be that dd is writing zeroes, you could ask fio to do the same with zero_buffers=1. Right now you are writing random data. On top of that, you're using the async interface with, you'd want to use ioengine=psync or similar to get something closer to what dd is doing. You're also overwriting the same 1g with 1m buffers 5 times, which is also different. You might want to look into doing a fully comparative test, before you assume that anything is broken here.

Now please follow the advise and report this on fio@vger.kernel.org. Issues are for bugs, I'm guessing this one is a usability question rather than a bug. Closing.

**Comment by Rabcor** [comment]
That explains it, thanks. Writing zeroes was the difference. Using psync only further reduced the write speeds; and the reason for all this, is because of lack of information on the subject available on the internet, I would've had to guess my way through the lengthy documentation to ever figure this out on my own.

I just wrongly assumed this to be a bug rather than a feature.

**Comment by axboe** [comment]
That’s why fio doesn’t write zeroes by default, it’s a bad write pattern if you really want to know what the storage device can do in terms of performance, as this case also aptly demonstrates.
