### ISSUE TITLE
feature request: libdispatch ioengine for macOS

### ISSUE THREAD

**Issue by joshenders** [axboe/fio#724]
I'm interested in measuring AIO performance on macOS given a workload that utilizes libdispatch. I would love to see libdispatch added to the list of ioengines: https://github.com/apple/swift-corelibs-libdispatch

**Comment by sitsofe** [comment]
@joshenders (I'm not volunteering to do this work - I'm just curious!)

Would the engine somehow be abstract (like `cpuio` - https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-ioengine) or is it still doing disk I/O?

Such an engine might need some trickery because `fio` has a concept of threads and processes at its heart whereas with GCD that's all supposed to be taken care of for you (it looks like the idea is that you just submit tasks and that's it) so there would need to be warnings that the usual `fio` process/thread options can't be used.
 
There's some information on calling using GCD from C on https://wiki.freebsd.org/GCD#The_same_program.2C_without_C_Blocks .

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If you can provide the requested information please reopen. Thanks!
