### ISSUE TITLE
I am trying to understand what happens step-by-step when this fio command is run?

### ISSUE THREAD

**Issue by sdhir93** [axboe/fio#755]

**Comment by sdhir93** [comment]
./fio -ioengine=libaio -bs=32k -direct=1 -thread -rw=randrw -percentage_random=100,0 -rwmixread=70 -size=10G -filename=randread_test.txt -name='test' -iodepth=4 -runtime=60 
Since the reads are 70% here, what is actually being read? Is it reading the 30% writes again and again.

**Comment by sitsofe** [comment]
@sdhir93 Assuming that all the dashes are actually double:
* [`ioengine=libaio`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-ioengine) - use the `libaio` ioengine.
* [`bs=32k`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-blocksize) - do I/O in 32 kilobyte (32*1024^2) blocks
* [`direct=1`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-direct) - try and bypass the Linux page cache
* [`thread`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-thread) - when running more than one jobs use threads (as opposed to processes)
* [`rw=randrw`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-readwrite) - do random reads AND random writes (but see below)
* [`percentage_random=100,0`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-percentage-random) - make the reads fully random but make the writes fully sequential
* [`rwmixread=70`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-rwmixread) - make 70% of the I/O done reads and the other 30% done writes
* [`size=10G`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-size) - only do I/O in the first 10 gigabytes (10*1024^3) of whichever file/device is used and try and create it at that size if it doesn't already exist at a big enough size.
* [`filename=randread_test.txt`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-filename) - do I/O into the file `randread_test.txt`

(settings before this point were global)

* [`name=test`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-name) - create a new job named test
* [`iodepth=4`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-iodepth) - have up to 4 outstanding I/Os at any given time
* [`runtime=60`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-runtime) - exit this job after 60 seconds if it is still running

> Since the reads are 70% here, what is actually being read?

This questions is vague... `fio` does I/O against specific points of the file so with your job above if `fio` chooses to do a read at offset 0 `fio` will read whatever the first 32 killobytes of the file is.

> Is it reading the 30% writes again and again

Not exactly but it is complicated. If we look at some debug output (there are other ways to get this information but this will do for a tiny throwaway example) from a different job we can see some trends:
```
$ ./fio --randseed=1 --rw=randrw --percentage_random=100,0 --rwmixread=70 --ioengine=null --size=1M --bs=32k --name=go --debug=io | awk '/complete:/ {print $6}'
off=0x0,len=0x8000,ddir=1,file=go.0.0
off=0x8000,len=0x8000,ddir=1,file=go.0.0
off=0x8000,len=0x8000,ddir=0,file=go.0.0
off=0xb8000,len=0x8000,ddir=0,file=go.0.0
off=0x10000,len=0x8000,ddir=1,file=go.0.0
off=0x18000,len=0x8000,ddir=1,file=go.0.0
off=0xd0000,len=0x8000,ddir=0,file=go.0.0
off=0x20000,len=0x8000,ddir=1,file=go.0.0
off=0x28000,len=0x8000,ddir=1,file=go.0.0
off=0x78000,len=0x8000,ddir=0,file=go.0.0
off=0x60000,len=0x8000,ddir=0,file=go.0.0
off=0xd8000,len=0x8000,ddir=0,file=go.0.0
off=0x68000,len=0x8000,ddir=0,file=go.0.0
off=0x30000,len=0x8000,ddir=1,file=go.0.0
off=0x58000,len=0x8000,ddir=0,file=go.0.0
off=0x38000,len=0x8000,ddir=1,file=go.0.0
off=0xe8000,len=0x8000,ddir=0,file=go.0.0
off=0x40000,len=0x8000,ddir=1,file=go.0.0
off=0x10000,len=0x8000,ddir=0,file=go.0.0
off=0xe0000,len=0x8000,ddir=0,file=go.0.0
off=0xa0000,len=0x8000,ddir=0,file=go.0.0
off=0xf0000,len=0x8000,ddir=0,file=go.0.0
off=0x38000,len=0x8000,ddir=0,file=go.0.0
off=0x48000,len=0x8000,ddir=1,file=go.0.0
off=0x70000,len=0x8000,ddir=0,file=go.0.0
off=0x88000,len=0x8000,ddir=0,file=go.0.0
off=0x80000,len=0x8000,ddir=0,file=go.0.0
off=0xc8000,len=0x8000,ddir=0,file=go.0.0
off=0x90000,len=0x8000,ddir=0,file=go.0.0
off=0x50000,len=0x8000,ddir=1,file=go.0.0
off=0x58000,len=0x8000,ddir=1,file=go.0.0
off=0x98000,len=0x8000,ddir=0,file=go.0.0
```

So here we see the offset, length and data direction (where the direction's value is described in https://fio.readthedocs.io/en/latest/fio_doc.html#log-file-formats ) of the I/O fio is trying to do. You can see each write's I/O offset always consecutively follows on from where the last write I/O was done. The read I/O offsets skip around in comparison to the previous read but notice how they don't overlap an earlier read offset (even though they CAN overlap an earlier write offset). I'd say this suggests the offsets are being handled independently (based on whether they are sequential or random) because you specified a mix of sequential and random I/O. The behaviour of not trying to generate a random offset that has been previously covered by another randomly generated offset happens because [`norandommap`](https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-norandommap) isn't on.

Hopefully this answers your query and if so can you close this issue? Further, as this isn't so much an issue in fio and more of a "How do I/Why is/What does this do?" question follow ups are better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.13/README#L58) (note that the list only accepts plain text emails).

**Comment by sdhir93** [comment]
Thank you for the explanation. But there are some points not clear yet.

My intention is to simulate a mixed i/o for overlapped reads/writes. More specifically, I want some reads and write to be overlapped so that I can test a cache feature of a write i.e. if the write is still not written to NAND and there is a read issued for that specific data, I want to cover that edge case in my drive firmware by keeping the 70-30 ratio for reads and writes respectively. My assumption here is that when I issue the above command, fio is doing some writes on some blocks and reads the same data with a do_verify=1, it should run fine.

In view of the above, I am looking for further clarity on below things.

> This questions is vague... fio does I/O against specific points of the file so with your job above if fio chooses to do a read at offset 0 fio will read whatever the first 32 killobytes of the file is.

Which file is being referred to here. Is it the same as being written? If not, then what is it reading if the drive is fully erased.

Also,  If the read and write are independent i.e fio is writing something else and reading something else, what does do_verify=1 will be verifying then. My current assumption here is that do_verify=1 verifies that read data was same as written data.

> Not exactly but it is complicated.

Your comment is suggesting that its reading some other blocks unrelated to where the writes are issued. If that is the case
1. How can I make sure it is reading what I am writing through fio.
2. how the command needs to be modified simulate a overlapped read/writes as intended above.

Thanks in advance!

**Comment by sitsofe** [comment]
@sdhir93 I think we're better off taking this to the mailing:

> as this isn't so much an issue in fio and more of a "How do I/Why is/What does this do?" question follow ups are better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.13/README#L58) (note that the list only accepts plain text emails).

**Comment by sdhir93** [comment]
Sure, I will close it here.
