### ISSUE TITLE
Replay trace with timestamp 

### ISSUE THREAD

**Issue by pbhandar2** [axboe/fio#756]
I am using FIO to simulate a workload. I want to transfer the workload to another machine and run it while also simulating the time at which the requests come in. What I do currently is use the option 

write_iolog=*filename*

The log that I get is. 

fio version 2 iolog
/gpfs/skeletor/run_hawc_exp.0.0 add

/gpfs/skeletor/run_hawc_exp.0.0 open

/gpfs/skeletor/run_hawc_exp.0.0 write 2072348000 4000

/gpfs/skeletor/run_hawc_exp.0.0 write 25436172000 4000

/gpfs/skeletor/run_hawc_exp.0.0 write 28971548000 4000

/gpfs/skeletor/run_hawc_exp.0.0 write 16149572000 4000

These do not include timestamp. When I replay using read_iolog=*filename*, it does not simulate the rate at which the request come in because there is no timestamp in the log. How do I get the timestamp in the log and make it simulate the incoming request at a particular timestamp at a particular location.

**Comment by sitsofe** [comment]
@pbhandar2 I think you are misunderstanding what the time at the far right actually means (and the documentation doesn't help). The 4000 is relative to the start of the log NOT relative to the last I/O. So if 5000ms have passed since the job started then all of those writes will be done directly after one another. Put another way having a 5000ms "wait" followed by a 4000ms "wait" means the later wait will be of 0.

If you want a command that inserts delays relative to the last command that would likely be a duplicate request of #247 .

Does this explanation help?

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
