### ISSUE TITLE
fio trim correct?

### ISSUE THREAD

**Issue by rim0621** [axboe/fio#764]
i measured trim latency. 

and the output format is json.

i checked clat_ns, it was 34.12ns (bs=4k)

is it possible ? 

i think SSD works as us unit.

**Comment by sitsofe** [comment]
@rim0621 Could you include the full command line you ran, the fio version and its output (https://github.com/axboe/fio/blob/master/REPORTING-BUGS )?

**Comment by bcran** [comment]
I'm seeing something similar when I use the libaio or posixaio ioengine.
Version fio-3.13-37-g0513, running on openSUSE Tumbleweed x64.

Job file:
```
[global]
filename=/dev/nvme2n1
size=32g
time_based=1
runtime=30s
ioengine=libaio
direct=1
blocksize=4k

[write]
rw=trimwrite
```

write: IOPS=12.9k, BW=50.5MiB/s (52.0MB/s)(1516MiB/30001msec); 0 zone resets
    slat (nsec): min=2485, max=374854, avg=4003.13, stdev=993.64
    clat (nsec): min=410, max=12484, avg=591.44, stdev=75.26
     lat (usec): min=3, max=376, avg= 4.68, stdev= 1.02
trim: IOPS=12.9k, BW=50.5MiB/s (52.0MB/s)(1516MiB/30001msec)
    clat (nsec): min=30, max=6473, avg=76.40, stdev=21.58
     lat (usec): min=66, max=377, avg=71.63, stdev= 4.41


Using the sync ioengine, I get a more reasonable values for clat trim of min 63us min, 71us avg.

However, since the clat value for the *writes* is also unreasonable with the async io engines - this being a U.2 NVMe drive it won't be completing writes in under 1us - it seems the `lat` value is the one to be looking at nowadays?

**Comment by vincentkfu** [comment]
Incredibly short trim completion latencies occur because libaio trims are actually synchronous operations but timestamps used for calculating latencies are recorded as if trim were an asynchronous operation. `issue_time` is recorded *after* the OS has issued the trim command and control has returned to fio. `completion_time` is recorded very shortly thereafter. So the result is that trims appear to complete in a few dozen nanoseconds on average.

`ioengines.c:td_io_queue()` is where io_u's are sent to ioengines.

```
	ret = td->io_ops->queue(td, io_u);
```

In Linux, libaio trims operations ultimately call `os-linux.h:os_trim()` which issues a call to the BLKDISCARD IOCTL.

At the very end of `td_io_queue()` is where `issue_time` is recorded for libaio operations.

```
	if (!td_ioengine_flagged(td, FIO_SYNCIO)) {
		if (fio_fill_issue_time(td))
			fio_gettime(&io_u->issue_time, NULL);

		/*
		 * only used for iolog
		 */
		if (td->o.read_iolog_file)
			memcpy(&td->last_issue, &io_u->issue_time,
					sizeof(io_u->issue_time));
```


I can think of two ways to address this problem:

* drop support for trim from libaio, posixaio, and io_uring when they do not support asynchronous trims. This is probably the right thing to do but would be painful for users.
* change the way that timestamps are recorded for trims when the ioengine is async but carries out a sync trim operation
   * if we have an async ioengine with a sync trim operation, record `issue_time` before sending the io_u to the engine
   * we would need some sort of ioengine flag to identify this case because some async ioengines do support async trims

@axboe which of the two options do you prefer, or do you have another proposal?

**Comment by axboe** [comment]
For async setups/engines where submission ends up being sync, we should probably just make sure that we log the latency appropriately. That means using 0 where it makes sense, and accounting the full time in the correct spot.
