### ISSUE TITLE
Verify should consider the randseed

### ISSUE THREAD

**Issue by Vladyyy** [axboe/fio#811]
If I ran the following 2 jobs:

```
fio --filename=test --rw=write --size=100MB --name=test --verify=crc32 --do_verify=1 --randseed=1
fio --filename=test --rw=read --size=100MB --name=test --verify=crc32 --randseed=10
```

I would expect the second read job to fail with a verification mismatch since the seeds are different. 

Looking at the source code FIO stores the randseed in the verification header during the write phase but doesn't check to see it matches the supplied value in the read phase.

**Comment by sitsofe** [comment]
@Vladyyy The problem is that people routinely don't set the randseed and since it's randomly generated you would get a mismatches when doing split verification when it's not set. I guess you could check if it's been explicitly set...

https://github.com/axboe/fio/blob/master/verify.c#L830 suggests there are cases where the `rand_seed` will be checked.  https://github.com/axboe/fio/blob/master/verify.c#L928 says there are cases where it won't be (because it gets faked). 

(https://github.com/axboe/fio/commit/c4b6117b236370b174f3e3d2e299bf8b3733be97 suggests that because the order that writes complete can be different to the order that the orginal sequence generated data from the random seed this can complicate verification but this should affect the value of the rand_seed itself)

**Comment by Vladyyy** [comment]
Thanks @sitsofe.

It seems the example I posted doesn't work as I would expect because of the condition you refereed to above: Where randseed is considered during verification only for a read-write workload.
```
		if (!td_rw(td) || (td->flags & TD_F_VER_BACKLOG))
			io_u->rand_seed = hdr->rand_seed;
```

I wonder what's the reasoning behind that ?

Change seems to have been made in the commit: [f31feaa216429](https://github.com/axboe/fio/commit/f31feaa21642929b6d9d5396b73669372fda9a0a)
