### ISSUE TITLE
Understanding write performance, with psync vs libaio

### ISSUE THREAD

**Issue by sherlockwu** [axboe/fio#812]
Hi there,

Im trying to understand different results I saw when **comparing psync and libaio**

1) My fio script is like this:
[global]
name=fio-rand-write
;ioengine=libaio
ioengine=psync
direct=1
thread=1
buffered=0
size=100%
randrepeat=0
time_based
ramp_time=0
norandommap
refill_buffers
log_max_value=1
group_reporting
percentile_list=25.0:50.0:75.0:99.0
filename=/mnt/970/data_970
[file1]
;stonewall
bs=16k
iodepth=1
numjobs=32
rw=randwrite
runtime=20

2) For **write** performance I saw:
     throughput(psync) = 643MB/s
     throughput(libaio) = 2300MB/s
    which is a lot difference. **Im wondering is this expected? thanks.**

3) However, for **read** performance, I saw similar numbers then
     throughput(psync) = 2400MB/s
     throughput(libaio) = 2400MB/s

Thanks.

**Comment by sitsofe** [comment]
@sherlockwu As this isn't so much an issue in fio and more of a "How do I/Why is?" question it is likely better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.15/README#L58) (note that the list only accepts plain text emails).

(You may also be better off posting some of the actual final group output produced by fio if you do send a mail to the mailing list. It's unclear whether you are saying your total bandwidth is 2.3+2.4 = 4.7GB/s since you are using `rw=readwrite`...)

**Comment by axboe** [comment]
Closing, this isn't a bug/issue, as sitsofe explained.
