### ISSUE TITLE
Creating an official Docker image?

### ISSUE THREAD

**Issue by zedtux** [axboe/fio#858]
There are plenty of containers for fio, but there are old and can't really trust them ...

`fio` is really good to test volume accesses from Docker/Kubernetes so having an official and trustable Docker image would be really great.

Would you mind (or anyone else) to build that image?

**Comment by sitsofe** [comment]
I'm reluctant on this one because publishing docker images means we're on the hook for the whole container. In addition:
- The upstream fio project doesn't really make binaries available (there are some for Windows but that's more for testing purposes)
- Most distros have fio (albeit usually an old one) in their repos so you're only a package manager command away from having it
- Building a basic fio on full fat distros isn't difficult (the main gotcha is making sure you have libaio / io_uring development libraries/headers around) and doesn't take too long

So I'd so no to an official docker image for now (but maybe yes to someone positing a patch for a lean mean Dockerfile to be included in the repo which mentions the caveats about things like Docker's filesystem and libaio). I'll close this issue for now but if someone posts such a patch please link to this issue. Thanks!

**Comment by zedtux** [comment]
😕
