### ISSUE TITLE
avg latency is inconformity with avg iops in my fio test

### ISSUE THREAD

**Issue by javagyt** [axboe/fio#902]
```
[root@jz-cae6d9ea42ed8df0fa7f10be3fbb-server-0-dzevespbolun ~]# fio --name=test --rw=randwrite --bs=4k --runtime=60 --ioengine=libaio --iodepth=1 --numjobs=1 --filename=/dev/vdb --direct=1 --group_reporting=1 --time_based=1 --eta-newline 1 --write_iops_log=randwrite_4k_1numjobs_1iodepth
test: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
fio-3.7
Starting 1 process
test: (groupid=0, jobs=1): err= 0: pid=3364: Fri Jan 10 11:57:19 2020
  write: IOPS=955, BW=3824KiB/s (3916kB/s)(224MiB/60002msec)
    slat (nsec): min=0, max=990036k, avg=50267.29, stdev=5845999.55
    clat (nsec): min=0, max=1007.3M, avg=1841937.98, stdev=31497445.83
     lat (nsec): min=0, max=1007.4M, avg=1889417.66, stdev=32034499.75
    clat percentiles (nsec):
     |  1.00th=[        0],  5.00th=[        0], 10.00th=[   724992],
     | 20.00th=[   790528], 30.00th=[   823296], 40.00th=[   847872],
     | 50.00th=[   880640], 60.00th=[   913408], 70.00th=[   946176],
     | 80.00th=[   995328], 90.00th=[  1073152], 95.00th=[  1138688],
     | 99.00th=[  1449984], 99.50th=[  1761280], 99.90th=[994050048],
     | 99.95th=[994050048], 99.99th=[994050048]
   bw (  KiB/s): min=    8, max= 4547, per=64.27%, avg=2457.12, stdev=733.83, samples=113
   iops        : min=    1, max=    1, avg= 1.00, stdev= 0.00, samples=57358
  lat (nsec)   : 2=9.23%
  lat (usec)   : 50=0.01%, 250=0.01%, 500=0.01%, 750=2.51%, 1000=68.44%
  lat (msec)   : 2=19.42%, 4=0.25%, 10=0.04%, 1000=0.10%
  cpu          : usr=0.39%, sys=2.18%, ctx=57359, majf=0, minf=33
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,57358,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=3824KiB/s (3916kB/s), 3824KiB/s-3824KiB/s (3916kB/s-3916kB/s), io=224MiB (235MB), run=60002-60002msec

Disk stats (read/write):
  vdb: ios=15/57307, merge=0/0, ticks=10/59010, in_queue=59010, util=98.30%

# uname -r
4.11.0-22.el7a.aarch64
```

I don't know why，avg lat=1.88ms, avg iops=955 in this fio test,if say lat avg=1.88ms,the avg iops should be 532.

**Comment by sitsofe** [comment]
@javagyt you don't know what the distribution of samples in both cases looks like to know that those should match each other. I believe latency is measured (on a per I/O basis but with a rolling average) whereas IOPS is derived (total I/Os done (57358) divided by time (60002msec) = 955.93).

Another thing to note is that you have completion latencies of 0. Did you know that this is due to caching? How would this distort results?

Finally do you get the same results with a more recent version of fio?

**Comment by javagyt** [comment]
@sitsofe 
this VM is from openstack,i have ssd as cache device in my ceph osd. i don't know why min completion latencies of 0. Is it a latency measured error? my vm current clocksource is:"arch_sys_counter".
the same test on host node:
`test: (groupid=0, jobs=1): err= 0: pid=4804: Fri Jan 10 21:05:17 2020
  write: IOPS=1043, BW=4173KiB/s (4273kB/s)(169MiB/41417msec)
    slat (usec): min=3, max=233, avg= 8.65, stdev= 3.24
    clat (usec): min=601, max=285415, avg=948.48, stdev=2639.81
     lat (usec): min=607, max=285425, avg=957.12, stdev=2639.89
    clat percentiles (usec):
     |  1.00th=[  685],  5.00th=[  717], 10.00th=[  742], 20.00th=[  775],
     | 30.00th=[  799], 40.00th=[  824], 50.00th=[  848], 60.00th=[  881],
     | 70.00th=[  914], 80.00th=[  955], 90.00th=[ 1045], 95.00th=[ 1172],
     | 99.00th=[ 2376], 99.50th=[ 2704], 99.90th=[15270], 99.95th=[19006],
     | 99.99th=[96994]
   bw (  KiB/s): min= 1816, max= 4712, per=99.98%, avg=4170.99, stdev=589.48, samples=82
   iops        : min=  745, max= 1176, avg=1042.85, stdev=112.47, samples=41
  lat (usec)   : 750=11.89%, 1000=74.27%
  lat (msec)   : 2=12.34%, 4=1.23%, 10=0.11%, 20=0.14%, 50=0.01%
  lat (msec)   : 100=0.01%, 250=0.01%, 500=0.01%
  cpu          : usr=1.23%, sys=0.59%, ctx=43234, majf=0, minf=111
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,43205,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=4173KiB/s (4273kB/s), 4173KiB/s-4173KiB/s (4273kB/s-4273kB/s), io=169MiB (177MB), run=41417-41417msec

Disk stats (read/write):
    dm-0: ios=3/1830, merge=0/0, ticks=130/51270, in_queue=51400, util=20.22%, aggrios=4792/2930, aggrmerge=380/376, aggrticks=29555/71226, aggrin_queue=84120, aggrutil=33.63%
  sdb: ios=4792/2930, merge=380/376, ticks=29555/71226, in_queue=84120, util=33.63%
`

**Comment by javagyt** [comment]
@sitsofe 
```
       if (sec < 0 || (sec == 0 && nsec < 0))
               return 0;
```
i discover io start_time > finish_time

**Comment by sitsofe** [comment]
@javagyt,

I've seen latency of zero when I/O is buffered because the request goes to the kernel and is then immediately ready because it's served out of the page cache. I don't know if ceph can do something similar even on direct I/O - you would have to check with the ceph developers. For your most recent fio run the latencies seem in the ballpark for a SATA SSD but there's quite a spread suggesting some sort of interference is happening - maybe this makes sense if it's a VM on a busy hypervisor. At any rate the average sampled iops (1042.85) seem close to the derived one (1043) which looks more sensible than the initial run.

Was this latest run with a newer fio (see https://github.com/axboe/fio/releases for what we're up to)?

**Comment by javagyt** [comment]
@sitso
hi，i do a test again,but i add a new option -> "--clocksource=gettimeofday"
here are my test result:
```
fio --name=test --rw=randwrite --bs=4k --runtime=60 --ioengine=libaio --iodepth=1 --numjobs=1 --filename=/dev/vdb --direct=1 --group_reporting=1 --time_based=1 --eta-newline 1 --clocksource=gettimeofday

test: (groupid=0, jobs=1): err= 0: pid=10506: Sat Jan 11 10:31:14 2020
  write: IOPS=499, BW=1997KiB/s (2045kB/s)(117MiB/60002msec)
    slat (usec): min=5, max=680, avg=28.12, stdev=13.55
    clat (usec): min=660, max=718739, avg=1972.31, stdev=5090.14
     lat (usec): min=687, max=718767, avg=2000.64, stdev=5090.35
    clat percentiles (usec):
     |  1.00th=[   865],  5.00th=[   963], 10.00th=[  1037], 20.00th=[  1156],
     | 30.00th=[  1254], 40.00th=[  1352], 50.00th=[  1483], 60.00th=[  1991],
     | 70.00th=[  2245], 80.00th=[  2442], 90.00th=[  2704], 95.00th=[  2966],
     | 99.00th=[  6980], 99.50th=[ 15401], 99.90th=[ 21103], 99.95th=[ 32113],
     | 99.99th=[223347]
   bw (  KiB/s): min=  608, max= 3624, per=100.00%, avg=2014.02, stdev=564.79, samples=119
   iops        : min=  152, max=  906, avg=503.50, stdev=141.20, samples=119
  lat (usec)   : 750=0.02%, 1000=7.40%
  lat (msec)   : 2=53.02%, 4=37.30%, 10=1.45%, 20=0.66%, 50=0.12%
  lat (msec)   : 100=0.01%, 250=0.02%, 750=0.01%
  cpu          : usr=0.17%, sys=1.62%, ctx=29961, majf=0, minf=5
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,29961,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=1997KiB/s (2045kB/s), 1997KiB/s-1997KiB/s (2045kB/s-2045kB/s), io=117MiB (123MB), run=60002-60002msec

Disk stats (read/write):
  vdb: ios=14/29904, merge=0/0, ticks=0/59440, in_queue=59440, util=99.12%
```
this result looks more reasonable. fio default use clock_gettime in this VM.
i don't know why clock_gettime got a unreasonable result.

**Comment by sitsofe** [comment]
@javagyt,

Just to let you know `sitso` is a different (and unrelated) Github user to me (I'm sitsofe :-).

I've requested this before but I'm going to be more explicit because this is important:

**Please can you test to see if your problem still exists in the latest fio from the master branch git and let us know the result?** If you can't do so then I'm afraid we're going to have to close this issue until such a point you can because we don't have the resources to support old versions of fio...

As to your latest comment, it could well be you different results with different clocks but be aware that `gettimeofday()` is impacted by things like NTP adjustments and the resolution may not be as fine as `clock_gettime()` (but it's your system so of course you can use what you like :-) ). Further, depending on the kernel and hardware `gettimeofday()` may have lower overhead than `clock_gettime()` but this should be fixed from >=5.3 kernels (see https://github.com/axboe/fio/issues/533#issuecomment-544223085 ).

**Comment by javagyt** [comment]
@sitsofe 
this is kernel version problem，arm 4.11 kernel have a defect.
https://github.com/torvalds/linux/commit/3d88d56c5873f6eebe23e05c3da701960146b801
so,my VM kernel version 4.11 upgrade to 4.18，this problem solved.

**Comment by sitsofe** [comment]
@javagyt Glad to hear you fixed it! I'll close the issue here as this was not an fio issue.
