### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [axboe/fio#917]
Would you like to add more error handling for return values from functions like the following?
- [pthread_mutex_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [init_zone_info](https://github.com/axboe/fio/blob/2198a6b5a9f40726b40aced24cf2dcdb3b639898/zbd.c#L367)
- [strdup](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [get_mult_time](https://github.com/axboe/fio/blob/5a9d5c4ab5f7cea83dc94e7cd23ecceb45b68134/parse.c#L182)

**Comment by sitsofe** [comment]
What will more complete handling look like and do?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by sitsofe** [comment]
@elfring I see... I suggest you give it a go on just one and we'll see how much more complicated the result looks.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by sitsofe** [comment]
@elfring In general I'm for things that improve code quality so long as:
- The change isn't too frivolous
- The change being made isn't done blindly just because the analyser said so (i.e. the person making the change has to be able to reason about it themselves too)
- The change doesn't make the code contorted and hard to read

Fio isn't an internet facing service (at least I wouldn't set up to be ;-) ) so I'd argue certain categories of failure will just result in it blowing up in the users face when all it could have done is exit as opposed to becoming a remote security hole so that reduces the urgency of such work. I've run various analysers over fio in the past but it's a lot of work to fix every warning to make them completely happy so it's a balance.

While fixing analyser issues is a start don't forget fio has a backlog of issues (e.g. https://github.com/axboe/fio/issues?q=is%3Aissue+is%3Aopen+label%3Aneedsattention , https://github.com/axboe/fio/issues?q=is%3Aissue+is%3Aopen+label%3Abug , https://github.com/axboe/fio/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement ) which would be of even greater benefit to the project if you want to help more :-)

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Comment by elfring** [comment]
The source code contains still [open issues](https://github.com/axboe/fio/blob/a06be957386f23a0ac94f215cd1e23e6f4c93161/engines/ime.c#L778 "Update candidate: fio_ime_aio_init()"), doesn't it?
