### ISSUE TITLE
false pass when changing rand_seed.

### ISSUE THREAD

**Issue by shoshan-lb** [axboe/fio#933]
Hi 

There is false pass when changing rand_seed in verify_only.

What have i missed in workloads? or it's a bug in fio 3.18?

I've run the following workloads:
 
1. write random, with a rand_seed.
```
[global]
ioengine=libaio
iodepth=32
runtime=0
cpus_allowed_policy=split
group_reporting=1
cpus_allowed=0-0
do_verify=1
verify=sha512
bs=4096
filename=/dev/nvme0n2
direct=1
loops=1
percentile_list=99:99.9:99.99:99.999:99.9999
norandommap
random_generator=lfsr
rw=randwrite
verify_fatal=1
allrandrepeat=0
randseed=44234

[job_0]
offset=0
size=52428800

```

test pass.

2. write random, with other rand_seed and verify_only=1.
**job is expected to fail but it pass successfully.**
```
[global]
ioengine=libaio
iodepth=32
runtime=0
cpus_allowed_policy=split
group_reporting=1
cpus_allowed=0-0
do_verify=1
verify=sha512
bs=4096
filename=/dev/nvme0n2
direct=1
loops=1
percentile_list=99:99.9:99.99:99.999:99.9999
norandommap
random_generator=lfsr
rw=randwrite
verify_fatal=1
allrandrepeat=0
randseed=99
verify_only=1
[job_0]
offset=0
size=52428800
```
output of second job: 
```
job_0: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=32
fio-3.18
Starting 1 process

job_0: (groupid=0, jobs=1): err= 0: pid=4165: Mon Feb 24 11:16:50 2020
  read: IOPS=6333, BW=24.7MiB/s (25.9MB/s)(50.0MiB/2021msec)
    slat (usec): min=4, max=111, avg=16.84, stdev= 4.66
    clat (usec): min=191, max=5939, avg=4885.49, stdev=194.57
     lat (usec): min=206, max=5954, avg=4902.81, stdev=194.61
    clat percentiles (usec):
     | 99.0000th=[ 5211], 99.9000th=[ 5604], 99.9900th=[ 5932],
     | 99.9990th=[ 5932], 99.9999th=[ 5932]
  lat (usec)   : 250=0.01%, 500=0.01%, 750=0.01%, 1000=0.01%
  lat (msec)   : 2=0.05%, 4=0.10%, 10=49.81%, >=2000=50.00%
  cpu          : usr=80.79%, sys=10.26%, ctx=22986, majf=0, minf=315
  IO depths    : 1=50.0%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=49.9%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.1%, 64=0.0%, >=64=0.0%
     issued rwts: total=12800,12800,0,0 short=0,0,0,0 dropped=0,0,0,0

Run status group 0 (all jobs):
   READ: bw=24.7MiB/s (25.9MB/s), 24.7MiB/s-24.7MiB/s (25.9MB/s-25.9MB/s), io=50.0MiB (52.4MB), run=2021-2021msec

Disk stats (read/write):
  nvme0n2: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%`
```

**Comment by sitsofe** [comment]
> What have i missed in workloads?

You've missed (because it's not documented) that split verification (where you use two entirely separate jobs or even fio invocation where the first does the write and the other does the verifying reads) does not check the seed because in the usual case it cannot know what the seed is. This means that split verification only make sense if you can somehow guarantee that ALL the I/O the second verifying job will read were actually written and it can't tell an old (but correctly sized) block from an old run from that of a new run.

>  or it's a bug in fio 3.18?

I believe it's been that way forever... do you get different behaviour with an older fio?

**Comment by shoshan-lb** [comment]
Proceeding  @sitsofe  clarifications and undocumented limitations.
How can rand_seed be used with verify_only?

best regards,
Shoshan

**Comment by sitsofe** [comment]
> Proceeding @sitsofe clarifications and undocumented limitations.

I'm afraid I don't understand what this sentence is saying in this context...

> How can rand_seed be used with verify_only?

If I'm reading https://github.com/axboe/fio/blob/58d3994d9be0783990af82571cea819b499d526c/verify.c#L927 correctly then **it can't** in the way you are expecting - you only get `rand_seed` verification with jobs that happen to be read/write and not using `verify_backlog`. Forcing the first part of a split verification to be a read/write likely won't do what you want it to do and split verification expects both jobs to have (near enough) the same parameters in order to work correctly.

The reasoning for the lack of rand_seed verification seems to be given in the commit message of https://github.com/axboe/fio/commit/c4b6117b236370b174f3e3d2e299bf8b3733be97 (and bear in mind that verify sorting was removed in https://github.com/axboe/fio/commit/f31feaa21642929b6d9d5396b73669372fda9a0a so that workaround is no longer available for use).

**Comment by shoshan-lb** [comment]
According to Line 927 in 58d3994.

first part of write using rand_seed without backlog would be as below
How can rand_seed be used in the second part of verify_only?

[global]
verify_backlog=0    //not using backlog
ioengine=libaio
iodepth=32
runtime=0
cpus_allowed_policy=split
group_reporting=1
cpus_allowed=0-0
do_verify=1
verify=sha512
bs=4096
filename=/dev/nvme0n2
direct=1
loops=1
percentile_list=99:99.9:99.99:99.999:99.9999
norandommap
random_generator=lfsr
rw=randrw
verify_fatal=1
allrandrepeat=0
randseed=44234


[job_0]
offset=0
size=52428800

**Comment by sitsofe** [comment]
@shoshan-lb :

> verify=sha512
> [...]
> rw=randrw

**Are you sure this is going to do what you want it to and won't trigger some other issues?** Did you miss the warning I put above:

> Forcing the first part of a split verification to be a read/write likely won't do what you want it to do

I don't think the path you are taking will have a happy ending - I foresee you will find more and more issues as you go further down the rabbit hole... I'm afraid I don't have time to help you down explore that route. 

> How can rand_seed be used in the second part of verify_only?

I'll be explicit - unless you're going to change the source code of fio to implement the logic to handle things I don't think fio 3.18 will do what you are attempting to make it do correctly (do a split verification that ALSO checks the seed for a given block is correct versus what was done for the "original" run). It looks like a useful thing to do but I'm afraid I don't have time to work on such a new feature myself (but if a good patch was submitted I might try reviewing it).

(FWIW: in the past I would do things like using a different block size between verification passes to ensure that stale data from an old pass was not picked up as valid data from a subsequent pass but I understand that's different to what you're asking)

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
