### ISSUE TITLE
fio - remote server - fio: waitpid: Function not implemented

### ISSUE THREAD

**Issue by Prabhu088** [axboe/fio#940]
I am trying to start fio server on windows machine and i hit with below error messages:

```
fio --version
fio-3.18
```

```
C:\Users\Administrator>fio --server fio --server=ip:192.168.0.33
fio: server listening on 192168.0.33,8765

fio: waitpid: Function not implemented
waitpid is not implemented
```

**Comment by sitsofe** [comment]
Known issue with Windows not implementing waitpid/forking (see https://www.spinics.net/lists/fio/msg04590.html ). The short of it is you can't use client/server mode to a Windows fio and this won't be fixed until/unless someone submits support for fio's server component using threads rather than processes.
