### ISSUE TITLE
FILE_FLAG_WRITE_THROUGH and storage caching

### ISSUE THREAD

**Issue by rrg92** [axboe/fio#945]
https://github.com/axboe/fio/blob/3bd2078bdd1c173f9d02bc20e2d630302555a8a0/engines/windowsaio.c#L203

I guess that specifying FILE_FLAG_WRITE_THROUGH only when sync I/O is true is not the correct way to completely bypass caches.

Please, can you  check the doc https://docs.microsoft.com/pt-br/windows/win32/api/fileapi/nf-fileapi-createfilea#caching-behavior  specially in this part:

![image](https://user-images.githubusercontent.com/16887793/77121908-13f97c00-6a1b-11ea-9ade-6bb4494f18b6.png)

I guess tha tin some cases, using windowsaio, request can be to storage cache.

**Comment by sitsofe** [comment]
@rrg92 In Linux land direct I/O has never implied that you bypass hardware caches (see https://stackoverflow.com/a/49462406 ) and it is quite possible for direct I/O to end up in a hardware volatile cache. Setting sync means you don't want the I/O to return until the disk has confirmed the data is on non-volatile storage (which mean it can be done via write-through or cache flushing etc). Fio preserves this semantic in its Windows port. 

You get what you want by enabling direct=1 AND [sync=1](https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-sync) but note the caveat on the page you linked:

> Note  Not all hard disk hardware supports this write-through capability.

So even on Windows there are no guarantees you'll get hardware write-through anyway. For example - why would the disk bother going to such an extent if it provides methods to know when the volatile data has been flushed / if the cache is non-volatile?

Given the above this does not sound like a bug in fio...

**Comment by rrg92** [comment]
I agree the fact Microsoft doc statement about no there are guarantees. But is is a possibility.

For example, using diskspd tool with equivalent set of parameters, I received different results from metric. The only difference is that diskspd do this flag. BEcause this, i wonder why fio can get more performance than diskspd.

These parameters i used:

diskspd -b8K -d30 -o4 -t8 -h -r -w25 -L -Z1G -c20G S:\PSQL01-DATA\dba\test.dat -

A question: If we specify sync = 1, the request will go assyncrhnous on windowioengine?

**Comment by sitsofe** [comment]
> I received different results from metric.

That's sadly not uncommon. See #875 ...

> A question: If we specify sync = 1, the request will go assyncrhnous on windowioengine?

In this case `sync=1` means each I/O must be acknowledged by the hardware. If I can queue up multiple such I/Os and do more queuing when any of them return am I still synchronous? :-)

(The I/O engine windowsaio itself is async so should be able to have multiple I/Os in flight regardless of sync but each I/O might take longer to return because the hardware of the disk can't cache them).

**Comment by rrg92** [comment]
Right. Thanks explanations @sitsofe !

**Comment by gonchik** [comment]
How does it works for the following setup? 
App send FILE_FLAG_WRITE_THROUGH 

- Then Wiindows server 2022
- That VM located on Vmware 8 
- SAN is PureStorage with additional caching

I am asking because looks like Windows gets ACK from virtual hardware instead of lower level, or I it's not correct?

**Comment by axboe** [comment]
This isn't a fio question, it's a Windows IO behavior question. But yes, if you're running in a vm, then the completion you get will be based on the virtual hardware. How that relates to the lower level is very much vm and setting dependent.
