### ISSUE TITLE
Fail to read big file

### ISSUE THREAD

**Issue by runzhiwang** [axboe/fio#957]
Environment: fio-3.19, goofys 0.19.0
1. When read a 32M file, it failed.
![image](https://user-images.githubusercontent.com/51938049/79102387-3c1b9700-7d9d-11ea-9bf9-87962cdd39d2.png)
2. But when read a 16K file, it succeed. 
![image](https://user-images.githubusercontent.com/51938049/79102535-7f760580-7d9d-11ea-80fe-1e47608c269b.png)

I want to test the efficiency of goofys when read a big file, but fio can not read a big file. Could someone help me ? Thank you very much.

**Comment by axboe** [comment]
This is a pretty basic use case, and I just checked your exact set of parameters and it works fine for me (for both of them). Not sure what's going on there, but I'm going to go out on a limb and say it's related to goofys. I'm assuming the same run works fine for you on a local directory on the same machine? If so, don't really think this is a fio issue.

**Comment by runzhiwang** [comment]
@axboe Thank you very much. I have another question. I find the write speed of fio can reach 1GB per second, but the write speed of dd in the same directory is only 100MB per second.  Why fio is so faster than dd ?

**Comment by sitsofe** [comment]
@runzhiwang It's hard to say for sure because we can't see just how you ran `dd` or just what the properties of your system are. For example `dd` has to read from somewhere before putting that data somewhere else and doing that has an overhead (especially if the place being read is "slow") but that is just one of many possible explanations...

At this point we're getting offtopic for an fio "issue" and into more of "How do I/Why is?". These types of questions are better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.19/README#L58) (note that the list only accepts plain text emails). As such, let's close this here and you can continue your questions on the list if you wish. Thanks!
