### ISSUE TITLE
multiple output formats each in a seperate file output file

### ISSUE THREAD

**Issue by tvtue** [axboe/fio#977]
Hi, 
as it is possible to generate multiple output formats by specifing --output-format=json,terse,normal is it somehome possible to put the output in different output files? 

If not this may be a RFE so that one can get this by specifying

--output=fio.out.json,fio.out.csv,fio.out.normal

Cheers and have nice day
timo

**Comment by sitsofe** [comment]
@tvtue Hi!

I don't think you can (as `output` only takes one filename and you would need a system to say which output goes to which file).

The problem with the format you're suggesting is that `,` is a valid character in a filename on at least Linux so I don't know I'd be happy accepting it for splitting purposes but I would imagine something could be done around the general idea (e.g. maybe a different parameter for each etc)...

As we seem to stack up a lot of RFEs that haven't seen attention would it be possible for you (or someone else) to submit a diff and we can review it? I'll close if it not but even if this issue is closed later we can re-open it if a good diff comes along...

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If someone wants to work on this issue please re-open after submitting a pr/patch and mention the patch fixes this issue. Thanks!
